import { useDeferredValue, useEffect, useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Search, SlidersHorizontal } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { Header } from '@/components/storefront/Header';
import { Footer } from '@/components/storefront/Footer';
import { ProductCard } from '@/components/storefront/ProductCard';
import { StoreBackdrop } from '@/components/storefront/StoreBackdrop';
import { BrandGlyph } from '@/components/storefront/BrandGlyph';
import { apiGet } from '@/lib/api';
import type { BrandId, Product } from '@/lib/types';
import { AnimatedContent } from '@/components/motion/AnimatedContent';

type Category={id:number;brandId:BrandId;name:string;slug:string};

export function CatalogPage(){
  const[params,setParams]=useSearchParams();const brand=(params.get('brand')==='enyerbados'?'enyerbados':'amargos') as BrandId;const category=params.get('category')||'';const initialQ=params.get('q')||'';const[search,setSearch]=useState(initialQ);const deferredSearch=useDeferredValue(search.trim());const[limit,setLimit]=useState(48);const[sort,setSort]=useState<'order'|'price-asc'|'price-desc'|'name'>('order');const[inStock,setInStock]=useState(false);
  useEffect(()=>setSearch(initialQ),[initialQ]);
  useEffect(()=>setLimit(48),[brand,category,deferredSearch]);
  useEffect(()=>{if(params.has('collection')){const next=new URLSearchParams(params);next.delete('collection');setParams(next,{replace:true});}},[params,setParams]);
  const products=useQuery({queryKey:['catalog',brand,category,deferredSearch,limit],queryFn:()=>apiGet<Product[]>(`/api/products?brand=${brand}${category?`&category=${encodeURIComponent(category)}`:''}${deferredSearch?`&q=${encodeURIComponent(deferredSearch)}`:''}&limit=${limit}`),staleTime:2*60_000,placeholderData:(previous)=>previous});const categories=useQuery({queryKey:['categories',brand],queryFn:()=>apiGet<Category[]>(`/api/categories?brand=${brand}`),staleTime:5*60_000});
  const filtered=useMemo(()=>{const arr=(products.data||[]).filter(p=>!inStock||Number(p.stockQty)>0);return [...arr].sort((a,b)=>sort==='price-asc'?Number(a.price)-Number(b.price):sort==='price-desc'?Number(b.price)-Number(a.price):sort==='name'?a.name.localeCompare(b.name):(Number(a.sortOrder??9999)-Number(b.sortOrder??9999)||Number(b.id)-Number(a.id)));},[products.data,inStock,sort]);
  const setCategory=(next:string)=>{const p=new URLSearchParams(params);next?p.set('category',next):p.delete('category');p.delete('q');setParams(p);};const setBrand=(b:BrandId)=>{const p=new URLSearchParams(params);p.set('brand',b);p.delete('category');p.delete('q');setParams(p);};const en=brand==='enyerbados';
  return <main className={`storefront-page ${en?'storefront-page--yellow':'storefront-page--green'} min-h-screen pt-[94px] sm:pt-[108px]`}><StoreBackdrop brand={brand}/><div className="storefront-content"><Header brand={brand} solid/><section className="px-3 pb-16 pt-4 sm:px-5 lg:px-8 lg:pb-24 lg:pt-8"><div className="catalog-surface mx-auto max-w-[1640px] rounded-[30px] px-4 py-7 sm:rounded-[38px] sm:px-7 sm:py-10 lg:px-10 lg:py-12"><AnimatedContent className="grid gap-7 border-b border-black/8 pb-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="inline-flex items-center gap-2 font-mono-ui text-[8px] font-bold uppercase tracking-[.22em] text-black/38"><BrandGlyph kind={en?'yerba':'mate'} className="h-4 w-4"/>{en?'Bien Yerbados':'Bien Amargos'}</div><h1 className="mt-2 text-5xl font-black tracking-[-.07em] text-[#14241a] sm:text-7xl lg:text-[88px]">Tienda.</h1><p className="mt-3 max-w-xl text-sm font-semibold text-black/45">Elegí lo tuyo. Las dos marcas comparten el mismo carrito.</p></div><div className="flex w-fit rounded-[15px] border border-black/8 bg-[#f8f3e8]/80 p-1"><button onClick={()=>setBrand('amargos')} className={`inline-flex min-h-10 items-center gap-2 rounded-[11px] px-4 text-[10px] font-black ${brand==='amargos'?'bg-[#164b36] text-white':'text-black/45'}`}><BrandGlyph kind="mate" className="h-4 w-4"/>Amargos</button><button onClick={()=>setBrand('enyerbados')} className={`inline-flex min-h-10 items-center gap-2 rounded-[11px] px-4 text-[10px] font-black ${brand==='enyerbados'?'bg-[#d7c6ad] text-[#17311f]':'text-black/45'}`}><BrandGlyph kind="yerba" className="h-4 w-4"/>Yerbados</button></div></AnimatedContent>
    <div className="mt-5 grid gap-3 xl:grid-cols-[1fr_auto]"><div className="hide-scrollbar flex gap-2 overflow-x-auto"><button onClick={()=>setCategory('')} className={`catalog-chip ${!category?'is-active':''}`}>Todo</button>{(categories.data||[]).map(c=><button key={c.id} onClick={()=>setCategory(c.slug)} className={`catalog-chip ${category===c.slug?'is-active':''}`}>{c.name}</button>)}</div><div className="flex flex-col gap-2 sm:flex-row"><label className="catalog-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto"/></label><label className="catalog-select"><SlidersHorizontal size={14}/><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="order">Orden de tienda</option><option value="price-asc">Precio: menor</option><option value="price-desc">Precio: mayor</option><option value="name">Nombre</option></select></label><button onClick={()=>setInStock(v=>!v)} className={`catalog-stock-toggle ${inStock?'is-active':''}`}>Con stock</button></div></div>
    <div className="mt-5 flex items-center justify-between"><div className="font-mono-ui text-[8px] uppercase tracking-[.16em] text-black/34">{filtered.length} productos</div>{search&&<button onClick={()=>setSearch('')} className="text-[9px] font-black text-black/40">Limpiar búsqueda ×</button>}</div><div className="mt-5 grid grid-cols-1 gap-3 min-[390px]:grid-cols-2 sm:gap-4 lg:grid-cols-3 xl:grid-cols-4">{products.isLoading?Array.from({length:8}).map((_,i)=><div key={i} className="aspect-[.72] animate-pulse rounded-[26px] bg-[#f8f3e8]/75"/>):filtered.map(p=><ProductCard key={p.id} product={p}/>)}</div>{!products.isLoading&&!filtered.length&&<div className="mt-12 rounded-[24px] border border-dashed border-black/12 bg-[#f8f3e8]/72 p-12 text-center text-sm font-bold text-black/42">No encontramos productos con esos filtros.</div>}{!products.isLoading&&(products.data?.length||0)>=limit&&limit<120&&<div className="mt-8 flex justify-center"><button type="button" onClick={()=>setLimit(current=>Math.min(120,current+48))} className="store-subtle-button min-h-11">Ver más productos</button></div>}</div></section><Footer brand={brand}/></div></main>;
}
