import { useEffect, useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, Compass, MapPin, Search, Sparkles } from 'lucide-react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { Link } from 'react-router-dom';
import { apiGet } from '@/lib/api';
import type { MateroLocation, MaterosPayload } from '@/lib/types';
import { Header } from '@/components/storefront/Header';
import { Footer } from '@/components/storefront/Footer';
import { StoreBackdrop } from '@/components/storefront/StoreBackdrop';
import { WorldMapCanvas } from '@/components/storefront/WorldMapCanvas';
import { AnimatedContent } from '@/components/motion/AnimatedContent';
import { CountUp } from '@/components/motion/CountUp';

export function WorldMapPage(){
  useEffect(()=>{
    const meta=document.querySelector<HTMLMetaElement>('meta[name="description"]'); const prev=meta?.content||'';
    const canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]'); const prevCanonical=canonical?.href||'';
    document.title='Materos por el mundo | Bien Amargos';
    if(meta)meta.content='Materos por el mundo: explorá los lugares que forman parte de la comunidad de Bien Amargos.';
    if(canonical)canonical.href='https://bienamargos.com.ar/materos-por-el-mundo';
    return()=>{if(meta)meta.content=prev;if(canonical)canonical.href=prevCanonical;};
  },[]);
  const reduce=useReducedMotion();
  const q=useQuery({queryKey:['world-maters'],queryFn:()=>apiGet<MaterosPayload>('/api/world-maters'),staleTime:120_000});
  const [term,setTerm]=useState(''); const [filter,setFilter]=useState<'all'|'argentina'|'world'>('all'); const [selected,setSelected]=useState<MateroLocation|null>(null);
  const locations=q.data?.locations||[]; const stats=q.data?.stats||{locations:0,cities:0,provinces:0,countries:0};
  const filtered=useMemo(()=>locations.filter(x=>{const blob=[x.name,x.city,x.province,x.country].filter(Boolean).join(' ').toLowerCase();const matches=!term||blob.includes(term.toLowerCase());const isArg=(x.country||'').toLowerCase().includes('argentina');return matches&&(filter==='all'||(filter==='argentina'?isArg:!isArg));}),[locations,term,filter]);
  const travel=()=>{const pool=filtered.filter(x=>x.featured).length?filtered.filter(x=>x.featured):filtered;if(!pool.length)return;const current=Math.max(-1,pool.findIndex(x=>x.id===selected?.id));setSelected(pool[(current+1)%pool.length]);};

  return <main className="storefront-page storefront-page--green min-h-screen"><StoreBackdrop brand="amargos"/><div className="storefront-content"><Header brand="amargos"/>
    <section className="relative px-3 pb-8 pt-[104px] sm:px-5 sm:pt-[124px] lg:px-8"><div className="world-shell mx-auto max-w-[1640px] overflow-hidden rounded-[30px] sm:rounded-[38px]">
      <div className="grid gap-7 px-5 py-8 sm:px-8 lg:grid-cols-[.78fr_1.22fr] lg:px-12 lg:py-12"><AnimatedContent className="self-center"><Link to="/" className="inline-flex items-center gap-2 font-mono-ui text-[8px] uppercase tracking-[.18em] text-black/40"><ArrowLeft size={13}/> Bien Amargos</Link><div className="mt-8 font-mono-ui text-[8px] uppercase tracking-[.22em] text-[#164b36]">Una ronda sin fronteras</div><h1 className="mt-3 text-[clamp(3rem,7vw,7.4rem)] font-black leading-[.82] tracking-[-.075em] text-[#142019]">Materos<br/>por el mundo.</h1><p className="mt-6 max-w-md text-sm font-semibold leading-6 text-black/50">La ronda llegó más lejos de lo que imaginábamos. Explorá los lugares que ya forman parte de esta historia.</p><div className="mt-8 grid grid-cols-3 gap-2"><Stat n={stats.locations} label="lugares"/><Stat n={stats.provinces} label="provincias"/><Stat n={stats.countries} label="países"/></div></AnimatedContent>
      <AnimatedContent delay={.08} className="relative min-h-[280px] overflow-hidden rounded-[26px] bg-[#13251b] p-5 text-white sm:min-h-[350px]"><div className="absolute inset-0 opacity-25 [background-image:radial-gradient(circle_at_15%_20%,#d7c6ad_0,transparent_26%),radial-gradient(circle_at_85%_65%,#2b7756_0,transparent_30%)]"/><img src="/brand/bien-amargos-mark.png" alt="" className="absolute -bottom-14 -right-10 h-72 w-72 rounded-full object-cover opacity-[.07] mix-blend-screen"/><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between"><div className="flex items-center gap-2 font-mono-ui text-[8px] uppercase tracking-[.2em] text-white/48"><Compass size={14}/> Bien Amargos Atlas</div><button onClick={travel} disabled={!filtered.length} className="inline-flex h-10 items-center gap-2 rounded-full bg-white/10 px-4 text-[9px] font-black backdrop-blur-sm transition hover:bg-white/15 disabled:opacity-30"><Sparkles size={14}/> Recorrer</button></div><div><div className="text-[clamp(2.1rem,4vw,4.5rem)] font-black leading-[.9] tracking-[-.06em] text-[#f7f3ea]">Cada punto<br/>tiene una ronda.</div><div className="mt-4 max-w-sm text-xs font-semibold leading-5 text-white/52">El mapa trabaja con los lugares reales cargados en Ronda Admin.</div></div></div></AnimatedContent></div>

      <div className="grid min-h-[70vh] border-t border-black/7 lg:grid-cols-[360px_1fr]"><aside className="order-2 bg-[#f5f0e5]/98 p-4 lg:order-1 lg:p-5"><div className="flex items-center gap-2 rounded-[14px] border border-black/8 bg-white/80 px-3"><Search size={15} className="text-black/30"/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Ciudad, provincia o país" className="h-11 min-w-0 flex-1 bg-transparent text-xs font-bold outline-none placeholder:text-black/25"/></div><div className="mt-3 grid grid-cols-3 gap-1 rounded-[13px] bg-black/[.04] p-1">{([['all','Todos'],['argentina','Argentina'],['world','Exterior']] as const).map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={`min-h-10 rounded-[10px] px-2 py-2 text-[8px] font-black ${filter===id?'bg-[#164b36] text-white':'text-black/40'}`}>{label}</button>)}</div><div className="mt-4 max-h-[54vh] space-y-2 overflow-auto pr-1"><AnimatePresence initial={false}>{filtered.map((loc,index)=><motion.button layout key={loc.id} initial={reduce?false:{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={reduce?{opacity:0}:{opacity:0,y:-5}} transition={{duration:reduce?0:.2,delay:reduce?0:Math.min(index,7)*.018}} onClick={()=>setSelected(loc)} className={`w-full rounded-[16px] border p-3 text-left transition ${selected?.id===loc.id?'border-[#164b36]/25 bg-[#164b36] text-white':'border-black/6 bg-white/68 hover:bg-white'}`}><div className="flex items-start gap-3"><span className={`mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-full ${selected?.id===loc.id?'bg-white/12':'bg-[#164b36]/8 text-[#164b36]'}`}><MapPin size={15}/></span><div className="min-w-0"><div className="truncate text-[11px] font-black">{loc.name}</div><div className={`mt-1 truncate text-[9px] ${selected?.id===loc.id?'text-white/52':'text-black/34'}`}>{[loc.city,loc.province,loc.country].filter(Boolean).join(' · ')||'Ubicación importada'}</div></div></div></motion.button>)}</AnimatePresence>{!filtered.length&&<div className="rounded-[18px] border border-dashed border-black/10 p-8 text-center text-xs font-bold text-black/30">No hay puntos que coincidan.</div>}</div></aside>
        <div className="relative order-1 min-h-[58vh] lg:order-2"><WorldMapCanvas locations={filtered} selectedId={selected?.id} onSelect={setSelected} className="absolute inset-0"/><AnimatePresence>{selected&&<motion.div key={selected.id} initial={reduce?false:{opacity:0,y:12,scale:.985}} animate={{opacity:1,y:0,scale:1}} exit={reduce?{opacity:0}:{opacity:0,y:8,scale:.99}} className="absolute bottom-[calc(5.6rem+env(safe-area-inset-bottom))] left-4 right-4 z-[500] rounded-[22px] border border-white/65 bg-[#fbf8f1]/96 p-4 shadow-[0_18px_54px_rgba(10,25,15,.20)] backdrop-blur-lg sm:bottom-4 sm:left-auto sm:max-w-sm"><div className="font-mono-ui text-[7px] uppercase tracking-[.18em] text-[#164b36]">{selected.brandId==='enyerbados'?'Bien Yerbados':'Materos por el mundo'}</div><div className="mt-1 text-xl font-black tracking-[-.04em]">{selected.name}</div><div className="mt-1 text-[10px] font-bold text-black/38">{[selected.city,selected.province,selected.country].filter(Boolean).join(' · ')||`${selected.latitude.toFixed(3)}, ${selected.longitude.toFixed(3)}`}</div>{selected.description&&<p className="mt-3 text-xs font-semibold leading-5 text-black/50">{selected.description}</p>}</motion.div>}</AnimatePresence></div>
      </div>
    </div></section><Footer brand="amargos"/></div></main>;
}
function Stat({n,label}:{n:number;label:string}){return <div className="rounded-[16px] border border-black/7 bg-white/68 p-3"><div className="text-2xl font-black tracking-[-.05em]"><CountUp value={n}/></div><div className="mt-1 font-mono-ui text-[7px] uppercase tracking-[.16em] text-black/34">{label}</div></div>}
