import type { FastifyPluginAsync, FastifyRequest } from 'fastify';
import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { PoolConnection } from 'mysql2/promise';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { getUploadRoot } from '../uploads.js';
import { pool } from '../db.js';
import { canAccessBrand, effectiveBrand, hasPermission, permissionsForRole, requireAdmin, requirePermission } from '../auth.js';
import { restoreStockForOrder } from './orders.js';

const loginSchema = z.object({ email: z.string().email(), password: z.string().min(8) });
const imageSchema = z.object({ id: z.number().int().positive().optional(), imageUrl: z.string().min(1).max(500), altText: z.string().max(190).nullable().optional(), sortOrder: z.number().int().min(0).optional() });
const variantSchema = z.object({
  id: z.number().int().positive().optional(), name: z.string().min(1).max(80).default('Color'), value: z.string().min(1).max(120), colorHex: z.string().max(20).nullable().optional(),
  sku: z.string().min(2).max(120), price: z.number().nonnegative().nullable().optional(), compareAtPrice: z.number().nonnegative().nullable().optional(), wholesalePrice: z.number().nonnegative().nullable().optional(), stockQty: z.number().int().min(0),
  lowStockThreshold: z.number().int().min(0).default(2), trackStock: z.boolean().default(true), imageUrl: z.string().max(500).nullable().optional(), imageZoom: z.number().min(0.8).max(1.4).nullable().optional(),
  imagePositionX: z.number().int().min(0).max(100).nullable().optional(), imagePositionY: z.number().int().min(0).max(100).nullable().optional(), imageBlendMode: z.enum(['normal','multiply']).nullable().optional(),
  active: z.boolean().default(true), sortOrder: z.number().int().min(0).default(0), images: z.array(imageSchema).max(12).default([]),
});
const productSchema = z.object({
  brandId: z.enum(['amargos', 'enyerbados']), categoryId: z.number().int().positive().nullable().optional(), name: z.string().min(2).max(190), slug: z.string().min(2).max(190).regex(/^[a-z0-9-]+$/),
  shortDescription: z.string().max(255).nullable().optional(), description: z.string().max(10000).nullable().optional(), seoTitle: z.string().max(190).nullable().optional(), seoDescription: z.string().max(320).nullable().optional(),
  sku: z.string().min(2).max(100), price: z.number().nonnegative(), compareAtPrice: z.number().nonnegative().nullable().optional(), wholesaleEnabled: z.boolean().default(false), wholesalePrice: z.number().nonnegative().nullable().optional(), wholesaleMinQty: z.number().int().min(1).max(9999).default(6), stockQty: z.number().int().min(0), lowStockThreshold: z.number().int().min(0).default(3),
  trackStock: z.boolean().default(true), featured: z.boolean().default(false), collectionFeatured: z.boolean().default(false), active: z.boolean().default(true), sortOrder: z.number().int().min(0).max(999999).default(9999),
  imageUrl: z.string().max(500).nullable().optional(), imageZoom: z.number().min(0.8).max(1.4).default(1.08), imagePositionX: z.number().int().min(0).max(100).default(50), imagePositionY: z.number().int().min(0).max(100).default(50),
  imageBlendMode: z.enum(['normal','multiply']).default('normal'), images: z.array(imageSchema).max(20).default([]), variants: z.array(variantSchema).max(40).default([]), confirmVariantArchive: z.boolean().optional().default(false),
});
const bannerSchema = z.object({
  brandId: z.enum(['amargos','enyerbados']).nullable().optional(), eyebrow: z.string().max(120).nullable().optional(), title: z.string().min(2).max(190), subtitle: z.string().max(255).nullable().optional(),
  imageUrl: z.string().min(1).max(500), mobileImageUrl: z.string().max(500).nullable().optional(), objectPositionDesktop: z.string().max(80).default('50% 50%'), objectPositionMobile: z.string().max(80).default('50% 50%'),
  ctaLabel: z.string().max(80).nullable().optional(), href: z.string().max(500).nullable().optional(), sortOrder: z.number().int().min(0).max(9999).default(0), active: z.boolean().default(true),
});

const sellStatuses = "('confirmed','preparing','ready','completed')";
const openStatuses = "('pending','confirmed','preparing','ready')";
const orderTransitions: Record<string, string[]> = {
  pending: ['confirmed','cancelled'], confirmed: ['preparing','cancelled'], preparing: ['ready','cancelled'], ready: ['completed'], completed: [], cancelled: [], expired: [],
};

function canTransitionOrder(from:string,to:string){ return Boolean(orderTransitions[from]?.includes(to)); }
function clampLimit(raw:unknown, fallback=100, max=500){ const n=Number(raw); return Number.isFinite(n)?Math.max(1,Math.min(max,Math.trunc(n))):fallback; }
function parsePage(raw:unknown){ const n=Number(raw); return Number.isFinite(n)?Math.max(1,Math.trunc(n)):1; }

async function audit(request:any, action:string, entityType:string, entityId?:string|number|null, detail?:unknown){
  try { await pool.query('INSERT INTO audit_logs (admin_id,action,entity_type,entity_id,detail_json,ip_address) VALUES (?,?,?,?,?,?)',[request.user?.id||null,action,entityType,entityId==null?null:String(entityId),detail?JSON.stringify(detail):null,request.ip||null]); } catch {}
}
async function orderBrands(orderId:number){ const [rows]=await pool.query<any[]>('SELECT DISTINCT brand_id AS brandId FROM order_items WHERE order_id=?',[orderId]); return rows.map(r=>String(r.brandId)); }
async function mayOperateOrder(request:FastifyRequest, orderId:number){ const scope=request.user.brandScope; if(!scope)return true; const brands=await orderBrands(orderId); return brands.length===1 && brands[0]===scope; }

async function enrichProducts(products:any[]) {
  if (!products.length) return products;
  const ids=products.map(p=>Number(p.id)); const ph=ids.map(()=>'?').join(',');
  const [images]=await pool.query<any[]>(`SELECT id,product_id AS productId,image_url AS imageUrl,alt_text AS altText,sort_order AS sortOrder FROM product_images WHERE product_id IN (${ph}) ORDER BY sort_order,id`,ids);
  const [variants]=await pool.query<any[]>(`SELECT id,product_id AS productId,name,value,color_hex AS colorHex,sku,price,compare_at_price AS compareAtPrice,wholesale_price AS wholesalePrice,stock_qty AS stockQty,low_stock_threshold AS lowStockThreshold,track_stock AS trackStock,image_url AS imageUrl,image_zoom AS imageZoom,image_position_x AS imagePositionX,image_position_y AS imagePositionY,image_blend_mode AS imageBlendMode,active,sort_order AS sortOrder FROM product_variants WHERE product_id IN (${ph}) AND archived=0 ORDER BY sort_order,id`,ids);
  const vIds=variants.map(v=>Number(v.id)); let vImages:any[]=[];
  if(vIds.length){const vph=vIds.map(()=>'?').join(',');const [rows]=await pool.query<any[]>(`SELECT id,variant_id AS variantId,image_url AS imageUrl,alt_text AS altText,sort_order AS sortOrder FROM product_variant_images WHERE variant_id IN (${vph}) ORDER BY sort_order,id`,vIds);vImages=rows;}
  const pi=new Map<number,any[]>(); images.forEach(x=>pi.set(Number(x.productId),[...(pi.get(Number(x.productId))||[]),x]));
  const vi=new Map<number,any[]>(); vImages.forEach(x=>vi.set(Number(x.variantId),[...(vi.get(Number(x.variantId))||[]),x]));
  const vp=new Map<number,any[]>(); variants.forEach(v=>{v.images=vi.get(Number(v.id))||[];vp.set(Number(v.productId),[...(vp.get(Number(v.productId))||[]),v]);});
  return products.map(p=>{const vs=vp.get(Number(p.id))||[];return {...p,stockQty:vs.length?vs.filter(v=>v.active).reduce((s,v)=>s+Number(v.stockQty||0),0):Number(p.stockQty),variantCount:vs.filter(v=>v.active).length,images:pi.get(Number(p.id))||[],variants:vs};});
}

async function loadAdminProduct(productId:number){
  const [rows]=await pool.query<any[]>(`SELECT p.id,p.brand_id AS brandId,p.category_id AS categoryId,p.name,p.slug,p.short_description AS shortDescription,p.description,p.seo_title AS seoTitle,p.seo_description AS seoDescription,p.sku,p.price,p.compare_at_price AS compareAtPrice,p.wholesale_enabled AS wholesaleEnabled,p.wholesale_price AS wholesalePrice,p.wholesale_min_qty AS wholesaleMinQty,p.stock_qty AS stockQty,p.low_stock_threshold AS lowStockThreshold,p.track_stock AS trackStock,p.featured,p.collection_featured AS collectionFeatured,p.sort_order AS sortOrder,p.active,p.image_url AS imageUrl,p.image_zoom AS imageZoom,p.image_position_x AS imagePositionX,p.image_position_y AS imagePositionY,p.image_blend_mode AS imageBlendMode,c.name AS categoryName,c.slug AS categorySlug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.id=? LIMIT 1`,[productId]);
  if(!rows.length)return null;
  return (await enrichProducts(rows))[0];
}

type ChildImage = { id?: number; imageUrl: string; altText?: string | null; sortOrder?: number };
type ImageTableConfig = { table: 'product_images' | 'product_variant_images'; ownerColumn: 'product_id' | 'variant_id' };

function normalizeImages(images: ChildImage[]) {
  const seen = new Set<string>();
  return images
    .map((image) => ({ ...image, imageUrl: String(image.imageUrl || '').trim() }))
    .filter((image) => {
      if (!image.imageUrl || seen.has(image.imageUrl)) return false;
      seen.add(image.imageUrl);
      return true;
    });
}

async function syncImageRows(conn: PoolConnection, config: ImageTableConfig, ownerId: number, requested: ChildImage[]) {
  const images = normalizeImages(requested);
  const [existing] = await conn.query<RowDataPacket[]>(
    `SELECT id,image_url AS imageUrl,alt_text AS altText,sort_order AS sortOrder FROM ${config.table} WHERE ${config.ownerColumn}=? ORDER BY sort_order,id`,
    [ownerId],
  );
  const byId = new Map(existing.map((row: any) => [Number(row.id), row]));
  const byUrl = new Map<string, any[]>();
  for (const row of existing as any[]) {
    const url = String(row.imageUrl || '');
    byUrl.set(url, [...(byUrl.get(url) || []), row]);
  }
  const kept = new Set<number>();

  for (let index = 0; index < images.length; index++) {
    const image = images[index];
    let row: any = image.id ? byId.get(Number(image.id)) : undefined;
    if (row && kept.has(Number(row.id))) row = undefined;
    if (!row) row = (byUrl.get(image.imageUrl) || []).find((candidate) => !kept.has(Number(candidate.id)));

    if (row) {
      const rowId = Number(row.id);
      kept.add(rowId);
      await conn.query(
        `UPDATE ${config.table} SET image_url=?,alt_text=?,sort_order=? WHERE id=? AND ${config.ownerColumn}=?`,
        [image.imageUrl, image.altText || null, index, rowId, ownerId],
      );
    } else {
      const [result] = await conn.query<ResultSetHeader>(
        `INSERT INTO ${config.table} (${config.ownerColumn},image_url,alt_text,sort_order) VALUES (?,?,?,?)`,
        [ownerId, image.imageUrl, image.altText || null, index],
      );
      kept.add(Number(result.insertId));
    }
  }

  const toDelete = (existing as any[]).map((row) => Number(row.id)).filter((id) => !kept.has(id));
  if (toDelete.length) {
    const placeholders = toDelete.map(() => '?').join(',');
    await conn.query(`DELETE FROM ${config.table} WHERE ${config.ownerColumn}=? AND id IN (${placeholders})`, [ownerId, ...toDelete]);
  }
}

async function saveProductChildren(conn: PoolConnection, productId:number, images:ChildImage[], variants:any[]) {
  await syncImageRows(conn, { table: 'product_images', ownerColumn: 'product_id' }, productId, images);

  const [existingRows]=await conn.query<RowDataPacket[]>('SELECT id FROM product_variants WHERE product_id=? AND archived=0',[productId]);
  const existingIds=new Set(existingRows.map((row:any)=>Number(row.id)));
  const providedIds=variants.filter(v=>v.id!=null).map(v=>Number(v.id));
  for(const id of providedIds){if(!existingIds.has(id))throw new Error('Una variante no pertenece a este producto. Recargá el editor e intentá de nuevo.');}
  const keep=new Set(providedIds);
  for(const row of existingRows) if(!keep.has(Number((row as any).id))) await conn.query('UPDATE product_variants SET active=0,archived=1 WHERE id=? AND product_id=?',[(row as any).id,productId]);

  for(let i=0;i<variants.length;i++){
    const v=variants[i]; let id=Number(v.id||0);
    if(id){
      const [rawResult]=await conn.query(`UPDATE product_variants SET name=?,value=?,color_hex=?,sku=?,price=?,compare_at_price=?,wholesale_price=?,stock_qty=?,low_stock_threshold=?,track_stock=?,image_url=?,image_zoom=?,image_position_x=?,image_position_y=?,image_blend_mode=?,active=?,archived=0,sort_order=? WHERE id=? AND product_id=?`,[v.name,v.value,v.colorHex||null,v.sku,v.price??null,v.compareAtPrice??null,v.wholesalePrice??null,v.stockQty,v.lowStockThreshold,v.trackStock?1:0,v.imageUrl||null,v.imageZoom??null,v.imagePositionX??null,v.imagePositionY??null,v.imageBlendMode??null,v.active?1:0,v.sortOrder??i,id,productId]);
      const result=rawResult as ResultSetHeader;
      if(!result.affectedRows)throw new Error('No pudimos actualizar una variante. Recargá el editor e intentá de nuevo.');
    }else{
      const [rawResult]=await conn.query(`INSERT INTO product_variants (product_id,name,value,color_hex,sku,price,compare_at_price,wholesale_price,stock_qty,low_stock_threshold,track_stock,image_url,image_zoom,image_position_x,image_position_y,image_blend_mode,active,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[productId,v.name,v.value,v.colorHex||null,v.sku,v.price??null,v.compareAtPrice??null,v.wholesalePrice??null,v.stockQty,v.lowStockThreshold,v.trackStock?1:0,v.imageUrl||null,v.imageZoom??null,v.imagePositionX??null,v.imagePositionY??null,v.imageBlendMode??null,v.active?1:0,v.sortOrder??i]);
      const result=rawResult as ResultSetHeader;id=Number(result.insertId);
    }
    await syncImageRows(conn, { table: 'product_variant_images', ownerColumn: 'variant_id' }, id, v.images || []);
  }
}

export const adminRoutes:FastifyPluginAsync=async(app)=>{
  app.post('/api/admin/auth/login',{config:{rateLimit:{max:8,timeWindow:'1 minute'}}},async(request,reply)=>{
    const parsed=loginSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({code:'INVALID_LOGIN',error:'Revisá email y contraseña.'});
    const [rows]=await pool.query<any[]>('SELECT id,name,email,password_hash AS passwordHash,role,brand_scope AS brandScope,active FROM admins WHERE email=? LIMIT 1',[parsed.data.email.toLowerCase()]);const admin=rows[0];
    if(!admin||!admin.active||!(await bcrypt.compare(parsed.data.password,admin.passwordHash)))return reply.code(401).send({code:'INVALID_LOGIN',error:'Email o contraseña incorrectos.'});
    await pool.query('UPDATE admins SET last_login_at=NOW() WHERE id=?',[admin.id]);const token=await reply.jwtSign({id:admin.id,name:admin.name,email:admin.email,role:admin.role,brandScope:admin.brandScope},{expiresIn:'12h'});
    reply.setCookie('ba_admin',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*12});
    await audit({user:admin,ip:request.ip},'auth.login','admin',admin.id,{email:admin.email});
    return {user:{id:admin.id,name:admin.name,email:admin.email,role:admin.role,brandScope:admin.brandScope,permissions:permissionsForRole(admin.role)}};
  });
  app.post('/api/admin/auth/logout',{preHandler:requireAdmin},async(request,reply)=>{await audit(request,'auth.logout','admin',request.user.id);reply.clearCookie('ba_admin',{path:'/'});return{ok:true};});
  app.get('/api/admin/me',{preHandler:requireAdmin},async request=>({user:{...request.user,permissions:permissionsForRole(request.user.role)}}));

  app.get('/api/admin/dashboard',{preHandler:requirePermission('dashboard.view')},async(request,reply)=>{
    const {brand}=request.query as {brand?:string};const effective=effectiveBrand(request,brand||null);if(effective==='__forbidden__')return reply.code(403).send({error:'Sin acceso a esta marca.'});
    const pParams=effective?[effective]:[];const productWhere=effective?'AND p.brand_id=?':'';const itemWhere=effective?'AND oi.brand_id=?':'';
    const [[products]]=await pool.query<any[]>(`SELECT COUNT(*) total FROM products p WHERE p.active=1 ${productWhere}`,pParams);
    const [[low]]=await pool.query<any[]>(`SELECT COUNT(DISTINCT p.id) total FROM products p WHERE p.active=1 ${productWhere} AND ((NOT EXISTS(SELECT 1 FROM product_variants vx WHERE vx.product_id=p.id AND vx.active=1 AND vx.archived=0) AND p.track_stock=1 AND p.stock_qty<=p.low_stock_threshold) OR EXISTS(SELECT 1 FROM product_variants v WHERE v.product_id=p.id AND v.active=1 AND v.archived=0 AND v.track_stock=1 AND v.stock_qty<=v.low_stock_threshold))`,pParams);
    const [[orders]]=await pool.query<any[]>(`SELECT COUNT(DISTINCT o.id) pending FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.status IN ${openStatuses} ${itemWhere}`,pParams);
    const [[sales]]=await pool.query<any[]>(`SELECT COALESCE(SUM(oi.line_total),0) sales30 FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.status IN ${sellStatuses} AND o.created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) ${itemWhere}`,pParams);
    const [recent]=await pool.query<any[]>(`SELECT o.id,o.code,MAX(o.customer_name) customerName,COALESCE(SUM(oi.line_total),0) total,MAX(o.status) status,MAX(o.created_at) createdAt FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE 1=1 ${itemWhere} GROUP BY o.id,o.code ORDER BY createdAt DESC LIMIT 6`,pParams);
    const [top]=await pool.query<any[]>(`SELECT oi.product_name name,COALESCE(oi.variant_value,'') variantValue,SUM(oi.qty) qty,SUM(oi.line_total) total FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.status IN ${sellStatuses} ${itemWhere} GROUP BY oi.product_name,oi.variant_value ORDER BY qty DESC LIMIT 5`,pParams);
    return{products:Number(products.total||0),lowStock:Number(low.total||0),pendingOrders:Number(orders.pending||0),sales30:Number(sales.sales30||0),recentOrders:recent,topProducts:top};
  });

  app.get('/api/admin/analytics',{preHandler:requirePermission('dashboard.view')},async(request,reply)=>{
    const {brand}=request.query as {brand?:string};const effective=effectiveBrand(request,brand||null);if(effective==='__forbidden__')return reply.code(403).send({error:'Sin acceso a esta marca.'});
    const params=effective?[effective]:[];const itemWhere=effective?'AND oi.brand_id=?':'';
    const base=`FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.status IN ${sellStatuses}`;
    const [[today]]=await pool.query<any[]>(`SELECT COUNT(DISTINCT o.id) ordersToday,COALESCE(SUM(oi.line_total),0) salesToday ${base} AND DATE(o.created_at)=CURDATE() ${itemWhere}`,params);
    const [[week]]=await pool.query<any[]>(`SELECT COUNT(DISTINCT o.id) orders7,COALESCE(SUM(oi.line_total),0) sales7 ${base} AND o.created_at>=DATE_SUB(NOW(),INTERVAL 7 DAY) ${itemWhere}`,params);
    const [monthOrders]=await pool.query<any[]>(`SELECT o.id,SUM(oi.line_total) brandTotal ${base} AND o.created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) ${itemWhere} GROUP BY o.id`,params);
    const sales30=monthOrders.reduce((s,r)=>s+Number(r.brandTotal||0),0);const orders30=monthOrders.length;const avgTicket30=orders30?sales30/orders30:0;
    const [series]=await pool.query<any[]>(`SELECT DATE(o.created_at) day,COUNT(DISTINCT o.id) orders,COALESCE(SUM(oi.line_total),0) sales ${base} AND o.created_at>=DATE_SUB(CURDATE(),INTERVAL 13 DAY) ${itemWhere} GROUP BY DATE(o.created_at) ORDER BY day`,params);
    const [pipeline]=await pool.query<any[]>(`SELECT o.status,COUNT(DISTINCT o.id) total FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.status IN ${openStatuses} ${itemWhere} GROUP BY o.status`,params);
    const [brands]=await pool.query<any[]>(`SELECT oi.brand_id brandId,COALESCE(SUM(oi.line_total),0) sales,SUM(oi.qty) qty FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.status IN ${sellStatuses} AND o.created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) ${itemWhere} GROUP BY oi.brand_id`,params);
    const [top]=await pool.query<any[]>(`SELECT oi.product_name name,COALESCE(oi.variant_value,'') variantValue,SUM(oi.qty) qty,SUM(oi.line_total) total,MAX(COALESCE(oi.image_url,p.image_url)) imageUrl FROM orders o JOIN order_items oi ON oi.order_id=o.id LEFT JOIN products p ON p.id=oi.product_id WHERE o.status IN ${sellStatuses} AND o.created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) ${itemWhere} GROUP BY oi.product_name,oi.variant_value ORDER BY qty DESC LIMIT 8`,params);
    const pParams=effective?[effective]:[];const productBrand=effective?'AND p.brand_id=?':'';
    const [lowStock]=await pool.query<any[]>(`SELECT p.id,p.name,p.sku,p.brand_id brandId,p.image_url imageUrl,CASE WHEN EXISTS(SELECT 1 FROM product_variants v0 WHERE v0.product_id=p.id AND v0.active=1 AND v0.archived=0) THEN (SELECT COALESCE(SUM(v1.stock_qty),0) FROM product_variants v1 WHERE v1.product_id=p.id AND v1.active=1 AND v1.archived=0) ELSE p.stock_qty END stockQty FROM products p WHERE p.active=1 ${productBrand} AND ((NOT EXISTS(SELECT 1 FROM product_variants vx WHERE vx.product_id=p.id AND vx.active=1 AND vx.archived=0) AND p.track_stock=1 AND p.stock_qty<=p.low_stock_threshold) OR EXISTS(SELECT 1 FROM product_variants v WHERE v.product_id=p.id AND v.active=1 AND v.archived=0 AND v.track_stock=1 AND v.stock_qty<=v.low_stock_threshold)) ORDER BY stockQty ASC LIMIT 8`,pParams);
    return{ordersToday:Number(today.ordersToday||0),salesToday:Number(today.salesToday||0),orders7:Number(week.orders7||0),sales7:Number(week.sales7||0),orders30,sales30,avgTicket30,series,pipeline,brands,top,lowStock};
  });

  app.get('/api/admin/categories',{preHandler:requirePermission('products.view')},async(request,reply)=>{const{brand}=request.query as {brand?:string};const effective=effectiveBrand(request,brand||null);if(effective==='__forbidden__')return reply.code(403).send({error:'Sin acceso.'});const params:any[]=[];let where='WHERE 1=1';if(effective){where+=' AND brand_id=?';params.push(effective);}const[rows]=await pool.query<any[]>(`SELECT id,brand_id AS brandId,name,slug,image_url AS imageUrl,icon_key AS iconKey,sort_order AS sortOrder,active FROM categories ${where} ORDER BY brand_id,sort_order,name`,params);return rows;});
  app.post('/api/admin/categories',{preHandler:requirePermission('content.manage')},async(request,reply)=>{const parsed=z.object({brandId:z.enum(['amargos','enyerbados']),name:z.string().min(2).max(120),slug:z.string().regex(/^[a-z0-9-]+$/),imageUrl:z.string().max(500).nullable().optional(),iconKey:z.string().max(80).nullable().optional(),sortOrder:z.number().int().default(0),active:z.boolean().default(true)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Categoría inválida.'});if(!canAccessBrand(request,parsed.data.brandId))return reply.code(403).send({error:'Sin acceso.'});const c=parsed.data;const[r]=await pool.query<ResultSetHeader>('INSERT INTO categories (brand_id,name,slug,image_url,icon_key,sort_order,active) VALUES (?,?,?,?,?,?,?)',[c.brandId,c.name,c.slug,c.imageUrl||null,c.iconKey||null,c.sortOrder,c.active?1:0]);await audit(request,'category.create','category',r.insertId,{name:c.name,brand:c.brandId});return reply.code(201).send({id:Number(r.insertId)});});
  app.put('/api/admin/categories/:id',{preHandler:requirePermission('content.manage')},async(request,reply)=>{const id=Number((request.params as any).id);const parsed=z.object({brandId:z.enum(['amargos','enyerbados']),name:z.string().min(2).max(120),slug:z.string().regex(/^[a-z0-9-]+$/),imageUrl:z.string().max(500).nullable().optional(),iconKey:z.string().max(80).nullable().optional(),sortOrder:z.number().int().default(0),active:z.boolean().default(true)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Categoría inválida.'});const[old]=await pool.query<any[]>('SELECT brand_id brandId FROM categories WHERE id=? LIMIT 1',[id]);if(!old.length)return reply.code(404).send({error:'Categoría inexistente.'});if(!canAccessBrand(request,old[0].brandId)||!canAccessBrand(request,parsed.data.brandId))return reply.code(403).send({error:'Sin acceso.'});const c=parsed.data;await pool.query('UPDATE categories SET brand_id=?,name=?,slug=?,image_url=?,icon_key=?,sort_order=?,active=? WHERE id=?',[c.brandId,c.name,c.slug,c.imageUrl||null,c.iconKey||null,c.sortOrder,c.active?1:0,id]);await audit(request,'category.update','category',id,{name:c.name,brand:c.brandId});return{ok:true};});
  app.put('/api/admin/categories/reorder',{preHandler:requirePermission('content.manage')},async(request,reply)=>{const parsed=z.object({items:z.array(z.object({id:z.number().int().positive(),sortOrder:z.number().int().min(0)})).min(1).max(500)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Orden inválido.'});const conn=await pool.getConnection();try{await conn.beginTransaction();for(const item of parsed.data.items){const[rows]=await conn.query<RowDataPacket[]>('SELECT brand_id brandId FROM categories WHERE id=?',[item.id]);if(rows.length&&!canAccessBrand(request,String(rows[0].brandId)))throw new Error('Sin acceso.');await conn.query('UPDATE categories SET sort_order=? WHERE id=?',[item.sortOrder,item.id]);}await conn.commit();await audit(request,'category.reorder','category','bulk',{count:parsed.data.items.length});return{ok:true};}catch(e:any){await conn.rollback();return reply.code(403).send({error:e.message||'No se pudo ordenar.'});}finally{conn.release();}});

  app.get('/api/admin/products',{preHandler:requirePermission('products.view')},async(request,reply)=>{const{brand}=request.query as {brand?:string};const effective=effectiveBrand(request,brand||null);if(effective==='__forbidden__')return reply.code(403).send({error:'Sin acceso.'});const params:any[]=[];let where='WHERE 1=1';if(effective){where+=' AND p.brand_id=?';params.push(effective);}const[rows]=await pool.query<any[]>(`SELECT p.id,p.brand_id AS brandId,p.category_id AS categoryId,p.name,p.slug,p.short_description AS shortDescription,p.description,p.seo_title AS seoTitle,p.seo_description AS seoDescription,p.sku,p.price,p.compare_at_price AS compareAtPrice,p.wholesale_enabled AS wholesaleEnabled,p.wholesale_price AS wholesalePrice,p.wholesale_min_qty AS wholesaleMinQty,p.stock_qty AS stockQty,p.low_stock_threshold AS lowStockThreshold,p.track_stock AS trackStock,p.featured,p.collection_featured AS collectionFeatured,p.sort_order AS sortOrder,p.active,p.image_url AS imageUrl,p.image_zoom AS imageZoom,p.image_position_x AS imagePositionX,p.image_position_y AS imagePositionY,p.image_blend_mode AS imageBlendMode,c.name AS categoryName,c.slug AS categorySlug FROM products p LEFT JOIN categories c ON c.id=p.category_id ${where} ORDER BY p.sort_order,p.id DESC`,params);return enrichProducts(rows);});
  app.get('/api/admin/products/:id',{preHandler:requirePermission('products.view')},async(request,reply)=>{const id=Number((request.params as any).id);const product=await loadAdminProduct(id);if(!product)return reply.code(404).send({error:'Producto inexistente.'});if(!canAccessBrand(request,product.brandId))return reply.code(403).send({error:'Sin acceso.'});return product;});
  app.post('/api/admin/products',{preHandler:requirePermission('products.create')},async(request,reply)=>{const parsed=productSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Producto inválido.',details:parsed.error.flatten()});const p=parsed.data;if(!canAccessBrand(request,p.brandId))return reply.code(403).send({error:'Sin acceso.'});const hasVariants=p.variants.length>0,productStock=hasVariants?0:p.stockQty,productTrack=hasVariants?0:(p.trackStock?1:0);const conn=await pool.getConnection();try{await conn.beginTransaction();const[r]=await conn.query<ResultSetHeader>(`INSERT INTO products (brand_id,category_id,name,slug,short_description,description,seo_title,seo_description,sku,price,compare_at_price,wholesale_enabled,wholesale_price,wholesale_min_qty,stock_qty,low_stock_threshold,track_stock,featured,collection_featured,active,sort_order,image_url,image_zoom,image_position_x,image_position_y,image_blend_mode) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[p.brandId,p.categoryId||null,p.name,p.slug,p.shortDescription||null,p.description||null,p.seoTitle||null,p.seoDescription||null,p.sku,p.price,p.compareAtPrice??null,p.wholesaleEnabled?1:0,p.wholesalePrice??null,p.wholesaleMinQty,productStock,p.lowStockThreshold,productTrack,p.featured?1:0,p.collectionFeatured?1:0,p.active?1:0,p.sortOrder,p.imageUrl||null,p.imageZoom,p.imagePositionX,p.imagePositionY,p.imageBlendMode]);const id=Number(r.insertId);await saveProductChildren(conn,id,p.images,p.variants);await conn.commit();await audit(request,'product.create','product',id,{name:p.name,brand:p.brandId});const product=await loadAdminProduct(id);return reply.code(201).send({id,product});}catch(e:any){await conn.rollback();const duplicate=e?.code==='ER_DUP_ENTRY';return reply.code(400).send({code:duplicate?'DUPLICATE_SKU':'PRODUCT_SAVE_FAILED',error:duplicate?'Ese SKU ya está siendo utilizado.':(e.message||'No se pudo guardar.')});}finally{conn.release();}});
  app.put('/api/admin/products/:id',{preHandler:requirePermission('products.edit')},async(request,reply)=>{const id=Number((request.params as any).id);const parsed=productSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Producto inválido.',details:parsed.error.flatten()});const p=parsed.data;const[original]=await pool.query<any[]>('SELECT brand_id brandId,price FROM products WHERE id=? LIMIT 1',[id]);if(!original.length)return reply.code(404).send({error:'Producto inexistente.'});if(!canAccessBrand(request,original[0].brandId)||!canAccessBrand(request,p.brandId))return reply.code(403).send({error:'Sin acceso.'});const[[variantCount]]=await pool.query<any[]>('SELECT COUNT(*) total FROM product_variants WHERE product_id=? AND archived=0',[id]);if(Number(variantCount.total)>0&&p.variants.length===0&&!p.confirmVariantArchive)return reply.code(409).send({code:'VARIANT_ARCHIVE_CONFIRM_REQUIRED',error:`Este producto tiene ${variantCount.total} variantes activas. Confirmá la conversión para archivarlas.`});const hasVariants=p.variants.length>0,productStock=hasVariants?0:p.stockQty,productTrack=hasVariants?0:(p.trackStock?1:0);const conn=await pool.getConnection();try{await conn.beginTransaction();await conn.query(`UPDATE products SET brand_id=?,category_id=?,name=?,slug=?,short_description=?,description=?,seo_title=?,seo_description=?,sku=?,price=?,compare_at_price=?,wholesale_enabled=?,wholesale_price=?,wholesale_min_qty=?,stock_qty=?,low_stock_threshold=?,track_stock=?,featured=?,collection_featured=?,active=?,sort_order=?,image_url=?,image_zoom=?,image_position_x=?,image_position_y=?,image_blend_mode=? WHERE id=?`,[p.brandId,p.categoryId||null,p.name,p.slug,p.shortDescription||null,p.description||null,p.seoTitle||null,p.seoDescription||null,p.sku,p.price,p.compareAtPrice??null,p.wholesaleEnabled?1:0,p.wholesalePrice??null,p.wholesaleMinQty,productStock,p.lowStockThreshold,productTrack,p.featured?1:0,p.collectionFeatured?1:0,p.active?1:0,p.sortOrder,p.imageUrl||null,p.imageZoom,p.imagePositionX,p.imagePositionY,p.imageBlendMode,id]);await saveProductChildren(conn,id,p.images,p.variants);await conn.commit();await audit(request,'product.update','product',id,{name:p.name,brand:p.brandId,price:{from:Number(original[0].price),to:p.price}});const product=await loadAdminProduct(id);return{ok:true,product};}catch(e:any){await conn.rollback();const duplicate=e?.code==='ER_DUP_ENTRY';return reply.code(400).send({code:duplicate?'DUPLICATE_SKU':'PRODUCT_SAVE_FAILED',error:duplicate?'Ese SKU ya está siendo utilizado.':(e.message||'No se pudo guardar.')});}finally{conn.release();}});
  app.put('/api/admin/products/reorder',{preHandler:requirePermission('products.edit')},async(request,reply)=>{const parsed=z.object({items:z.array(z.object({id:z.number().int().positive(),sortOrder:z.number().int().min(0).max(999999)})).min(1).max(1000)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Orden inválido.'});const conn=await pool.getConnection();try{await conn.beginTransaction();for(const item of parsed.data.items){const[rows]=await conn.query<RowDataPacket[]>('SELECT brand_id brandId FROM products WHERE id=?',[item.id]);if(rows.length&&!canAccessBrand(request,String(rows[0].brandId)))throw new Error('Sin acceso.');await conn.query('UPDATE products SET sort_order=? WHERE id=?',[item.sortOrder,item.id]);}await conn.commit();await audit(request,'product.reorder','product','bulk',{count:parsed.data.items.length});return{ok:true};}catch(e:any){await conn.rollback();return reply.code(403).send({error:e.message||'No se pudo guardar el orden.'});}finally{conn.release();}});

  app.put('/api/admin/wholesale/:id',{preHandler:requirePermission('products.price')},async(request,reply)=>{
    const id=Number((request.params as any).id);
    const parsed=z.object({
      wholesaleEnabled:z.boolean(),
      wholesalePrice:z.number().nonnegative().nullable(),
      wholesaleMinQty:z.number().int().min(1).max(9999),
      variants:z.array(z.object({id:z.number().int().positive(),wholesalePrice:z.number().nonnegative().nullable()})).max(80).default([]),
    }).safeParse(request.body);
    if(!parsed.success)return reply.code(400).send({error:'Configuración mayorista inválida.'});
    const[products]=await pool.query<any[]>('SELECT brand_id brandId,name FROM products WHERE id=? LIMIT 1',[id]);
    if(!products.length)return reply.code(404).send({error:'Producto inexistente.'});
    if(!canAccessBrand(request,products[0].brandId))return reply.code(403).send({error:'Sin acceso.'});
    const conn=await pool.getConnection();
    try{
      await conn.beginTransaction();
      await conn.query('UPDATE products SET wholesale_enabled=?,wholesale_price=?,wholesale_min_qty=? WHERE id=?',[parsed.data.wholesaleEnabled?1:0,parsed.data.wholesalePrice,parsed.data.wholesaleMinQty,id]);
      for(const variant of parsed.data.variants){
        const[result]=await conn.query<ResultSetHeader>('UPDATE product_variants SET wholesale_price=? WHERE id=? AND product_id=? AND archived=0',[variant.wholesalePrice,variant.id,id]);
        if(!result.affectedRows)throw new Error('Una variante mayorista ya no pertenece a este producto. Recargá la pantalla.');
      }
      await conn.commit();
      await audit(request,'product.wholesale','product',id,{enabled:parsed.data.wholesaleEnabled,minQty:parsed.data.wholesaleMinQty,variants:parsed.data.variants.length});
      const product=await loadAdminProduct(id);
      return{ok:true,product};
    }catch(e:any){
      await conn.rollback();
      return reply.code(400).send({error:e.message||'No se pudo guardar el precio mayorista.'});
    }finally{conn.release();}
  });

  app.post('/api/admin/products/:id/stock',{preHandler:requirePermission('inventory.adjust')},async(request,reply)=>{const id=Number((request.params as any).id);const parsed=z.object({delta:z.number().int().refine(n=>n!==0),note:z.string().max(255).optional(),variantId:z.number().int().positive().optional(),movementType:z.enum(['in','out','correction']).optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Ajuste inválido.'});const conn=await pool.getConnection();try{await conn.beginTransaction();const[rows]=await conn.query<RowDataPacket[]>('SELECT brand_id brandId,stock_qty stockQty FROM products WHERE id=? FOR UPDATE',[id]);const product=rows[0];if(!product)throw new Error('Producto no encontrado.');if(!canAccessBrand(request,String(product.brandId)))throw new Error('Sin acceso.');const[vcRows]=await conn.query<RowDataPacket[]>('SELECT COUNT(*) total FROM product_variants WHERE product_id=? AND archived=0',[id]);let next=0,before=0;if(Number(vcRows[0]?.total||0)>0){if(!parsed.data.variantId)throw new Error('Elegí una variante para ajustar el stock.');const[vs]=await conn.query<RowDataPacket[]>('SELECT id,stock_qty stockQty FROM product_variants WHERE id=? AND product_id=? AND archived=0 FOR UPDATE',[parsed.data.variantId,id]);if(!vs.length)throw new Error('Variante no encontrada.');before=Number(vs[0].stockQty);next=before+parsed.data.delta;if(next<0)throw new Error('El stock no puede quedar negativo.');await conn.query('UPDATE product_variants SET stock_qty=? WHERE id=?',[next,parsed.data.variantId]);await conn.query(`INSERT INTO stock_movements (product_id,variant_id,delta,balance_after,reason,note,actor_admin_id) VALUES (?,?,?,?,'manual_adjustment',?,?)`,[id,parsed.data.variantId,parsed.data.delta,next,parsed.data.note||'Ajuste manual',request.user.id]);}else{before=Number(product.stockQty);next=before+parsed.data.delta;if(next<0)throw new Error('El stock no puede quedar negativo.');await conn.query('UPDATE products SET stock_qty=? WHERE id=?',[next,id]);await conn.query(`INSERT INTO stock_movements (product_id,delta,balance_after,reason,note,actor_admin_id) VALUES (?,?,?,'manual_adjustment',?,?)`,[id,parsed.data.delta,next,parsed.data.note||'Ajuste manual',request.user.id]);}await conn.commit();await audit(request,'stock.adjust','product',id,{variantId:parsed.data.variantId||null,before,delta:parsed.data.delta,after:next,note:parsed.data.note||'Ajuste manual'});return{ok:true,stockQty:next};}catch(e:any){await conn.rollback();return reply.code(e.message==='Sin acceso.'?403:400).send({error:e.message||'No se pudo ajustar.'});}finally{conn.release();}});
  app.get('/api/admin/stock-movements',{preHandler:requirePermission('inventory.view')},async(request,reply)=>{const{brand}=request.query as {brand?:string};const effective=effectiveBrand(request,brand||null);if(effective==='__forbidden__')return reply.code(403).send({error:'Sin acceso.'});const params:any[]=[];let where='WHERE 1=1';if(effective){where+=' AND p.brand_id=?';params.push(effective);}const[rows]=await pool.query<any[]>(`SELECT sm.id,sm.variant_id AS variantId,sm.delta,sm.balance_after AS balanceAfter,sm.reason,sm.note,sm.created_at AS createdAt,p.name AS productName,p.sku,p.brand_id AS brandId,v.value AS variantValue,v.sku AS variantSku,o.code AS orderCode,a.name AS actorName FROM stock_movements sm JOIN products p ON p.id=sm.product_id LEFT JOIN product_variants v ON v.id=sm.variant_id LEFT JOIN orders o ON o.id=sm.order_id LEFT JOIN admins a ON a.id=sm.actor_admin_id ${where} ORDER BY sm.created_at DESC LIMIT 500`,params);return rows;});

  app.get('/api/admin/orders',{preHandler:requirePermission('orders.view')},async(request,reply)=>{const{brand,status,search}=request.query as {brand?:string;status?:string;search?:string};const effective=effectiveBrand(request,brand||null);if(effective==='__forbidden__')return reply.code(403).send({error:'Sin acceso.'});const params:any[]=[];const conditions=['1=1'];if(effective){conditions.push('EXISTS (SELECT 1 FROM order_items x WHERE x.order_id=o.id AND x.brand_id=?)');params.push(effective);}if(status){conditions.push('o.status=?');params.push(status);}if(search?.trim()){conditions.push('(o.code LIKE ? OR o.customer_name LIKE ? OR o.customer_phone LIKE ?)');const term=`%${search.trim()}%`;params.push(term,term,term);}const[orders]=await pool.query<any[]>(`SELECT o.id,o.code,o.customer_name AS customerName,o.customer_phone AS customerPhone,o.customer_email AS customerEmail,o.delivery_type AS deliveryType,o.address,o.notes,o.internal_note AS internalNote,o.total,o.status,o.reserved_until AS reservedUntil,o.created_at AS createdAt,o.updated_at AS updatedAt FROM orders o WHERE ${conditions.join(' AND ')} ORDER BY o.created_at DESC LIMIT 500`,params);if(!orders.length)return[];const ids=orders.map(o=>o.id);const ph=ids.map(()=>'?').join(',');const[items]=await pool.query<any[]>(`SELECT order_id AS orderId,brand_id AS brandId,product_name AS productName,sku,variant_name AS variantName,variant_value AS variantValue,variant_sku AS variantSku,image_url AS imageUrl,unit_price AS unitPrice,qty,line_total AS lineTotal FROM order_items WHERE order_id IN (${ph}) ORDER BY id`,ids);const[eventRows]=await pool.query<any[]>(`SELECT order_id AS orderId,from_status AS fromStatus,to_status AS toStatus,note,created_at AS createdAt FROM order_events WHERE order_id IN (${ph}) ORDER BY created_at`,ids);const grouped=new Map<number,any[]>(),events=new Map<number,any[]>();items.forEach(i=>grouped.set(Number(i.orderId),[...(grouped.get(Number(i.orderId))||[]),i]));eventRows.forEach(e=>events.set(Number(e.orderId),[...(events.get(Number(e.orderId))||[]),e]));return orders.map(o=>{const allItems=grouped.get(Number(o.id))||[];const visibleItems=effective?allItems.filter(i=>i.brandId===effective):allItems;const brands=new Set(allItems.map(i=>i.brandId));const visibleTotal=effective?visibleItems.reduce((s,i)=>s+Number(i.lineTotal||0),0):Number(o.total);return{...o,total:visibleTotal,orderTotal:Number(o.total),items:visibleItems,events:events.get(Number(o.id))||[],mixedBrands:brands.size>1,canOperate:!request.user.brandScope||(brands.size===1&&brands.has(request.user.brandScope))};});});
  app.patch('/api/admin/orders/:id/status',{preHandler:requirePermission('orders.update_status')},async(request,reply)=>{const id=Number((request.params as any).id);const parsed=z.object({status:z.enum(['confirmed','preparing','ready','completed','cancelled'])}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Estado inválido.'});if(!(await mayOperateOrder(request,id)))return reply.code(403).send({error:'Este pedido incluye una marca fuera de tu alcance. Necesitás acceso global para cambiar su estado.'});const[orders]=await pool.query<any[]>('SELECT id,status FROM orders WHERE id=? LIMIT 1',[id]);if(!orders.length)return reply.code(404).send({error:'Pedido inexistente.'});const from=String(orders[0].status),to=parsed.data.status;if(to==='cancelled'&&!hasPermission(request,'orders.cancel'))return reply.code(403).send({error:'No tenés permiso para cancelar pedidos.'});if(!canTransitionOrder(from,to))return reply.code(409).send({code:'INVALID_ORDER_TRANSITION',error:`No se puede pasar de ${from} a ${to}.`});if(to==='cancelled'){const restored=await restoreStockForOrder(id,'cancel_restore',request.user.id);if(!restored)return reply.code(409).send({error:'El pedido ya estaba cancelado o vencido.'});await pool.query('INSERT INTO order_events (order_id,from_status,to_status,actor_admin_id) VALUES (?,?,?,?)',[id,from,to,request.user.id]);await audit(request,'order.cancel','order',id,{from,to});return{ok:true};}await pool.query('UPDATE orders SET status=? WHERE id=?',[to,id]);await pool.query('INSERT INTO order_events (order_id,from_status,to_status,actor_admin_id) VALUES (?,?,?,?)',[id,from,to,request.user.id]);await audit(request,'order.status','order',id,{from,to});return{ok:true};});
  app.put('/api/admin/orders/:id/note',{preHandler:requirePermission('orders.update_status')},async(request,reply)=>{const id=Number((request.params as any).id);if(!(await mayOperateOrder(request,id)))return reply.code(403).send({error:'Sin acceso a este pedido.'});const parsed=z.object({note:z.string().max(2000)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Nota inválida.'});await pool.query('UPDATE orders SET internal_note=? WHERE id=?',[parsed.data.note||null,id]);await audit(request,'order.note','order',id,{note:parsed.data.note});return{ok:true};});

  app.get('/api/admin/customers',{preHandler:requirePermission('customers.view')},async(request,reply)=>{const{brand}=request.query as {brand?:string};const effective=effectiveBrand(request,brand||null);if(effective==='__forbidden__')return reply.code(403).send({error:'Sin acceso.'});const params:any[]=[];const itemWhere=effective?'AND oi.brand_id=?':'';if(effective)params.push(effective);const[rows]=await pool.query<any[]>(`SELECT o.customer_phone phone,SUBSTRING_INDEX(GROUP_CONCAT(o.customer_name ORDER BY o.created_at DESC SEPARATOR '||'),'||',1) name,SUBSTRING_INDEX(GROUP_CONCAT(COALESCE(o.customer_email,'') ORDER BY o.created_at DESC SEPARATOR '||'),'||',1) email,COUNT(DISTINCT o.id) orders,COALESCE(SUM(oi.line_total),0) totalSpent,MAX(o.created_at) lastOrder,SUBSTRING_INDEX(GROUP_CONCAT(o.delivery_type ORDER BY o.created_at DESC SEPARATOR ','),',',1) lastDelivery FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.status IN ${sellStatuses} ${itemWhere} GROUP BY o.customer_phone ORDER BY totalSpent DESC,lastOrder DESC LIMIT 1000`,params);return rows.map(r=>({...r,orders:Number(r.orders||0),totalSpent:Number(r.totalSpent||0),avgTicket:Number(r.orders)?Number(r.totalSpent||0)/Number(r.orders):0}));});
  app.get('/api/admin/customers/:phone',{preHandler:requirePermission('customers.view')},async(request,reply)=>{const phone=decodeURIComponent(String((request.params as any).phone||''));const{brand}=request.query as {brand?:string};const effective=effectiveBrand(request,brand||null);if(effective==='__forbidden__')return reply.code(403).send({error:'Sin acceso.'});const params:any[]=[phone];const brandJoin=effective?'AND oi.brand_id=?':'';if(effective)params.push(effective);const[orders]=await pool.query<any[]>(`SELECT o.id,o.code,o.created_at createdAt,o.delivery_type deliveryType,o.status,SUM(oi.line_total) totalSpent FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.customer_phone=? AND o.status IN ${sellStatuses} ${brandJoin} GROUP BY o.id ORDER BY o.created_at DESC LIMIT 30`,params);const[topProducts]=await pool.query<any[]>(`SELECT oi.product_name productName,COALESCE(oi.variant_value,'') variantValue,SUM(oi.qty) qty FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.customer_phone=? AND o.status IN ${sellStatuses} ${brandJoin} GROUP BY oi.product_name,oi.variant_value ORDER BY qty DESC LIMIT 6`,params);const customer=orders.length?{phone,name:'',orders:orders.length,totalSpent:orders.reduce((sum:number,o:any)=>sum+Number(o.totalSpent||0),0),avgTicket:0,lastOrder:orders[0].createdAt,lastDelivery:orders[0].deliveryType}:null;if(customer)customer.avgTicket=customer.totalSpent/customer.orders;return{customer,orders:orders.map(o=>({...o,totalSpent:Number(o.totalSpent||0)})),topProducts:topProducts.map(p=>({...p,qty:Number(p.qty||0)}))};});

  app.get('/api/admin/notifications',{preHandler:requirePermission('dashboard.view')},async(request,reply)=>{const{brand}=request.query as {brand?:string};const scope=effectiveBrand(request,brand||null);if(scope==='__forbidden__')return reply.code(403).send({error:'Sin acceso.'});const pParams=scope?[scope]:[];const productWhere=scope?'AND p.brand_id=?':'';const[[low]]=await pool.query<any[]>(`SELECT COUNT(*) total FROM products p WHERE p.active=1 ${productWhere} AND ((NOT EXISTS(SELECT 1 FROM product_variants vx WHERE vx.product_id=p.id AND vx.active=1 AND vx.archived=0) AND p.track_stock=1 AND p.stock_qty<=p.low_stock_threshold) OR EXISTS(SELECT 1 FROM product_variants v WHERE v.product_id=p.id AND v.active=1 AND v.archived=0 AND v.track_stock=1 AND v.stock_qty<=v.low_stock_threshold))`,pParams);const itemClause=scope?'AND EXISTS(SELECT 1 FROM order_items oi WHERE oi.order_id=o.id AND oi.brand_id=?)':'';const[[pending]]=await pool.query<any[]>(`SELECT COUNT(*) total FROM orders o WHERE o.status='pending' ${itemClause}`,pParams);const[[stale]]=await pool.query<any[]>(`SELECT COUNT(*) total FROM orders o WHERE o.status='pending' AND o.created_at<DATE_SUB(NOW(),INTERVAL 30 MINUTE) ${itemClause}`,pParams);const[[ready]]=await pool.query<any[]>(`SELECT COUNT(*) total FROM orders o WHERE o.status='ready' ${itemClause}`,pParams);const[[noImage]]=await pool.query<any[]>(`SELECT COUNT(*) total FROM products p WHERE p.active=1 AND (p.image_url IS NULL OR p.image_url='') ${productWhere}`,pParams);const items=[{id:'pending',type:'orders',severity:'info',title:`${Number(pending.total)} pedidos pendientes`,count:Number(pending.total),href:'/admin/pedidos?status=pending'},{id:'stale',type:'orders',severity:'warning',title:`${Number(stale.total)} pendientes hace +30 min`,count:Number(stale.total),href:'/admin/pedidos?status=pending'},{id:'ready',type:'orders',severity:'success',title:`${Number(ready.total)} pedidos listos`,count:Number(ready.total),href:'/admin/pedidos?status=ready'},{id:'low',type:'stock',severity:'warning',title:`${Number(low.total)} alertas de stock`,count:Number(low.total),href:'/admin/stock?low=1'},{id:'images',type:'catalog',severity:'info',title:`${Number(noImage.total)} productos sin foto`,count:Number(noImage.total),href:'/admin/productos?missingImage=1'}].filter(x=>x.count>0);return{total:items.reduce((s,x)=>s+x.count,0),items};});

  app.get('/api/admin/search',{preHandler:requireAdmin},async(request,reply)=>{const raw=request.query as any;const q=String(raw.q||'').trim();if(q.length<2)return{products:[],orders:[],customers:[]};const scope=effectiveBrand(request,raw.brand||null);if(scope==='__forbidden__')return reply.code(403).send({error:'Sin acceso.'});const term=`%${q}%`,pParams:any[]=[term,term];let pWhere='';if(scope){pWhere='AND brand_id=?';pParams.push(scope);}const[products]=await pool.query<any[]>(`SELECT id,name,sku,brand_id brandId FROM products WHERE (name LIKE ? OR sku LIKE ?) ${pWhere} ORDER BY name LIMIT 6`,pParams);const oParams:any[]=[term,term,term];let oWhere='';if(scope){oWhere='AND EXISTS(SELECT 1 FROM order_items oi WHERE oi.order_id=o.id AND oi.brand_id=?)';oParams.push(scope);}const[orders]=await pool.query<any[]>(`SELECT o.id,o.code,o.customer_name customerName,o.status FROM orders o WHERE (o.code LIKE ? OR o.customer_name LIKE ? OR o.customer_phone LIKE ?) ${oWhere} ORDER BY o.created_at DESC LIMIT 6`,oParams);const cParams:any[]=[term,term];let cWhere='';if(scope){cWhere='AND EXISTS(SELECT 1 FROM order_items oi WHERE oi.order_id=o.id AND oi.brand_id=?)';cParams.push(scope);}const[cust]=await pool.query<any[]>(`SELECT o.customer_phone phone,SUBSTRING_INDEX(GROUP_CONCAT(o.customer_name ORDER BY o.created_at DESC SEPARATOR '||'),'||',1) name FROM orders o WHERE (o.customer_name LIKE ? OR o.customer_phone LIKE ?) ${cWhere} GROUP BY o.customer_phone LIMIT 6`,cParams);return{products,orders,customers:cust};});

  app.get('/api/admin/settings',{preHandler:requirePermission('settings.manage')},async()=>{const[rows]=await pool.query<any[]>('SELECT setting_key settingKey,setting_value settingValue FROM site_settings ORDER BY setting_key');const settings=Object.fromEntries(rows.map(r=>[r.settingKey,r.settingValue]));const[brands]=await pool.query<any[]>('SELECT id,name,whatsapp,instagram,email FROM brands ORDER BY id');return{settings,brands};});
  app.put('/api/admin/settings',{preHandler:requirePermission('settings.manage')},async(request,reply)=>{const schema=z.object({settings:z.record(z.string(),z.string().max(2000)).default({}),brands:z.array(z.object({id:z.enum(['amargos','enyerbados']),whatsapp:z.string().max(40).nullable().optional(),instagram:z.string().max(120).nullable().optional(),email:z.string().max(190).nullable().optional()})).max(2).default([])});const parsed=schema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Configuración inválida.'});const allowed=new Set(['order_whatsapp','hero_amargos','hero_enyerbados','shipping_note','pickup_note','instagram_feed_url','store_status','announcement','reservation_minutes']);const conn=await pool.getConnection();try{await conn.beginTransaction();for(const[key,value]of Object.entries(parsed.data.settings)){if(allowed.has(key))await conn.query('INSERT INTO site_settings (setting_key,setting_value) VALUES (?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)',[key,value]);}for(const b of parsed.data.brands){if(!canAccessBrand(request,b.id))continue;await conn.query('UPDATE brands SET whatsapp=?,instagram=?,email=? WHERE id=?',[b.whatsapp||null,b.instagram||null,b.email||null,b.id]);}await conn.commit();await audit(request,'settings.update','settings','global',{keys:Object.keys(parsed.data.settings)});return{ok:true};}catch(e:any){await conn.rollback();return reply.code(400).send({error:e.message||'No se pudo guardar.'});}finally{conn.release();}});

  app.get('/api/admin/admins',{preHandler:requirePermission('admins.manage')},async()=>{const[rows]=await pool.query<any[]>('SELECT id,name,email,role,brand_scope brandScope,active,last_login_at lastLoginAt,created_at createdAt FROM admins ORDER BY name');return rows.map(r=>({...r,active:Boolean(r.active)}));});
  app.post('/api/admin/admins',{preHandler:requirePermission('admins.manage')},async(request,reply)=>{const parsed=z.object({name:z.string().min(2).max(120),email:z.string().email(),password:z.string().min(8).max(120),role:z.enum(['superadmin','manager','operator']),brandScope:z.enum(['amargos','enyerbados']).nullable().optional(),active:z.boolean().default(true)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Administrador inválido.'});if(request.user.role!=='superadmin')return reply.code(403).send({error:'Solo un superadmin puede administrar usuarios.'});const hash=await bcrypt.hash(parsed.data.password,12);try{const[r]=await pool.query<ResultSetHeader>('INSERT INTO admins (name,email,password_hash,role,brand_scope,active) VALUES (?,?,?,?,?,?)',[parsed.data.name,parsed.data.email.toLowerCase(),hash,parsed.data.role,parsed.data.brandScope||null,parsed.data.active?1:0]);await audit(request,'admin.create','admin',r.insertId,{email:parsed.data.email,role:parsed.data.role,brandScope:parsed.data.brandScope||null});return reply.code(201).send({id:Number(r.insertId)});}catch(e:any){return reply.code(400).send({error:e.code==='ER_DUP_ENTRY'?'Ese email ya existe.':'No se pudo crear el administrador.'});}});
  app.put('/api/admin/admins/:id',{preHandler:requirePermission('admins.manage')},async(request,reply)=>{if(request.user.role!=='superadmin')return reply.code(403).send({error:'Solo un superadmin puede administrar usuarios.'});const id=Number((request.params as any).id);const parsed=z.object({name:z.string().min(2).max(120),role:z.enum(['superadmin','manager','operator']),brandScope:z.enum(['amargos','enyerbados']).nullable().optional(),active:z.boolean(),password:z.string().min(8).max(120).optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Datos inválidos.'});if(id===request.user.id&&!parsed.data.active)return reply.code(409).send({error:'No podés desactivar tu propio usuario.'});const hash=parsed.data.password?await bcrypt.hash(parsed.data.password,12):null;if(hash)await pool.query('UPDATE admins SET name=?,role=?,brand_scope=?,active=?,password_hash=? WHERE id=?',[parsed.data.name,parsed.data.role,parsed.data.brandScope||null,parsed.data.active?1:0,hash,id]);else await pool.query('UPDATE admins SET name=?,role=?,brand_scope=?,active=? WHERE id=?',[parsed.data.name,parsed.data.role,parsed.data.brandScope||null,parsed.data.active?1:0,id]);await audit(request,'admin.update','admin',id,{role:parsed.data.role,brandScope:parsed.data.brandScope||null,active:parsed.data.active});return{ok:true};});

  app.get('/api/admin/banners',{preHandler:requirePermission('content.manage')},async(request)=>{const params:any[]=[];let where='';if(request.user.brandScope){where='WHERE brand_id IS NULL OR brand_id=?';params.push(request.user.brandScope);}const[rows]=await pool.query<any[]>(`SELECT id,brand_id AS brandId,eyebrow,title,subtitle,image_url AS imageUrl,mobile_image_url AS mobileImageUrl,object_position_desktop AS objectPositionDesktop,object_position_mobile AS objectPositionMobile,cta_label AS ctaLabel,href,sort_order AS sortOrder,active FROM home_banners ${where} ORDER BY sort_order,id`,params);return rows.map(r=>({...r,active:Boolean(r.active)}));});
  app.post('/api/admin/banners',{preHandler:requirePermission('content.manage')},async(request,reply)=>{const parsed=bannerSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Banner inválido.'});const b=parsed.data;if(b.brandId&&!canAccessBrand(request,b.brandId))return reply.code(403).send({error:'Sin acceso.'});const[r]=await pool.query<ResultSetHeader>(`INSERT INTO home_banners (brand_id,eyebrow,title,subtitle,image_url,mobile_image_url,object_position_desktop,object_position_mobile,cta_label,href,sort_order,active) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[b.brandId||null,b.eyebrow||null,b.title,b.subtitle||null,b.imageUrl,b.mobileImageUrl||null,b.objectPositionDesktop,b.objectPositionMobile,b.ctaLabel||null,b.href||null,b.sortOrder,b.active?1:0]);await audit(request,'banner.create','banner',r.insertId,{title:b.title});return{ok:true,id:Number(r.insertId)};});
  app.put('/api/admin/banners/:id',{preHandler:requirePermission('content.manage')},async(request,reply)=>{const id=Number((request.params as any).id);const parsed=bannerSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Banner inválido.'});const[old]=await pool.query<any[]>('SELECT brand_id brandId FROM home_banners WHERE id=?',[id]);if(!old.length)return reply.code(404).send({error:'Banner inexistente.'});const b=parsed.data;if((old[0].brandId&&!canAccessBrand(request,old[0].brandId))||(b.brandId&&!canAccessBrand(request,b.brandId)))return reply.code(403).send({error:'Sin acceso.'});await pool.query(`UPDATE home_banners SET brand_id=?,eyebrow=?,title=?,subtitle=?,image_url=?,mobile_image_url=?,object_position_desktop=?,object_position_mobile=?,cta_label=?,href=?,sort_order=?,active=? WHERE id=?`,[b.brandId||null,b.eyebrow||null,b.title,b.subtitle||null,b.imageUrl,b.mobileImageUrl||null,b.objectPositionDesktop,b.objectPositionMobile,b.ctaLabel||null,b.href||null,b.sortOrder,b.active?1:0,id]);await audit(request,'banner.update','banner',id,{title:b.title});return{ok:true};});
  app.delete('/api/admin/banners/:id',{preHandler:requirePermission('content.manage')},async(request,reply)=>{const id=Number((request.params as any).id);const[rows]=await pool.query<any[]>('SELECT brand_id brandId,title FROM home_banners WHERE id=?',[id]);if(!rows.length)return reply.code(404).send({error:'Banner inexistente.'});if(rows[0].brandId&&!canAccessBrand(request,rows[0].brandId))return reply.code(403).send({error:'Sin acceso.'});await pool.query('DELETE FROM home_banners WHERE id=?',[id]);await audit(request,'banner.delete','banner',id,{title:rows[0].title});return{ok:true};});

  app.get('/api/admin/media',{preHandler:requirePermission('media.manage')},async()=>{const[rows]=await pool.query<any[]>(`SELECT m.id,m.url,m.file_name AS fileName,m.mime_type AS mimeType,m.size_bytes AS sizeBytes,m.width,m.height,m.alt_text AS altText,m.created_at AS createdAt,a.name AS uploadedByName FROM media_assets m LEFT JOIN admins a ON a.id=m.uploaded_by ORDER BY m.created_at DESC LIMIT 1000`);return rows;});
  app.get('/api/admin/media/:id/usage',{preHandler:requirePermission('media.manage')},async(request,reply)=>{const id=Number((request.params as any).id);const[rows]=await pool.query<any[]>('SELECT url FROM media_assets WHERE id=?',[id]);if(!rows.length)return reply.code(404).send({error:'Archivo inexistente.'});const url=rows[0].url;const queries=await Promise.all([pool.query<any[]>('SELECT id,name label FROM products WHERE image_url=? LIMIT 20',[url]),pool.query<any[]>('SELECT pi.id,p.name label FROM product_images pi JOIN products p ON p.id=pi.product_id WHERE pi.image_url=? LIMIT 20',[url]),pool.query<any[]>('SELECT v.id,p.name label,v.value extra FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.image_url=? LIMIT 20',[url]),pool.query<any[]>('SELECT vi.id,p.name label,v.value extra FROM product_variant_images vi JOIN product_variants v ON v.id=vi.variant_id JOIN products p ON p.id=v.product_id WHERE vi.image_url=? LIMIT 20',[url]),pool.query<any[]>('SELECT id,name label FROM categories WHERE image_url=? LIMIT 20',[url]),pool.query<any[]>('SELECT id,title label FROM home_banners WHERE image_url=? OR mobile_image_url=? LIMIT 20',[url,url]),pool.query<any[]>('SELECT id,name label FROM materos_locations WHERE image_url=? LIMIT 20',[url])]);return{products:queries[0][0],productGallery:queries[1][0],variants:queries[2][0],variantGallery:queries[3][0],categories:queries[4][0],banners:queries[5][0],materos:queries[6][0]};});
  app.delete('/api/admin/media/:id',{preHandler:requirePermission('media.manage')},async(request,reply)=>{const id=Number((request.params as any).id);const[rows]=await pool.query<any[]>('SELECT url,file_name fileName FROM media_assets WHERE id=? LIMIT 1',[id]);if(!rows.length)return reply.code(404).send({error:'Archivo inexistente.'});const{url,fileName}=rows[0];const counts=await Promise.all([pool.query<any[]>('SELECT COUNT(*) total FROM products WHERE image_url=?',[url]),pool.query<any[]>('SELECT COUNT(*) total FROM product_images WHERE image_url=?',[url]),pool.query<any[]>('SELECT COUNT(*) total FROM product_variants WHERE image_url=?',[url]),pool.query<any[]>('SELECT COUNT(*) total FROM product_variant_images WHERE image_url=?',[url]),pool.query<any[]>('SELECT COUNT(*) total FROM categories WHERE image_url=?',[url]),pool.query<any[]>('SELECT COUNT(*) total FROM home_banners WHERE image_url=? OR mobile_image_url=?',[url,url]),pool.query<any[]>('SELECT COUNT(*) total FROM materos_locations WHERE image_url=?',[url])]);const used=counts.reduce((s,r)=>s+Number((r[0] as any[])[0]?.total||0),0);if(used>0)return reply.code(409).send({code:'MEDIA_IN_USE',error:'La imagen está en uso. Revisá sus usos antes de eliminarla.'});const conn=await pool.getConnection();try{await conn.beginTransaction();await conn.query('DELETE FROM media_assets WHERE id=?',[id]);if(String(url).startsWith('/uploads/')){const root=getUploadRoot();const diskPath=path.resolve(root,String(fileName));if(diskPath.startsWith(root+path.sep)){try{await fs.unlink(diskPath);}catch(e:any){if(e?.code!=='ENOENT')throw e;}}}await conn.commit();await audit(request,'media.delete','media',id,{url});return{ok:true};}catch(e:any){await conn.rollback();return reply.code(500).send({error:'No se pudo eliminar el archivo de forma segura.'});}finally{conn.release();}});

  app.get('/api/admin/faqs',{preHandler:requirePermission('content.manage')},async()=>{const[rows]=await pool.query<any[]>('SELECT id,question,answer,keywords,category,sort_order AS sortOrder,active FROM faq_items ORDER BY sort_order,id');return rows.map(r=>({...r,active:Boolean(r.active)}));});
  app.post('/api/admin/faqs',{preHandler:requirePermission('content.manage')},async(request,reply)=>{const parsed=z.object({question:z.string().min(2).max(220),answer:z.string().min(2).max(4000),keywords:z.string().max(500).optional().default(''),category:z.string().min(2).max(80).default('General'),sortOrder:z.number().int().min(0).default(0),active:z.boolean().default(true)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'FAQ inválida.'});const f=parsed.data;const[r]=await pool.query<ResultSetHeader>('INSERT INTO faq_items (question,answer,keywords,category,sort_order,active) VALUES (?,?,?,?,?,?)',[f.question,f.answer,f.keywords,f.category,f.sortOrder,f.active?1:0]);await audit(request,'faq.create','faq',r.insertId,{question:f.question});return{ok:true,id:Number(r.insertId)};});
  app.put('/api/admin/faqs/:id',{preHandler:requirePermission('content.manage')},async(request,reply)=>{const id=Number((request.params as any).id);const parsed=z.object({question:z.string().min(2).max(220),answer:z.string().min(2).max(4000),keywords:z.string().max(500).optional().default(''),category:z.string().min(2).max(80).default('General'),sortOrder:z.number().int().min(0).default(0),active:z.boolean().default(true)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'FAQ inválida.'});const f=parsed.data;await pool.query('UPDATE faq_items SET question=?,answer=?,keywords=?,category=?,sort_order=?,active=? WHERE id=?',[f.question,f.answer,f.keywords,f.category,f.sortOrder,f.active?1:0,id]);await audit(request,'faq.update','faq',id,{question:f.question});return{ok:true};});
  app.delete('/api/admin/faqs/:id',{preHandler:requirePermission('content.manage')},async(request)=>{const id=Number((request.params as any).id);await pool.query('DELETE FROM faq_items WHERE id=?',[id]);await audit(request,'faq.delete','faq',id);return{ok:true};});
  app.post('/api/admin/faqs/test',{preHandler:requirePermission('content.manage')},async(request,reply)=>{const parsed=z.object({question:z.string().min(1).max(500)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'Escribí una pregunta.'});const normalize=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ñ]+/g,' ').trim();const q=normalize(parsed.data.question);const[rows]=await pool.query<any[]>('SELECT id,question,answer,keywords,category FROM faq_items WHERE active=1 ORDER BY sort_order,id');let best:any=null,bestScore=0;for(const f of rows){const terms=[...String(f.keywords||'').split(','),f.question].map(normalize).filter(Boolean);let score=0;for(const term of terms){if(q.includes(term)||term.includes(q))score+=term===q?10:4;else for(const token of term.split(/\s+/))if(token.length>2&&q.includes(token))score+=1;}if(score>bestScore){best=f;bestScore=score;}}return bestScore>0?{matched:true,score:bestScore,faq:best,response:best.answer}:{matched:false,score:0,faq:null,response:'No encontré esa respuesta. Si querés, escribinos por WhatsApp.'};});

  app.get('/api/admin/audit',{preHandler:requirePermission('audit.view')},async(request)=>{const{action,entity,admin}=request.query as any;const params:any[]=[];const where:string[]=[];if(action){where.push('l.action=?');params.push(action);}if(entity){where.push('l.entity_type=?');params.push(entity);}if(admin){where.push('l.admin_id=?');params.push(Number(admin));}const[rows]=await pool.query<any[]>(`SELECT l.id,l.action,l.entity_type AS entityType,l.entity_id AS entityId,l.detail_json AS detailJson,l.ip_address AS ipAddress,l.created_at AS createdAt,a.name AS adminName,a.email AS adminEmail FROM audit_logs l LEFT JOIN admins a ON a.id=l.admin_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY l.created_at DESC LIMIT 800`,params);return rows;});
};
