import { FormEvent, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDown, ArrowUp, Image, Pencil, Plus, X } from 'lucide-react';
import { toast } from 'sonner';
import { apiGet, apiSend } from '@/lib/api';
import type { BrandId } from '@/lib/types';
import { AdminCard, AdminEmpty, AdminPage, AdminPageHeader } from '@/components/admin/AdminUI';
import { useAdmin } from '@/components/admin/AdminContext';
import { AdminMediaPicker } from '@/components/admin/AdminMediaPicker';
import { AdminImageActions } from '@/components/admin/AdminImageUpload';

type Category={id:number;brandId:BrandId;name:string;slug:string;imageUrl?:string|null;iconKey?:string|null;sortOrder:number;active:boolean|number};
type Form={id?:number;brandId:BrandId;name:string;slug:string;imageUrl:string;iconKey:string;sortOrder:string;active:boolean};
const slugify=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const icons=['mate','yerba','bombilla','termo','canasta','combo','accesorios'];
export function AdminCategories(){
 const qc=useQueryClient();const{brand,user,can}=useAdmin();const[editing,setEditing]=useState<Form|null>(null);const[picker,setPicker]=useState(false);
 const query=brand==='all'?'':`?brand=${brand}`; const q=useQuery({queryKey:['admin-categories',brand],queryFn:()=>apiGet<Category[]>(`/api/admin/categories${query}`)});
 const list=useMemo(()=>[...(q.data||[])].sort((a,b)=>a.sortOrder-b.sortOrder||a.id-b.id),[q.data]);
 const save=useMutation({mutationFn:(p:any)=>p.id?apiSend(`/api/admin/categories/${p.id}`,'PUT',p):apiSend('/api/admin/categories','POST',p),onSuccess:()=>{toast.success('Categoría guardada.');setEditing(null);qc.invalidateQueries({queryKey:['admin-categories']});qc.invalidateQueries({queryKey:['categories']});},onError:(e:any)=>toast.error(e.message)});
 const reorder=useMutation({mutationFn:(items:Category[])=>apiSend('/api/admin/categories/reorder','PUT',{items:items.map((x,i)=>({id:x.id,sortOrder:(i+1)*10}))}),onSuccess:()=>{toast.success('Orden actualizado.');qc.invalidateQueries({queryKey:['admin-categories']});qc.invalidateQueries({queryKey:['categories']});}});
 function submit(e:FormEvent){e.preventDefault();if(!editing)return;save.mutate({...editing,imageUrl:editing.imageUrl||null,iconKey:editing.iconKey||null,sortOrder:Number(editing.sortOrder||0)});}
 const defaultBrand:BrandId=user.brandScope|| (brand==='enyerbados'?'enyerbados':'amargos');
 const open=(c?:Category)=>setEditing(c?{id:c.id,brandId:c.brandId,name:c.name,slug:c.slug,imageUrl:c.imageUrl||'',iconKey:c.iconKey||'',sortOrder:String(c.sortOrder),active:Boolean(c.active)}:{brandId:defaultBrand,name:'',slug:'',imageUrl:'',iconKey:defaultBrand==='amargos'?'mate':'yerba',sortOrder:String((list.length+1)*10),active:true});
 function move(index:number,dir:-1|1){const next=[...list],target=index+dir;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];reorder.mutate(next);}
 return <AdminPage><AdminPageHeader eyebrow="Catálogo" title="Categorías" description="Orden, imagen, icono y visibilidad dentro de la marca seleccionada." action={can('content.manage')?<button onClick={()=>open()} className="admin-primary-button"><Plus size={15}/> Nueva categoría</button>:undefined}/>
 <AdminCard>{list.length?<div className="grid gap-2">{list.map((c,i)=><div key={c.id} className="grid grid-cols-[58px_1fr_auto] items-center gap-3 rounded-[17px] border border-black/7 bg-[#faf9f5] p-2.5"><div className="grid h-14 w-14 place-items-center overflow-hidden rounded-[14px] bg-white">{c.imageUrl?<img src={c.imageUrl} alt={c.name} className="h-full w-full object-cover"/>:<Image size={18} className="text-black/16"/>}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="truncate text-[11px] font-black">{c.name}</span><span className={`rounded-full px-2 py-1 text-[7px] font-black ${c.active?'bg-emerald-50 text-emerald-700':'bg-black/5 text-black/35'}`}>{c.active?'VISIBLE':'OCULTA'}</span></div><div className="mt-1 text-[8px] text-black/30">/{c.slug} · {c.brandId==='amargos'?'Bien Amargos':'Bien Yerbados'} · orden {c.sortOrder}</div></div><div className="flex items-center gap-1">{can('content.manage')&&<><button disabled={i===0||reorder.isPending} onClick={()=>move(i,-1)} className="admin-icon-button !p-2"><ArrowUp size={13}/></button><button disabled={i===list.length-1||reorder.isPending} onClick={()=>move(i,1)} className="admin-icon-button !p-2"><ArrowDown size={13}/></button><button onClick={()=>open(c)} className="admin-icon-button !p-2"><Pencil size={13}/></button></>}</div></div>)}</div>:<AdminEmpty title="No hay categorías" description="Creá la primera categoría para esta vista."/>}</AdminCard>
 {editing&&<div className="fixed inset-0 z-[160] grid place-items-center bg-[#07110c]/45 p-4 backdrop-blur-[2px]"><form onSubmit={submit} className="w-full max-w-xl rounded-[26px] border border-white/30 bg-[#f7f5ef] p-6 shadow-[0_30px_110px_rgba(0,0,0,.3)]"><div className="flex items-center justify-between"><div><div className="admin-eyebrow">{editing.id?'Editar':'Crear'}</div><h2 className="mt-1 text-2xl font-black">Categoría</h2></div><button type="button" onClick={()=>setEditing(null)} className="admin-icon-button"><X size={16}/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="admin-field-label sm:col-span-2">Marca<select disabled={Boolean(user.brandScope)} className="admin-input" value={editing.brandId} onChange={e=>setEditing({...editing,brandId:e.target.value as BrandId})}><option value="amargos">Bien Amargos</option><option value="enyerbados">Bien Yerbados</option></select></label><label className="admin-field-label">Nombre<input required className="admin-input" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value,slug:editing.id?editing.slug:slugify(e.target.value)})}/></label><label className="admin-field-label">Slug<input required className="admin-input" value={editing.slug} onChange={e=>setEditing({...editing,slug:e.target.value})}/></label><div className="sm:col-span-2"><div className="admin-field-label mb-2">Imagen</div><AdminImageActions compact onUploaded={media=>setEditing(x=>x?{...x,imageUrl:media.url}:x)} onOpenLibrary={()=>setPicker(true)}/><details className="mt-2"><summary className="cursor-pointer text-[8px] font-black uppercase tracking-[.12em] text-black/35">URL avanzada</summary><input className="admin-input mt-2" value={editing.imageUrl} onChange={e=>setEditing({...editing,imageUrl:e.target.value})} placeholder="/uploads/..."/></details></div><label className="admin-field-label">Icono<select className="admin-input" value={editing.iconKey} onChange={e=>setEditing({...editing,iconKey:e.target.value})}>{icons.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="admin-field-label">Orden<input type="number" className="admin-input" value={editing.sortOrder} onChange={e=>setEditing({...editing,sortOrder:e.target.value})}/></label><label className="flex items-center gap-2 text-xs font-black sm:col-span-2"><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/> Visible en catálogo</label></div><button disabled={save.isPending} className="admin-primary-button mt-6 w-full justify-center">{save.isPending?'Guardando…':'Guardar categoría'}</button></form></div>}
 <AdminMediaPicker open={picker} onClose={()=>setPicker(false)} onSelect={url=>{if(editing)setEditing({...editing,imageUrl:url})}}/>
 </AdminPage>;
}
