import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ChevronDown, ChevronUp, GripVertical, ImagePlus, Layers3, PackagePlus, Pencil, Save, Search, Sparkles, X } from 'lucide-react';
import { toast } from 'sonner';
import { Link, useSearchParams } from 'react-router-dom';
import { apiGet, apiSend } from '@/lib/api';
import { money } from '@/lib/format';
import type { Product } from '@/lib/types';
import { AdminCard, AdminEmpty, AdminPage, AdminPageHeader } from '@/components/admin/AdminUI';
import { useAdmin } from '@/components/admin/AdminContext';

export function AdminProducts(){
  const qc=useQueryClient();const[params,setParams]=useSearchParams();const{brand,can}=useAdmin();const[search,setSearch]=useState('');const[orderRows,setOrderRows]=useState<Product[]>([]);
  const orderMode=params.get('order')==='1';const missingImage=params.get('missingImage')==='1';
  const suffix=brand==='all'?'':`?brand=${brand}`;
  const products=useQuery({queryKey:['admin-products',brand],queryFn:()=>apiGet<Product[]>(`/api/admin/products${suffix}`)});
  useEffect(()=>{if(orderMode&&products.data)setOrderRows([...(products.data||[])].sort((a,b)=>Number(a.sortOrder??9999)-Number(b.sortOrder??9999)||a.id-b.id));},[orderMode,products.data]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return(products.data||[]).filter(p=>(!missingImage||!p.imageUrl)&&(!q||`${p.name} ${p.sku} ${p.categoryName||''}`.toLowerCase().includes(q)));},[products.data,search,missingImage]);
  const reorder=useMutation({mutationFn:(items:{id:number;sortOrder:number}[])=>apiSend('/api/admin/products/reorder','PUT',{items}),onSuccess:()=>{toast.success('Orden guardado.');qc.invalidateQueries({queryKey:['admin-products']});setParams({});},onError:(e:any)=>toast.error(e.message)});
  const move=(i:number,dir:-1|1)=>{const j=i+dir;if(j<0||j>=orderRows.length)return;const list=[...orderRows];[list[i],list[j]]=[list[j],list[i]];setOrderRows(list);};
  return <AdminPage>
    <AdminPageHeader eyebrow="Catálogo maestro" title="Productos" description="Gestioná catálogo, variantes, imágenes, visibilidad y orden de tienda." action={<div className="flex flex-wrap gap-2">{can('products.edit')&&<button onClick={()=>setParams({order:'1'})} className="admin-secondary-button"><GripVertical size={15}/> Ordenar tienda</button>}{can('products.create')&&<Link to="/admin/productos/nuevo" className="admin-primary-button"><PackagePlus size={16}/> Nuevo producto</Link>}</div>}/>
    {orderMode&&<AdminCard className="mb-5"><div className="flex items-center justify-between"><div><div className="text-sm font-black">Orden de tienda</div><div className="mt-1 text-[10px] text-black/38">Usá las flechas en desktop o touch. Se guarda todo en una sola operación.</div></div><button onClick={()=>setParams({})} className="grid h-9 w-9 place-items-center rounded-xl bg-black/5"><X size={15}/></button></div><div className="mt-4 grid gap-2">{orderRows.map((p,i)=><div key={p.id} className="flex items-center gap-3 rounded-[16px] border border-black/7 bg-[#faf8f2] px-3 py-2.5"><GripVertical size={15} className="text-black/20"/><span className="grid h-7 w-7 place-items-center rounded-lg bg-black/5 text-[9px] font-black">{i+1}</span><span className="min-w-0 flex-1 truncate text-xs font-black">{p.name}</span><span className="hidden text-[8px] font-bold text-black/30 sm:inline">{p.brandId==='amargos'?'Amargos':'Yerbados'}</span><div className="flex gap-1"><button disabled={i===0} onClick={()=>move(i,-1)} className="admin-mini-icon"><ChevronUp size={13}/></button><button disabled={i===orderRows.length-1} onClick={()=>move(i,1)} className="admin-mini-icon"><ChevronDown size={13}/></button></div></div>)}</div><button onClick={()=>reorder.mutate(orderRows.map((p,i)=>({id:p.id,sortOrder:i+1})))} disabled={reorder.isPending} className="admin-primary-button mt-4"><Save size={15}/>{reorder.isPending?'Guardando…':'Guardar orden'}</button></AdminCard>}
    <AdminCard className="p-3 sm:p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="text-[10px] font-black text-black/38">{brand==='all'?'Todo el negocio':brand==='amargos'?'Bien Amargos':'Bien Yerbados'}{missingImage?' · sin imagen':''}</div><label className="admin-search-field sm:min-w-[320px]"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto, SKU o categoría"/></label></div>
      <div className="mt-4 hidden overflow-x-auto md:block"><table className="admin-table min-w-[980px]"><thead><tr><th>Orden</th><th>Producto</th><th>Marca</th><th>Precio</th><th>Stock</th><th>Variantes</th><th>Home</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><span className="font-mono-ui text-[9px] font-black">{p.sortOrder??9999}</span></td><td><div className="flex items-center gap-3"><div className="h-14 w-14 overflow-hidden rounded-[15px] bg-[#fffdf8] p-1.5">{p.imageUrl?<img src={p.imageUrl} alt="" className="h-full w-full object-contain"/>:<div className="grid h-full place-items-center"><ImagePlus size={16} className="text-black/20"/></div>}</div><div><div className="max-w-[330px] truncate text-[13px] font-black">{p.name}</div><div className="mt-1 font-mono-ui text-[8px] text-black/32">{p.sku} · {p.categoryName||'Sin categoría'}</div></div></div></td><td><span className={`admin-brand-chip ${p.brandId==='amargos'?'admin-brand-chip--green':'admin-brand-chip--yellow'}`}>{p.brandId==='amargos'?'Amargos':'Yerbados'}</span></td><td className="font-black">{money(p.price)}</td><td className="font-black">{p.stockQty}</td><td><span className="inline-flex items-center gap-1.5 font-black"><Layers3 size={13}/>{p.variantCount||0}</span></td><td><div className="flex gap-1">{Boolean(p.featured)&&<Sparkles size={14} className="text-amber-500"/>}{Boolean(p.collectionFeatured)&&<span className="text-[9px] font-black text-[#164b36]">COL</span>}</div></td><td><Link to={`/admin/productos/${p.id}`} className="admin-icon-button"><Pencil size={13}/>{can('products.edit')?'Editar':'Ver'}</Link></td></tr>)}</tbody></table></div>
      <div className="mt-4 grid gap-2 md:hidden">{filtered.map(p=><Link to={`/admin/productos/${p.id}`} key={p.id} className="flex items-center gap-3 rounded-[17px] border border-black/7 bg-[#faf8f2] p-3"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-[14px] bg-white">{p.imageUrl?<img src={p.imageUrl} alt="" className="h-full w-full object-contain p-1"/>:<div className="grid h-full place-items-center"><ImagePlus size={15} className="text-black/20"/></div>}</div><div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{p.name}</div><div className="mt-1 text-[9px] text-black/35">{money(p.price)} · {p.variantCount||0} variantes</div><div className="mt-1 font-mono-ui text-[8px] text-black/30">Stock {p.stockQty} · {p.sku}</div></div><Pencil size={14} className="text-black/30"/></Link>)}</div>
      {!filtered.length&&!products.isLoading&&<AdminEmpty title="No hay productos" description="No encontramos productos con estos filtros."/>}
    </AdminCard>
  </AdminPage>;
}
