import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { Clock3, MessageCircle, Search, ShoppingBag, UserRound, Users, X } from 'lucide-react';
import { apiGet } from '@/lib/api';
import { dateTime, money } from '@/lib/format';
import { AdminCard, AdminEmpty, AdminPage, AdminPageHeader, MetricCard, StatusPill } from '@/components/admin/AdminUI';
import { useAdmin } from '@/components/admin/AdminContext';

type Customer={phone:string;name:string;email?:string|null;orders:number;totalSpent:number;avgTicket?:number;lastOrder:string;lastDelivery?:string|null};
type CustomerDetail={customer:Customer;orders:Array<{id:number;code:string;status:string;deliveryType:string;createdAt:string;totalSpent:number}>;topProducts:Array<{productName:string;variantValue?:string|null;qty:number}>};

export function AdminCustomers(){
  const {brand}=useAdmin(); const [params]=useSearchParams(); const [search,setSearch]=useState(()=>params.get('search')||''); const [selected,setSelected]=useState<Customer|null>(null);
  const suffix=brand==='all'?'':`?brand=${brand}`;
  const q=useQuery({queryKey:['admin-customers',brand],queryFn:()=>apiGet<Customer[]>(`/api/admin/customers${suffix}`)});
  const detail=useQuery({queryKey:['admin-customer-detail',selected?.phone,brand],enabled:Boolean(selected),queryFn:()=>apiGet<CustomerDetail>(`/api/admin/customers/${encodeURIComponent(selected!.phone)}${suffix}`)});
  const filtered=useMemo(()=>{const term=search.toLowerCase().trim();return(q.data||[]).filter(c=>!term||`${c.name} ${c.phone} ${c.email||''}`.toLowerCase().includes(term));},[q.data,search]);
  const totalSpent=(q.data||[]).reduce((s,c)=>s+Number(c.totalSpent||0),0); const recurring=(q.data||[]).filter(c=>Number(c.orders)>1).length; const avg=(q.data||[]).length?totalSpent/(q.data||[]).length:0;
  return <AdminPage>
    <AdminPageHeader eyebrow="Relación con clientes" title="Clientes" description="Historial real de compradores. Los pedidos cancelados o vencidos no inflan las métricas."/>
    <div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Clientes únicos" value={q.data?.length||0} icon={<Users size={17}/>}/><MetricCard label="Recurrentes" value={recurring} detail="2 o más compras válidas" icon={<UserRound size={17}/>} tone="green"/><MetricCard label="Valor promedio" value={money(avg)} detail="facturación válida por cliente"/></div>
    <AdminCard className="mt-5 p-3 sm:p-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-black">Base de clientes</div><div className="mt-1 text-[9px] text-black/35">Click en un cliente para abrir su ficha.</div></div><label className="admin-search-field w-full sm:max-w-[320px]"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nombre, teléfono o email"/></label></div>
      <div className="mt-4 hidden overflow-x-auto md:block"><table className="admin-table min-w-[780px]"><thead><tr><th>Cliente</th><th>Pedidos</th><th>Total válido</th><th>Ticket</th><th>Última compra</th><th></th></tr></thead><tbody>{filtered.map(c=><tr key={c.phone} onClick={()=>setSelected(c)} className="cursor-pointer"><td><div className="font-black">{c.name}</div><div className="mt-1 text-[10px] text-black/38">{c.phone}{c.email?` · ${c.email}`:''}</div></td><td><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${c.orders>1?'bg-emerald-50 text-emerald-700':'bg-black/5 text-black/45'}`}>{c.orders}</span></td><td className="font-black">{money(c.totalSpent)}</td><td className="font-bold">{money(c.avgTicket||0)}</td><td><div className="text-xs font-bold">{dateTime(c.lastOrder)}</div><div className="mt-1 text-[9px] text-black/35">{c.lastDelivery==='shipping'?'Envío':'Retiro'}</div></td><td className="text-right"><MessageCircle size={15} className="ml-auto text-[#0e6c37]"/></td></tr>)}</tbody></table></div>
      <div className="mt-4 grid gap-2 md:hidden">{filtered.map(c=><button key={c.phone} onClick={()=>setSelected(c)} className="rounded-[18px] border border-black/7 bg-[#faf9f5] p-4 text-left"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-black">{c.name}</div><div className="mt-1 text-[9px] text-black/35">{c.phone}</div></div><span className="rounded-full bg-[#164b36]/8 px-2.5 py-1 text-[8px] font-black text-[#164b36]">{c.orders} pedidos</span></div><div className="mt-4 grid grid-cols-2 gap-2 border-t border-black/6 pt-3 text-[9px]"><div><span className="text-black/32">Total</span><div className="mt-1 font-black">{money(c.totalSpent)}</div></div><div><span className="text-black/32">Última compra</span><div className="mt-1 font-bold">{dateTime(c.lastOrder)}</div></div></div></button>)}</div>
      {!filtered.length&&!q.isLoading&&<AdminEmpty title="No encontramos clientes" description="Probá con otra búsqueda."/>}
    </AdminCard>
    {selected&&<div className="fixed inset-0 z-[170] flex justify-end bg-black/30 backdrop-blur-[2px]" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="h-full w-full max-w-[520px] overflow-y-auto border-l border-black/8 bg-[#f4f3ed] p-5 shadow-[-24px_0_80px_rgba(0,0,0,.16)] sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="admin-eyebrow">Cliente</div><h2 className="mt-2 text-3xl font-black tracking-[-.05em]">{selected.name}</h2><div className="mt-2 text-xs font-bold text-black/42">{selected.phone}{selected.email?` · ${selected.email}`:''}</div></div><button onClick={()=>setSelected(null)} className="admin-icon-button"><X size={16}/></button></div>
      <a href={`https://wa.me/${selected.phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer" className="admin-primary-button mt-5 w-full"><MessageCircle size={15}/> Abrir WhatsApp</a>
      <div className="mt-5 grid grid-cols-3 gap-2"><MiniStat label="Pedidos" value={String(selected.orders)}/><MiniStat label="Total" value={money(selected.totalSpent)}/><MiniStat label="Ticket" value={money(selected.avgTicket||0)}/></div>
      <section className="mt-7"><div className="flex items-center gap-2 text-xs font-black"><ShoppingBag size={15}/> Historial reciente</div><div className="mt-3 grid gap-2">{detail.data?.orders?.length?detail.data.orders.map(o=><div key={o.id} className="rounded-[16px] border border-black/7 bg-white p-3"><div className="flex items-center justify-between gap-3"><div><div className="font-mono-ui text-[8px] font-bold text-black/35">{o.code}</div><div className="mt-1 text-[10px] font-black">{money(o.totalSpent)}</div></div><StatusPill status={o.status}/></div><div className="mt-2 flex items-center gap-1 text-[8px] text-black/32"><Clock3 size={11}/>{dateTime(o.createdAt)} · {o.deliveryType==='shipping'?'Envío':'Retiro'}</div></div>):<div className="text-[10px] text-black/35">Sin compras válidas para este filtro.</div>}</div></section>
      <section className="mt-7"><div className="text-xs font-black">Productos frecuentes</div><div className="mt-3 grid gap-2">{detail.data?.topProducts?.length?detail.data.topProducts.map((p,i)=><div key={`${p.productName}-${p.variantValue||''}-${i}`} className="flex items-center justify-between rounded-[14px] border border-black/6 bg-white px-3 py-3 text-[10px]"><span className="font-bold">{p.productName}{p.variantValue?` · ${p.variantValue}`:''}</span><strong>{p.qty} u.</strong></div>):<div className="text-[10px] text-black/35">Todavía no hay frecuencia suficiente.</div>}</div></section>
    </aside></div>}
  </AdminPage>;
}
function MiniStat({label,value}:{label:string;value:string}){return <div className="rounded-[16px] border border-black/7 bg-white p-3"><div className="font-mono-ui text-[7px] uppercase tracking-[.12em] text-black/30">{label}</div><div className="mt-2 text-sm font-black">{value}</div></div>}
