import { FormEvent, useState } from 'react';
import { ArrowRight, LockKeyhole, Mail } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { motion, useReducedMotion } from 'motion/react';
import { toast } from 'sonner';
import { apiSend } from '@/lib/api';

export function AdminLogin(){
  const navigate=useNavigate(); const[loading,setLoading]=useState(false); const reduce=useReducedMotion();
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setLoading(true);try{await apiSend('/api/admin/auth/login','POST',{email:fd.get('email'),password:fd.get('password')});navigate('/admin');}catch(err:any){toast.error(err.message||'No se pudo iniciar sesión.');}finally{setLoading(false);}}
  return <main className="relative min-h-screen overflow-hidden bg-[#0d1711] text-[#172119]">
    <div className="absolute inset-0"><picture className="block h-full w-full"><source media="(max-width: 768px)" srcSet="/brand/hero-beach-mobile.webp"/><img src="/brand/hero-beach.webp" alt="" className="h-full w-full object-cover object-center opacity-22"/></picture><div className="absolute inset-0 bg-[linear-gradient(110deg,rgba(7,20,13,.98)_0%,rgba(7,20,13,.88)_47%,rgba(7,20,13,.57)_100%)]"/></div>
    <div className="relative mx-auto grid min-h-screen max-w-[1500px] items-center gap-8 px-5 py-8 lg:grid-cols-[1.08fr_.92fr] lg:px-10">
      <motion.section initial={reduce?false:{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:reduce?0:.5,ease:[.22,1,.36,1]}} className="hidden min-h-[650px] flex-col justify-between rounded-[34px] border border-white/10 bg-white/[.035] p-10 text-white shadow-[0_34px_100px_rgba(0,0,0,.22)] lg:flex"><div className="flex items-center gap-3"><img src="/brand/bien-amargos-mark.png" alt="Bien Amargos" className="h-14 w-14 rounded-[17px] object-cover"/><div><div className="text-lg font-black tracking-[-.03em]">Bien Amargos</div><div className="mt-1 font-mono-ui text-[7px] uppercase tracking-[.2em] text-white/38">Mar de Ajó · Argentina</div></div></div><div><div className="font-mono-ui text-[8px] uppercase tracking-[.22em] text-white/38">Ronda Admin</div><h1 className="mt-4 max-w-xl text-[clamp(4rem,7vw,7rem)] font-black leading-[.83] tracking-[-.075em]">Todo el negocio, en una sola ronda.</h1><p className="mt-6 max-w-md text-sm font-semibold leading-6 text-white/48">Productos, pedidos, stock, contenido, FAQs y Materos por el Mundo, dentro del mismo sistema.</p></div><div className="font-mono-ui text-[7px] uppercase tracking-[.18em] text-white/28">Bien Amargos · Ronda Admin V8.2</div></motion.section>
      <section className="flex justify-center"><motion.form initial={reduce?false:{opacity:0,y:12,scale:.99}} animate={{opacity:1,y:0,scale:1}} transition={{duration:reduce?0:.45,delay:reduce?0:.08,ease:[.22,1,.36,1]}} onSubmit={submit} className="w-full max-w-[470px] rounded-[30px] border border-white/65 bg-[#f7f3ea]/97 p-6 shadow-[0_34px_96px_rgba(0,0,0,.26)] backdrop-blur-lg sm:p-8"><div className="flex items-center gap-3 lg:hidden"><motion.img initial={reduce?false:{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} src="/brand/bien-amargos-mark.png" alt="Bien Amargos" className="h-12 w-12 rounded-[15px] object-cover"/><div><div className="text-sm font-black">Bien Amargos</div><div className="mt-1 font-mono-ui text-[7px] uppercase tracking-[.18em] text-black/32">Ronda Admin</div></div></div><div className="mt-8 lg:mt-0"><div className="font-mono-ui text-[8px] uppercase tracking-[.19em] text-[#164b36]">Acceso privado</div><h2 className="mt-3 text-4xl font-black tracking-[-.055em] sm:text-5xl">Bienvenido de vuelta.</h2><p className="mt-3 text-xs font-semibold leading-5 text-black/44">Ingresá para administrar la tienda y la comunidad.</p></div><div className="mt-8 grid gap-3"><label className="grid gap-2"><span className="font-mono-ui text-[7px] uppercase tracking-[.16em] text-black/36">Email</span><div className="admin-login-field"><Mail size={16} className="text-black/28"/><input required name="email" type="email" autoComplete="email" placeholder="tu@email.com"/></div></label><label className="grid gap-2"><span className="font-mono-ui text-[7px] uppercase tracking-[.16em] text-black/36">Contraseña</span><div className="admin-login-field"><LockKeyhole size={16} className="text-black/28"/><input required name="password" type="password" autoComplete="current-password" placeholder="••••••••"/></div></label></div><motion.button whileTap={{scale:.985}} disabled={loading} className="mt-5 flex h-13 w-full items-center justify-center gap-2 rounded-[16px] bg-[#164b36] text-sm font-black text-white shadow-[0_14px_30px_rgba(22,75,54,.17)] transition hover:-translate-y-px disabled:translate-y-0 disabled:opacity-50">{loading?'Ingresando…':'Entrar a Ronda Admin'}<ArrowRight size={16}/></motion.button><div className="mt-5 text-center font-mono-ui text-[7px] uppercase tracking-[.15em] text-black/26">Acceso seguro · Bien Amargos</div></motion.form></section>
    </div>
  </main>;
}
