import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, History, Search, SlidersHorizontal, X } from 'lucide-react';
import { toast } from 'sonner';
import { apiGet, apiSend } from '@/lib/api';
import { dateTime } from '@/lib/format';
import { useSearchParams } from 'react-router-dom';
import type { Product } from '@/lib/types';
import { AdminCard, AdminEmpty, AdminPage, AdminPageHeader, MetricCard } from '@/components/admin/AdminUI';
import { useAdmin } from '@/components/admin/AdminContext';

type Movement={id:number;variantId?:number|null;delta:number;balanceAfter:number;reason:string;note?:string;createdAt:string;productName:string;sku:string;brandId:string;variantValue?:string|null;variantSku?:string|null;orderCode?:string;actorName?:string};
type Row={p:Product;v:NonNullable<Product['variants']>[number]|null;key:string;stock:number;low:number};

type AdjustState={row:Row;kind:'in'|'out'|'correction';qty:string;note:string}|null;
export function AdminStock(){
  const qc=useQueryClient();const{brand,can}=useAdmin();const[params]=useSearchParams();const[search,setSearch]=useState('');const[onlyLow,setOnlyLow]=useState(()=>params.get('low')==='1');const[adjusting,setAdjusting]=useState<AdjustState>(null);const suffix=brand==='all'?'':`?brand=${brand}`;
  const products=useQuery({queryKey:['admin-products-stock',brand],queryFn:()=>apiGet<Product[]>(`/api/admin/products${suffix}`)});const movements=useQuery({queryKey:['stock-movements',brand],queryFn:()=>apiGet<Movement[]>(`/api/admin/stock-movements${suffix}`)});
  const rows=useMemo<Row[]>(()=>{const all=(products.data||[]).flatMap(p=>p.variants?.length?p.variants.filter(v=>Boolean(v.active)).map(v=>({p,v,key:`${p.id}:${v.id}`,stock:Number(v.stockQty),low:Number(v.lowStockThreshold??p.lowStockThreshold)})):[{p,v:null,key:`${p.id}:0`,stock:Number(p.stockQty),low:Number(p.lowStockThreshold)}]);const term=search.toLowerCase().trim();return all.filter(r=>(!term||`${r.p.name} ${r.v?.value||''} ${r.v?.sku||r.p.sku}`.toLowerCase().includes(term))&&(!onlyLow||r.stock<=r.low));},[products.data,search,onlyLow]);
  const lowCount=rows.filter(r=>r.stock<=r.low).length,total=rows.reduce((s,r)=>s+r.stock,0),out=rows.filter(r=>r.stock===0).length;
  const adjust=useMutation({mutationFn:({id,variantId,delta,note,movementType}:{id:number;variantId?:number;delta:number;note:string;movementType:string})=>apiSend(`/api/admin/products/${id}/stock`,'POST',{variantId,delta,note,movementType}),onSuccess:()=>{toast.success('Stock actualizado.');setAdjusting(null);['admin-products','admin-products-stock','stock-movements','admin-dashboard','admin-analytics','catalog','featured-products','admin-notifications'].forEach(k=>qc.invalidateQueries({queryKey:[k]}));},onError:(e:any)=>toast.error(e.message)});
  function confirmAdjust(){if(!adjusting)return;const qty=Math.max(0,Number(adjusting.qty||0));if(!qty)return toast.error('Ingresá una cantidad válida.');let delta=qty;if(adjusting.kind==='out')delta=-qty;if(adjusting.kind==='correction')delta=qty-adjusting.row.stock;if(delta===0)return toast.error('El stock resultante ya es el actual.');adjust.mutate({id:adjusting.row.p.id,variantId:adjusting.row.v?.id,delta,note:adjusting.note||({in:'Ingreso manual',out:'Salida manual',correction:'Corrección de inventario'} as const)[adjusting.kind],movementType:adjusting.kind});}
  return <AdminPage>
    <AdminPageHeader eyebrow="Inventario" title="Stock" description="Ajustes seguros, alertas y trazabilidad completa."/>
    <div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Unidades disponibles" value={total}/><MetricCard label="Stock bajo" value={lowCount} icon={<AlertTriangle size={17}/>} tone={lowCount?'yellow':'neutral'}/><MetricCard label="Sin stock" value={out} tone={out?'dark':'neutral'}/></div>
    <div className="mt-5 grid gap-5 2xl:grid-cols-[.92fr_1.08fr]">
      <AdminCard className="p-3 sm:p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="rounded-full bg-black/[.04] px-3 py-2 text-[9px] font-black text-black/42">{brand==='all'?'Todo el negocio':brand==='amargos'?'Bien Amargos':'Bien Yerbados'}</div><button onClick={()=>setOnlyLow(v=>!v)} className={`rounded-[14px] px-3 py-2 text-[10px] font-black ${onlyLow?'bg-red-50 text-red-600':'bg-black/[.035] text-black/40'}`}>Solo alertas</button></div><label className="admin-search-field mt-3"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto, variante o SKU"/></label><div className="mt-3 max-h-[680px] overflow-y-auto pr-1"><div className="grid gap-2">{rows.map(row=><div key={row.key} className={`rounded-[18px] border p-3 ${row.stock<=row.low?'border-red-100 bg-red-50/45':'border-black/6 bg-black/[.018]'}`}><div className="flex items-center gap-3"><div className="h-12 w-12 shrink-0 overflow-hidden rounded-[14px] bg-[#eee9dc]">{(row.v?.imageUrl||row.p.imageUrl)&&<img src={row.v?.imageUrl||row.p.imageUrl||''} alt="" className="h-full w-full object-contain p-1"/>}</div><div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{row.p.name}{row.v?.value?` · ${row.v.value}`:''}</div><div className="mt-1 font-mono-ui text-[8px] text-black/32">{row.v?.sku||row.p.sku}</div></div><div className={`text-right ${row.stock<=row.low?'text-red-600':''}`}><div className="text-xl font-black">{row.stock}</div><div className="text-[8px] font-bold">mín. {row.low}</div></div></div>{can('inventory.adjust')&&<button onClick={()=>setAdjusting({row,kind:'in',qty:'1',note:''})} className="admin-secondary-button mt-3 w-full justify-center"><SlidersHorizontal size={14}/> Ajustar stock</button>}</div>)}{!rows.length&&!products.isLoading&&<AdminEmpty title="Sin resultados"/>}</div></div></AdminCard>
      <AdminCard className="overflow-hidden p-0"><div className="flex items-center gap-3 border-b border-black/7 p-5"><span className="grid h-10 w-10 place-items-center rounded-[14px] bg-black/5"><History size={16}/></span><div><div className="text-sm font-black">Historial de movimientos</div><div className="mt-1 text-[9px] text-black/35">Quién movió stock, cuánto y por qué.</div></div></div><div className="max-h-[760px] overflow-y-auto divide-y divide-black/[.055]">{(movements.data||[]).map(m=><div key={m.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="text-xs font-black">{m.productName}{m.variantValue?` · ${m.variantValue}`:''}</div><div className="mt-1 text-[9px] text-black/35">{m.actorName||'Sistema'} · {m.note||m.reason}{m.orderCode?` · ${m.orderCode}`:''}</div><div className="mt-1 font-mono-ui text-[8px] text-black/25">{dateTime(m.createdAt)}</div></div><div className="text-right"><div className={`text-sm font-black ${m.delta>0?'text-emerald-700':'text-red-600'}`}>{m.delta>0?'+':''}{m.delta}</div><div className="mt-1 text-[8px] text-black/35">saldo {m.balanceAfter}</div></div></div>)}{!movements.data?.length&&!movements.isLoading&&<AdminEmpty title="Sin movimientos"/>}</div></AdminCard>
    </div>
    {adjusting&&<div className="fixed inset-0 z-[240] grid place-items-center bg-black/45 p-4 backdrop-blur-sm" onMouseDown={()=>setAdjusting(null)}><div className="w-full max-w-md rounded-[26px] bg-[#f6f3eb] p-5 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><div className="admin-eyebrow">Ajustar stock</div><div className="mt-1 text-lg font-black">{adjusting.row.p.name}{adjusting.row.v?.value?` · ${adjusting.row.v.value}`:''}</div><div className="mt-1 text-[10px] text-black/40">Stock actual: <b>{adjusting.row.stock}</b></div></div><button onClick={()=>setAdjusting(null)} className="grid h-9 w-9 place-items-center rounded-xl bg-black/5"><X size={15}/></button></div><div className="mt-5 grid gap-4"><label className="admin-field-label">Movimiento<select className="admin-input" value={adjusting.kind} onChange={e=>setAdjusting({...adjusting,kind:e.target.value as any,qty:e.target.value==='correction'?String(adjusting.row.stock):'1'})}><option value="in">Ingreso</option><option value="out">Salida</option><option value="correction">Corrección a valor exacto</option></select></label><label className="admin-field-label">{adjusting.kind==='correction'?'Stock resultante':'Cantidad'}<input className="admin-input" type="number" min="0" value={adjusting.qty} onChange={e=>setAdjusting({...adjusting,qty:e.target.value})}/></label><label className="admin-field-label">Motivo / nota<input className="admin-input" value={adjusting.note} onChange={e=>setAdjusting({...adjusting,note:e.target.value})} placeholder="Compra proveedor, merma, conteo…"/></label><div className="rounded-[14px] bg-black/[.035] p-3 text-[10px] font-bold text-black/45">Resultado: <b className="text-black">{adjusting.kind==='in'?adjusting.row.stock+Number(adjusting.qty||0):adjusting.kind==='out'?adjusting.row.stock-Number(adjusting.qty||0):Number(adjusting.qty||0)}</b></div><button onClick={confirmAdjust} disabled={adjust.isPending} className="admin-primary-button justify-center">{adjust.isPending?'Guardando…':'Confirmar ajuste'}</button></div></div></div>}
  </AdminPage>;
}
