import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Eye, EyeOff, ImagePlus, Pencil, Plus, Save, Trash2, X } from 'lucide-react';
import { toast } from 'sonner';
import { apiGet, apiSend } from '@/lib/api';
import { AdminCard, AdminEmpty, AdminPage, AdminPageHeader } from '@/components/admin/AdminUI';
import { AdminMediaPicker } from '@/components/admin/AdminMediaPicker';
import { AdminImageActions } from '@/components/admin/AdminImageUpload';
import type { BrandId } from '@/lib/types';

type Banner={id:number;brandId?:BrandId|null;eyebrow?:string|null;title:string;subtitle?:string|null;imageUrl:string;mobileImageUrl?:string|null;objectPositionDesktop?:string;objectPositionMobile?:string;ctaLabel?:string|null;href?:string|null;sortOrder:number;active:boolean|number};
type Media={id:number;url:string;fileName:string};
type Draft={brandId:''|BrandId;eyebrow:string;title:string;subtitle:string;imageUrl:string;mobileImageUrl:string;objectPositionDesktop:string;objectPositionMobile:string;ctaLabel:string;href:string;sortOrder:number;active:boolean};
const empty:Draft={brandId:'',eyebrow:'',title:'',subtitle:'',imageUrl:'',mobileImageUrl:'',objectPositionDesktop:'50% 50%',objectPositionMobile:'50% 50%',ctaLabel:'',href:'',sortOrder:10,active:true};

export function AdminBanners(){
 const qc=useQueryClient();const[editing,setEditing]=useState<number|null>(null);const[draft,setDraft]=useState<Draft>(empty);const[picker,setPicker]=useState<'desktop'|'mobile'|null>(null);
 const q=useQuery({queryKey:['admin-banners'],queryFn:()=>apiGet<Banner[]>('/api/admin/banners')});const media=useQuery({queryKey:['admin-media'],queryFn:()=>apiGet<Media[]>('/api/admin/media')});
 const ordered=[...(q.data||[])].sort((a,b)=>a.sortOrder-b.sortOrder||a.id-b.id);
 const save=useMutation({mutationFn:()=>editing?apiSend(`/api/admin/banners/${editing}`,'PUT',draft):apiSend('/api/admin/banners','POST',draft),onSuccess:()=>{toast.success('Banner guardado.');setEditing(null);setDraft(empty);qc.invalidateQueries({queryKey:['admin-banners']});qc.invalidateQueries({queryKey:['home-banners']});},onError:(e:any)=>toast.error(e.message)});
 const del=useMutation({mutationFn:(id:number)=>apiSend(`/api/admin/banners/${id}`,'DELETE'),onSuccess:()=>{toast.success('Banner eliminado.');qc.invalidateQueries({queryKey:['admin-banners']});qc.invalidateQueries({queryKey:['home-banners']});},onError:(e:any)=>toast.error(e.message)});
 const edit=(b:Banner)=>{setEditing(b.id);setDraft({brandId:b.brandId||'',eyebrow:b.eyebrow||'',title:b.title,subtitle:b.subtitle||'',imageUrl:b.imageUrl,mobileImageUrl:b.mobileImageUrl||'',objectPositionDesktop:b.objectPositionDesktop||'50% 50%',objectPositionMobile:b.objectPositionMobile||'50% 50%',ctaLabel:b.ctaLabel||'',href:b.href||'',sortOrder:b.sortOrder,active:Boolean(b.active)});window.scrollTo({top:0,behavior:'smooth'});};
 const submit=(e:FormEvent)=>{e.preventDefault();if(!draft.imageUrl.trim())return toast.error('Elegí una imagen desktop.');save.mutate();};
 return <AdminPage>
  <AdminPageHeader eyebrow="Storefront" title="Carrusel" description="Banners de campaña con arte específico para desktop y mobile." action={<button onClick={()=>{setEditing(null);setDraft(empty);}} className="admin-primary-button"><Plus size={15}/> Nuevo banner</button>}/>
  <AdminCard className="mb-5 !bg-[#153f2f] text-white"><div className="grid gap-3 sm:grid-cols-2"><div><div className="text-xs font-black">Desktop recomendado</div><div className="mt-1 text-2xl font-black">1920 × 800 px</div><div className="mt-1 text-[9px] text-white/48">WebP · ratio ~2.4:1 · sujeto dentro del 60% central.</div></div><div><div className="text-xs font-black">Mobile recomendado</div><div className="mt-1 text-2xl font-black">1080 × 1350 px</div><div className="mt-1 text-[9px] text-white/48">WebP · ratio 4:5. Si no cargás mobile se usa el banner desktop.</div></div></div></AdminCard>
  <div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]">
   <AdminCard><form onSubmit={submit} className="grid gap-4"><div className="flex items-center justify-between"><div><div className="text-sm font-black">{editing?'Editar banner':'Nuevo banner'}</div><div className="mt-1 text-[10px] text-black/40">Poco texto, foto protagonista.</div></div>{editing&&<button type="button" onClick={()=>{setEditing(null);setDraft(empty);}} className="grid h-9 w-9 place-items-center rounded-xl bg-black/5"><X size={15}/></button>}</div>
    <div className="grid gap-3 sm:grid-cols-2"><div><div className="mb-2 text-[9px] font-black text-black/40">DESKTOP</div><div className="aspect-[2.4/1] overflow-hidden rounded-[18px] bg-[#ece8dd]">{draft.imageUrl?<img src={draft.imageUrl} alt="" className="h-full w-full object-cover" style={{objectPosition:draft.objectPositionDesktop}}/>:<div className="grid h-full place-items-center text-black/20"><ImagePlus/></div>}</div></div><div><div className="mb-2 text-[9px] font-black text-black/40">MOBILE</div><div className="mx-auto aspect-[4/5] max-h-[190px] overflow-hidden rounded-[18px] bg-[#ece8dd]">{(draft.mobileImageUrl||draft.imageUrl)?<img src={draft.mobileImageUrl||draft.imageUrl} alt="" className="h-full w-full object-cover" style={{objectPosition:draft.objectPositionMobile}}/>:<div className="grid h-full place-items-center text-black/20"><ImagePlus/></div>}</div></div></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="admin-field-label">Marca<select className="admin-input" value={draft.brandId} onChange={e=>setDraft(x=>({...x,brandId:e.target.value as Draft['brandId']}))}><option value="">Ambas marcas</option><option value="amargos">Bien Amargos</option><option value="enyerbados">Bien Yerbados</option></select></label><label className="admin-field-label">Orden<input className="admin-input" type="number" min="0" value={draft.sortOrder} onChange={e=>setDraft(x=>({...x,sortOrder:Number(e.target.value)}))}/></label></div>
    <label className="admin-field-label">Eyebrow<input className="admin-input" value={draft.eyebrow} onChange={e=>setDraft(x=>({...x,eyebrow:e.target.value}))}/></label><label className="admin-field-label">Título<input className="admin-input" value={draft.title} onChange={e=>setDraft(x=>({...x,title:e.target.value}))} required/></label><label className="admin-field-label">Subtítulo<input className="admin-input" value={draft.subtitle} onChange={e=>setDraft(x=>({...x,subtitle:e.target.value}))}/></label>
    <div className="grid gap-3 sm:grid-cols-2"><label className="admin-field-label">CTA<input className="admin-input" value={draft.ctaLabel} onChange={e=>setDraft(x=>({...x,ctaLabel:e.target.value}))}/></label><label className="admin-field-label">Link<input className="admin-input" value={draft.href} onChange={e=>setDraft(x=>({...x,href:e.target.value}))}/></label></div>
    <div className="grid gap-3 sm:grid-cols-2"><div><div className="admin-field-label mb-2">Imagen desktop</div><AdminImageActions compact uploadLabel="Subir desktop" onUploaded={media=>setDraft(x=>({...x,imageUrl:media.url}))} onOpenLibrary={()=>setPicker('desktop')}/><details className="mt-2"><summary className="cursor-pointer text-[8px] font-black uppercase tracking-[.12em] text-black/35">URL avanzada</summary><input className="admin-input mt-2" value={draft.imageUrl} onChange={e=>setDraft(x=>({...x,imageUrl:e.target.value}))}/></details></div><div><div className="admin-field-label mb-2">Imagen mobile opcional</div><AdminImageActions compact uploadLabel="Subir mobile" onUploaded={media=>setDraft(x=>({...x,mobileImageUrl:media.url}))} onOpenLibrary={()=>setPicker('mobile')}/><details className="mt-2"><summary className="cursor-pointer text-[8px] font-black uppercase tracking-[.12em] text-black/35">URL avanzada</summary><input className="admin-input mt-2" value={draft.mobileImageUrl} onChange={e=>setDraft(x=>({...x,mobileImageUrl:e.target.value}))}/></details></div></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="admin-field-label">Posición desktop<input className="admin-input" value={draft.objectPositionDesktop} onChange={e=>setDraft(x=>({...x,objectPositionDesktop:e.target.value}))} placeholder="50% 50%"/></label><label className="admin-field-label">Posición mobile<input className="admin-input" value={draft.objectPositionMobile} onChange={e=>setDraft(x=>({...x,objectPositionMobile:e.target.value}))} placeholder="50% 50%"/></label></div>
    <div className="flex flex-wrap gap-2"><button type="button" onClick={()=>setDraft(x=>({...x,active:!x.active}))} className="admin-secondary-button">{draft.active?<><Eye size={14}/> Visible</>:<><EyeOff size={14}/> Oculto</>}</button></div>
    {!!media.data?.length&&<div><div className="mb-2 text-[9px] font-black uppercase tracking-[.16em] text-black/35">Biblioteca reciente</div><div className="grid grid-cols-4 gap-2">{media.data.slice(0,8).map(m=><button key={m.id} type="button" onClick={()=>setDraft(x=>({...x,imageUrl:m.url}))} className="aspect-square overflow-hidden rounded-[14px] border border-black/7 bg-white p-1"><img src={m.url} alt={m.fileName} className="h-full w-full rounded-[10px] object-contain"/></button>)}</div></div>}
    <button disabled={save.isPending} className="admin-primary-button justify-center"><Save size={15}/>{save.isPending?'Guardando…':editing?'Guardar cambios':'Crear banner'}</button>
   </form></AdminCard>
   <AdminCard>{ordered.length?<div className="grid gap-3">{ordered.map(b=><article key={b.id} className="grid gap-3 rounded-[22px] border border-black/7 bg-[#faf8f2] p-3 sm:grid-cols-[180px_1fr_auto] sm:items-center"><div className="aspect-[2.4/1] overflow-hidden rounded-[15px] bg-[#ece8dd]"><img src={b.imageUrl} alt={b.title} className="h-full w-full object-cover" style={{objectPosition:b.objectPositionDesktop||'50% 50%'}}/></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-black/5 px-2 py-1 text-[8px] font-black">{b.brandId==='amargos'?'Amargos':b.brandId==='enyerbados'?'Yerbados':'Ambas'}</span><span className="text-[8px] text-black/30">Orden {b.sortOrder}</span></div><div className="mt-2 truncate text-sm font-black">{b.title}</div><div className="mt-1 text-[9px] text-black/35">{b.mobileImageUrl?'Desktop + mobile':'Solo desktop'}</div></div><div className="flex gap-2 sm:flex-col"><button onClick={()=>edit(b)} className="grid h-9 w-9 place-items-center rounded-xl bg-white"><Pencil size={14}/></button><button onClick={()=>confirm('¿Eliminar este banner?')&&del.mutate(b.id)} className="grid h-9 w-9 place-items-center rounded-xl bg-red-50 text-red-500"><Trash2 size={14}/></button></div></article>)}</div>:<AdminEmpty title="Todavía no hay banners" description="Creá el primero y aparecerá en la home automáticamente."/>}</AdminCard>
  </div>
 <AdminMediaPicker open={Boolean(picker)} onClose={()=>setPicker(null)} title={picker==='mobile'?'Elegir imagen mobile':'Elegir imagen desktop'} onSelect={url=>setDraft(x=>picker==='mobile'?{...x,mobileImageUrl:url}:{...x,imageUrl:url})}/>
 </AdminPage>;
}
