import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, ArrowUpRight, Boxes, CircleDollarSign, PackageCheck, ShoppingBag, Sparkles, TrendingUp, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { apiGet } from '@/lib/api';
import { dateTime, money } from '@/lib/format';
import { AdminCard, AdminCardHeader, AdminEmpty, AdminPage, AdminPageHeader, MetricCard, StatusPill } from '@/components/admin/AdminUI';
import { useAdmin } from '@/components/admin/AdminContext';
import { CountUp } from '@/components/motion/CountUp';

type Dash={products:number;lowStock:number;pendingOrders:number;sales30:number;recentOrders:{id:number;code:string;customerName:string;total:number;status:string;createdAt:string}[];topProducts:{name:string;variantValue?:string;qty:number;total:number}[]};
type Analytics={ordersToday:number;salesToday:number;orders7:number;sales7:number;orders30:number;sales30:number;avgTicket30:number;series:{day:string;orders:number;sales:number}[];pipeline:{status:string;total:number}[];brands:{brandId:string;sales:number;qty:number}[];top:{name:string;variantValue?:string;qty:number;total:number;imageUrl?:string|null}[];lowStock:{id:number;name:string;sku:string;brandId:string;imageUrl?:string|null;stockQty:number}[]};
type Notifications={total:number;items:{id:string;title:string;count:number;href:string;severity:string}[]};
const pipelineOrder=['pending','confirmed','preparing','ready'];
const pipelineLabels:Record<string,string>={pending:'Pendientes',confirmed:'Confirmados',preparing:'Preparando',ready:'Listos'};

export function AdminDashboard(){
  const{brand,can}=useAdmin();const suffix=brand==='all'?'':`?brand=${brand}`;
  const q=useQuery({queryKey:['admin-dashboard',brand],queryFn:()=>apiGet<Dash>(`/api/admin/dashboard${suffix}`)});
  const a=useQuery({queryKey:['admin-analytics',brand],queryFn:()=>apiGet<Analytics>(`/api/admin/analytics${suffix}`)});
  const n=useQuery({queryKey:['admin-notifications',brand],queryFn:()=>apiGet<Notifications>(`/api/admin/notifications${suffix}`)});
  const label=brand==='amargos'?'Bien Amargos':brand==='enyerbados'?'Bien Yerbados':'Todo el negocio';
  const maxSales=Math.max(1,...(a.data?.series||[]).map(x=>Number(x.sales||0)));const totalBrandSales=(a.data?.brands||[]).reduce((s,x)=>s+Number(x.sales||0),0)||1;
  return <AdminPage>
    <AdminPageHeader eyebrow="Centro de control" title={label} description="Lo importante para operar el negocio ahora mismo." action={can('products.create')?<Link to="/admin/productos/nuevo" className="admin-primary-button"><Sparkles size={15}/> Nuevo producto</Link>:undefined}/>
    <div className="admin-metrics-grid">
      <MetricCard label="Ventas de hoy" value={a.isLoading?'…':<><span className="text-[.72em]">$</span> <CountUp value={Math.round(a.data?.salesToday||0)} duration={520}/></>} detail={`${a.data?.ordersToday||0} pedidos`} icon={<CircleDollarSign size={17}/>} tone="green"/>
      <MetricCard label="Pedidos de hoy" value={a.isLoading?'…':<CountUp value={a.data?.ordersToday||0} duration={460}/>} detail={`${q.data?.pendingOrders||0} abiertos`} icon={<ShoppingBag size={17}/>}/>
      <MetricCard label="Ticket promedio · 30d" value={a.isLoading?'…':<><span className="text-[.72em]">$</span> <CountUp value={Math.round(a.data?.avgTicket30||0)} duration={560}/></>} detail={`${a.data?.orders30||0} pedidos`} icon={<TrendingUp size={17}/>} tone="yellow"/>
      <MetricCard label="Stock bajo" value={q.isLoading?'…':<CountUp value={q.data?.lowStock||0} duration={420}/>} detail="Variantes o productos" icon={<AlertTriangle size={17}/>} tone={Number(q.data?.lowStock||0)>0?'dark':'neutral'}/>
    </div>
    <div className="mt-5 grid gap-5 2xl:grid-cols-[1.35fr_.65fr]">
      <AdminCard><AdminCardHeader title="Ritmo de ventas" description="Facturación de los últimos 14 días." action={<span className="rounded-full bg-black/[.045] px-3 py-2 text-[10px] font-black text-black/45">30d · {money(a.data?.sales30||0)}</span>}/><div className="mt-7 flex h-[230px] items-end gap-2 sm:gap-3">{(a.data?.series||[]).length?(a.data?.series||[]).map(d=>{const pct=Math.max(5,Math.round((Number(d.sales)/maxSales)*100));const date=new Date(`${String(d.day).slice(0,10)}T12:00:00`);return <div key={String(d.day)} className="group flex min-w-0 flex-1 flex-col items-center gap-2"><div className="relative flex h-[185px] w-full items-end"><div className="w-full rounded-t-[10px] bg-gradient-to-t from-[#164b36] to-[#2f7457] transition group-hover:brightness-110" style={{height:`${pct}%`}}><div className="pointer-events-none absolute -top-9 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded-lg bg-[#111713] px-2 py-1 text-[9px] font-bold text-white shadow-lg group-hover:block">{money(Number(d.sales))}</div></div></div><span className="text-[8px] font-bold text-black/30">{date.toLocaleDateString('es-AR',{day:'2-digit'})}</span></div>}):<div className="grid h-full w-full place-items-center text-sm text-black/30">Todavía no hay ventas en este período.</div>}</div></AdminCard>
      <AdminCard className="bg-[#111713] text-white"><AdminCardHeader title="Pedidos ahora" description="Qué está en curso."/><div className="mt-5 grid gap-2">{pipelineOrder.map((status,i)=>{const value=Number((a.data?.pipeline||[]).find(x=>x.status===status)?.total||0);return <Link key={status} to={`/admin/pedidos?status=${status}`} className="flex items-center justify-between rounded-[16px] bg-white/[.055] px-4 py-3 transition hover:bg-white/[.09]"><span className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white/[.07] font-mono-ui text-[8px] text-white/35">0{i+1}</span><span className="text-xs font-bold">{pipelineLabels[status]}</span></span><b className={status==='ready'?'text-[#efc51d]':''}>{value}</b></Link>})}</div></AdminCard>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
      <AdminCard><AdminCardHeader title="Necesita atención" description="Alertas reales y accionables."/><div className="mt-4 grid gap-2">{n.data?.items.length?n.data.items.map(item=><Link key={item.id} to={item.href} className={`admin-attention-item admin-attention-item--${item.severity}`}><span>{item.title}</span><strong>{item.count}</strong></Link>):<div className="rounded-[18px] bg-emerald-50 p-4 text-xs font-bold text-emerald-700"><PackageCheck size={17} className="mb-2"/>No hay alertas pendientes.</div>}</div></AdminCard>
      <AdminCard><AdminCardHeader title="Pedidos recientes" description="Últimos movimientos." action={<Link to="/admin/pedidos" className="text-[10px] font-black text-black/40">Ver todos →</Link>}/><div className="mt-3 divide-y divide-black/[.055]">{(q.data?.recentOrders||[]).map(o=><Link to={`/admin/pedidos?search=${encodeURIComponent(o.code)}`} key={o.id} className="grid grid-cols-[1fr_auto] items-center gap-4 py-3.5"><div className="min-w-0"><div className="flex items-center gap-2"><span className="truncate text-[13px] font-black">{o.customerName}</span><StatusPill status={o.status}/></div><div className="mt-1 text-[9px] text-black/35">{o.code} · {dateTime(o.createdAt)}</div></div><div className="text-sm font-black">{money(o.total)}</div></Link>)}{!q.data?.recentOrders?.length&&!q.isLoading&&<AdminEmpty title="Todavía no hay pedidos"/>}</div></AdminCard>
    </div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2">
      <AdminCard><AdminCardHeader title="Productos que empujan la ronda" description="Unidades vendidas en los últimos 30 días."/><div className="mt-5 grid gap-3">{(a.data?.top||q.data?.topProducts||[]).slice(0,6).map((p:any,i:number)=><div key={`${p.name}-${p.variantValue||''}`} className="flex items-center gap-3"><div className="font-mono-ui text-[9px] text-black/25">0{i+1}</div>{p.imageUrl&&<img src={p.imageUrl} alt="" className="h-10 w-10 rounded-xl bg-[#eee9dc] object-contain p-1"/>}<div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{p.name}{p.variantValue?` · ${p.variantValue}`:''}</div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-black/5"><div className="h-full rounded-full bg-[#164b36]" style={{width:`${Math.max(8,Math.min(100,(Number(p.qty||0)/Math.max(1,Number((a.data?.top||[])[0]?.qty||p.qty||1)))*100))}%`}}/></div></div><div className="text-right"><div className="text-xs font-black">{p.qty} u.</div><div className="mt-1 text-[9px] text-black/35">{money(Number(p.total||0))}</div></div></div>)}</div></AdminCard>
      <AdminCard><AdminCardHeader title="Mix de marcas" description="Participación en ventas de los últimos 30 días."/><div className="mt-6 grid gap-5">{(['amargos','enyerbados'] as const).map(b=>{const row=(a.data?.brands||[]).find(x=>x.brandId===b);const sales=Number(row?.sales||0);const pct=Math.round((sales/totalBrandSales)*100);return <div key={b}><div className="flex items-end justify-between"><div><div className="text-sm font-black">{b==='amargos'?'Bien Amargos':'Bien Yerbados'}</div><div className="mt-1 text-[10px] text-black/35">{row?.qty||0} unidades</div></div><div className="text-right"><div className="text-xl font-black">{pct}%</div><div className="text-[9px] text-black/35">{money(sales)}</div></div></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-black/5"><div className={`h-full rounded-full ${b==='amargos'?'bg-[#164b36]':'bg-[#d7c6ad]'}`} style={{width:`${pct}%`}}/></div></div>})}</div><Link to="/admin/clientes" className="mt-7 flex items-center justify-between rounded-[18px] bg-black/[.03] px-4 py-3 text-xs font-black"><span className="flex items-center gap-2"><Users size={15}/> Ver clientes</span><ArrowUpRight size={14}/></Link></AdminCard>
    </div>
  </AdminPage>;
}
