import { ChangeEvent, useMemo, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, Clipboard, FileImage, Image as ImageIcon, PanelsTopLeft, Search, Trash2, Upload, X } from 'lucide-react';
import { toast } from 'sonner';
import { apiGet, apiSend } from '@/lib/api';
import { AdminCard, AdminEmpty, AdminPage, AdminPageHeader } from '@/components/admin/AdminUI';

type Media={id:number;url:string;fileName:string;mimeType?:string|null;sizeBytes:number;width?:number|null;height?:number|null;altText?:string|null;createdAt:string;uploadedByName?:string|null};
type UsageGroup={id:number;label:string;extra?:string|null};
type Usage={products:UsageGroup[];productGallery?:UsageGroup[];variants:UsageGroup[];variantGallery?:UsageGroup[];categories?:UsageGroup[];banners:UsageGroup[];materos:UsageGroup[]};

export function AdminMedia(){
 const qc=useQueryClient(); const input=useRef<HTMLInputElement>(null); const[search,setSearch]=useState(''); const[selected,setSelected]=useState<Media|null>(null);
 const q=useQuery({queryKey:['admin-media'],queryFn:()=>apiGet<Media[]>('/api/admin/media')});
 const usage=useQuery({queryKey:['admin-media-usage',selected?.id],enabled:Boolean(selected),queryFn:()=>apiGet<Usage>(`/api/admin/media/${selected!.id}/usage`)});
 const del=useMutation({mutationFn:(id:number)=>apiSend(`/api/admin/media/${id}`,'DELETE'),onSuccess:()=>{toast.success('Archivo eliminado de la biblioteca y del servidor.');setSelected(null);qc.invalidateQueries({queryKey:['admin-media']});},onError:(e:any)=>toast.error(e.message)});
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const fd=new FormData();fd.append('file',file);try{const r=await fetch('/api/admin/upload',{method:'POST',body:fd,credentials:'include'});const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudo subir.');toast.success(data.width&&data.height?`Imagen ${data.width}×${data.height} cargada.`:'Imagen cargada.');qc.invalidateQueries({queryKey:['admin-media']});}catch(err:any){toast.error(err.message||'No se pudo subir.');}finally{e.target.value='';}}
 const filtered=useMemo(()=>{const t=search.trim().toLowerCase();return(q.data||[]).filter(m=>!t||`${m.fileName} ${m.mimeType||''}`.toLowerCase().includes(t));},[q.data,search]);
 const usageCount=usage.data?Object.values(usage.data).reduce((s,g)=>s+(Array.isArray(g)?g.length:0),0):0;
 return <AdminPage><AdminPageHeader eyebrow="Activos" title="Multimedia" description="Biblioteca central. Una imagen, sus usos y su eliminación segura desde un solo lugar." action={<><input ref={input} onChange={upload} type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="hidden"/><button onClick={()=>input.current?.click()} className="admin-primary-button"><Upload size={15}/> Subir imagen</button></>}/>
 <div className="mb-4 grid gap-3 lg:grid-cols-2"><AdminCard><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[#173f30] text-white"><ImageIcon size={17}/></div><div><div className="text-sm font-black">Fotos de producto</div><div className="mt-1 text-xs font-semibold leading-relaxed text-black/45">Ideal: <b>1600 × 1600 px</b> · mínimo 1200 × 1200 · WebP/JPG · 150–450 KB. El producto debería ocupar <b>80–90%</b> del lienzo.</div></div></div></AdminCard><AdminCard><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[#d7c6ad] text-[#17311f]"><PanelsTopLeft size={17}/></div><div><div className="text-sm font-black">Carrusel</div><div className="mt-1 text-xs font-semibold leading-relaxed text-black/45">Desktop: <b>1920 × 800 px</b>. Mobile: <b>1080 × 1350 px</b>. Recomendado WebP.</div></div></div></AdminCard></div>
 <AdminCard><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-black">Biblioteca</div><div className="mt-1 text-[9px] text-black/34">{filtered.length} archivos visibles</div></div><label className="admin-search-field w-full sm:max-w-[300px]"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar archivo"/></label></div>{filtered.length?<div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5">{filtered.map(m=>{const tooSmall=Boolean(m.width&&m.height&&(m.width<1200||m.height<1200));return <button type="button" key={m.id} onClick={()=>setSelected(m)} className="group overflow-hidden rounded-[20px] border border-black/7 bg-[#faf8f2] text-left transition hover:-translate-y-0.5 hover:shadow-[0_14px_32px_rgba(0,0,0,.06)]"><div className="aspect-square bg-white p-3"><img src={m.url} alt={m.altText||m.fileName} className="h-full w-full object-contain" loading="lazy"/></div><div className="p-3"><div className="truncate text-[10px] font-black">{m.fileName}</div><div className="mt-1 text-[8px] text-black/35">{m.width&&m.height?`${m.width}×${m.height} · `:''}{Math.max(1,Math.round(m.sizeBytes/1024))} KB</div>{tooSmall&&<div className="mt-2 flex gap-1.5 rounded-xl bg-amber-50 px-2 py-1.5 text-[8px] font-bold leading-tight text-amber-800"><AlertTriangle size={11} className="shrink-0"/>Pequeña para producto.</div>}</div></button>})}</div>:<AdminEmpty title="Todavía no hay imágenes" description="Subí una foto y quedará disponible para productos, categorías y contenido editorial."/>}</AdminCard>
 {selected&&<div className="fixed inset-0 z-[170] flex justify-end bg-black/30 backdrop-blur-[2px]" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><aside className="h-full w-full max-w-[560px] overflow-y-auto border-l border-black/8 bg-[#f5f3ed] p-5 shadow-[-24px_0_80px_rgba(0,0,0,.16)] sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="admin-eyebrow">Archivo</div><h2 className="mt-2 break-all text-2xl font-black tracking-[-.04em]">{selected.fileName}</h2></div><button onClick={()=>setSelected(null)} className="admin-icon-button"><X size={16}/></button></div><div className="mt-5 aspect-square overflow-hidden rounded-[24px] border border-black/7 bg-white p-5"><img src={selected.url} alt={selected.altText||selected.fileName} className="h-full w-full object-contain"/></div><div className="mt-4 grid grid-cols-3 gap-2"><Info label="Dimensiones" value={selected.width&&selected.height?`${selected.width}×${selected.height}`:'—'}/><Info label="Formato" value={(selected.mimeType||'—').replace('image/','').toUpperCase()}/><Info label="Peso" value={`${Math.max(1,Math.round(selected.sizeBytes/1024))} KB`}/></div><div className="mt-4 flex gap-2"><button onClick={()=>navigator.clipboard.writeText(selected.url).then(()=>toast.success('URL copiada.'))} className="admin-secondary-button flex-1"><Clipboard size={14}/> Copiar URL</button><button disabled={usageCount>0||del.isPending} onClick={()=>confirm('¿Eliminar este archivo del servidor? Esta acción no se puede deshacer.')&&del.mutate(selected.id)} className="admin-secondary-button text-red-600 disabled:cursor-not-allowed disabled:opacity-40"><Trash2 size={14}/> Eliminar</button></div><section className="mt-7"><div className="flex items-center gap-2 text-xs font-black"><FileImage size={15}/> Utilizada en</div>{usage.isLoading?<div className="mt-3 text-[10px] text-black/35">Revisando referencias…</div>:usageCount?<div className="mt-3 grid gap-2">{usage.data&&Object.entries(usage.data).flatMap(([group,items])=>(items||[]).map((x:any)=><div key={`${group}-${x.id}-${x.extra||''}`} className="rounded-[14px] border border-black/6 bg-white px-3 py-3"><div className="font-mono-ui text-[7px] uppercase tracking-[.12em] text-black/28">{usageLabel(group)}</div><div className="mt-1 text-[10px] font-black">{x.label}{x.extra?` · ${x.extra}`:''}</div></div>))}</div>:<div className="mt-3 rounded-[16px] border border-emerald-900/8 bg-emerald-50/60 p-4 text-[10px] font-bold text-emerald-800">No tiene referencias. Se puede eliminar de forma segura.</div>}</section></aside></div>}
 </AdminPage>
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-[15px] border border-black/7 bg-white p-3"><div className="font-mono-ui text-[7px] uppercase tracking-[.12em] text-black/28">{label}</div><div className="mt-2 text-[10px] font-black">{value}</div></div>}
function usageLabel(k:string){return({products:'Producto',productGallery:'Galería de producto',variants:'Variante',variantGallery:'Galería de variante',categories:'Categoría',banners:'Carrusel',materos:'Materos por el mundo'} as Record<string,string>)[k]||k}
