import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, ExternalLink, KeyRound, Plus, Save, ShieldCheck, UserCog, X } from 'lucide-react';
import { toast } from 'sonner';
import { apiGet, apiSend } from '@/lib/api';
import { AdminCard, AdminCardHeader, AdminPage, AdminPageHeader } from '@/components/admin/AdminUI';
import { useAdmin } from '@/components/admin/AdminContext';

type Data={settings:Record<string,string>;brands:{id:'amargos'|'enyerbados';name:string;whatsapp?:string|null;instagram?:string|null;email?:string|null}[]};
type FormState={orderWhatsapp:string;reservationMinutes:string;announcement:string;storeStatus:string;heroAmargos:string;heroYerbados:string;shippingNote:string;pickupNote:string;amargosWhatsapp:string;amargosInstagram:string;amargosEmail:string;enyerbadosWhatsapp:string;enyerbadosInstagram:string;enyerbadosEmail:string};
type AdminAccount={id:number;name:string;email:string;role:'superadmin'|'manager'|'operator';brandScope:'amargos'|'enyerbados'|null;active:boolean;lastLoginAt?:string|null;createdAt:string};
type AdminDraft={id?:number;name:string;email:string;password:string;role:'superadmin'|'manager'|'operator';brandScope:''|'amargos'|'enyerbados';active:boolean};
const empty:FormState={orderWhatsapp:'5492257410476',reservationMinutes:'30',announcement:'',storeStatus:'open',heroAmargos:'Tu próxima ronda empieza acá.',heroYerbados:'Yerba con presencia.',shippingNote:'',pickupNote:'',amargosWhatsapp:'',amargosInstagram:'',amargosEmail:'',enyerbadosWhatsapp:'',enyerbadosInstagram:'',enyerbadosEmail:''};
const emptyAdmin:AdminDraft={name:'',email:'',password:'',role:'operator',brandScope:'',active:true};

export function AdminSettings(){
  const qc=useQueryClient(); const{can,user}=useAdmin(); const q=useQuery({queryKey:['admin-settings'],queryFn:()=>apiGet<Data>('/api/admin/settings')}); const[form,setForm]=useState<FormState>(empty); const[initial,setInitial]=useState(''); const[section,setSection]=useState<'general'|'amargos'|'yerbados'|'users'>('general'); const[adminDraft,setAdminDraft]=useState<AdminDraft|null>(null);
  const admins=useQuery({queryKey:['admin-admins'],enabled:can('admins.manage'),queryFn:()=>apiGet<AdminAccount[]>('/api/admin/admins')});
  useEffect(()=>{if(!q.data)return;const a=q.data.brands.find(b=>b.id==='amargos');const e=q.data.brands.find(b=>b.id==='enyerbados');const next={orderWhatsapp:q.data.settings.order_whatsapp||'',reservationMinutes:q.data.settings.reservation_minutes||'30',announcement:q.data.settings.announcement||'',storeStatus:q.data.settings.store_status||'open',heroAmargos:q.data.settings.hero_amargos||'Ronda con carácter.',heroYerbados:q.data.settings.hero_enyerbados||'Yerba con presencia.',shippingNote:q.data.settings.shipping_note||'',pickupNote:q.data.settings.pickup_note||'',amargosWhatsapp:a?.whatsapp||'',amargosInstagram:a?.instagram||'',amargosEmail:a?.email||'',enyerbadosWhatsapp:e?.whatsapp||'',enyerbadosInstagram:e?.instagram||'',enyerbadosEmail:e?.email||''};setForm(next);setInitial(JSON.stringify(next));},[q.data]);
  const dirty=initial&&JSON.stringify(form)!==initial;
  useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
  const save=useMutation({mutationFn:()=>apiSend('/api/admin/settings','PUT',{settings:{order_whatsapp:form.orderWhatsapp,reservation_minutes:form.reservationMinutes,announcement:form.announcement,store_status:form.storeStatus,hero_amargos:form.heroAmargos,hero_enyerbados:form.heroYerbados,shipping_note:form.shippingNote,pickup_note:form.pickupNote},brands:[{id:'amargos',whatsapp:form.amargosWhatsapp,instagram:form.amargosInstagram,email:form.amargosEmail},{id:'enyerbados',whatsapp:form.enyerbadosWhatsapp,instagram:form.enyerbadosInstagram,email:form.enyerbadosEmail}]}),onSuccess:()=>{toast.success('Configuración guardada.');setInitial(JSON.stringify(form));qc.invalidateQueries({queryKey:['admin-settings']});qc.invalidateQueries({queryKey:['store-settings']});},onError:(e:any)=>toast.error(e.message)});
  const saveAdmin=useMutation({mutationFn:(d:AdminDraft)=>d.id?apiSend(`/api/admin/admins/${d.id}`,'PUT',{name:d.name,role:d.role,brandScope:d.brandScope||null,active:d.active,...(d.password?{password:d.password}:{})}):apiSend('/api/admin/admins','POST',{name:d.name,email:d.email,password:d.password,role:d.role,brandScope:d.brandScope||null,active:d.active}),onSuccess:()=>{toast.success('Administrador guardado.');setAdminDraft(null);qc.invalidateQueries({queryKey:['admin-admins']});},onError:(e:any)=>toast.error(e.message)});
  const patch=(k:keyof FormState,v:string)=>setForm(x=>({...x,[k]:v})); const submit=(e:FormEvent)=>{e.preventDefault();save.mutate();};
  const sections=useMemo(()=>[{id:'general',label:'General'},{id:'amargos',label:'Bien Amargos'},{id:'yerbados',label:'Bien Yerbados'},...(can('admins.manage')?[{id:'users',label:'Usuarios y permisos'}]:[])],[can]);
  return <AdminPage><form onSubmit={submit}><AdminPageHeader eyebrow="Sistema" title="Configuración" description="Operación, marcas y accesos en una pantalla ordenada." action={<div className="flex items-center gap-2">{dirty&&<span className="rounded-full bg-amber-100 px-3 py-2 text-[8px] font-black text-amber-800">● Cambios sin guardar</span>}{section!=='users'&&<button disabled={save.isPending||!dirty} className="admin-primary-button"><Save size={15}/>{save.isPending?'Guardando…':'Guardar cambios'}</button>}</div>}/>
  <div className="grid gap-5 lg:grid-cols-[220px_1fr]"><AdminCard className="h-fit !p-2 lg:sticky lg:top-[94px]"><nav className="grid gap-1">{sections.map((s:any)=><button type="button" key={s.id} onClick={()=>setSection(s.id)} className={`rounded-[13px] px-3 py-3 text-left text-[10px] font-black transition ${section===s.id?'bg-[#111713] text-white':'text-black/45 hover:bg-black/4 hover:text-black'}`}>{s.label}</button>)}</nav></AdminCard><div>
  {section==='general'&&<div className="grid gap-5 xl:grid-cols-[1fr_.85fr]"><div className="grid gap-5"><AdminCard><AdminCardHeader title="Operación" description="WhatsApp, reserva y estado de la tienda."/><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="admin-field-label sm:col-span-2">WhatsApp de pedidos<input className="admin-input" value={form.orderWhatsapp} onChange={e=>patch('orderWhatsapp',e.target.value)} placeholder="5492257…"/><span>Formato internacional, solo números.</span></label><label className="admin-field-label">Reserva de stock<input className="admin-input" type="number" min="5" value={form.reservationMinutes} onChange={e=>patch('reservationMinutes',e.target.value)}/><span>Minutos para pedidos pendientes.</span></label><label className="admin-field-label">Estado<select className="admin-input" value={form.storeStatus} onChange={e=>patch('storeStatus',e.target.value)}><option value="open">Abierta</option><option value="closed">Cerrada</option></select></label><label className="admin-field-label sm:col-span-2">Aviso superior<input className="admin-input" value={form.announcement} onChange={e=>patch('announcement',e.target.value)} placeholder="Envíos a todo el país · Retiro coordinado"/></label></div></AdminCard><AdminCard><AdminCardHeader title="Entrega" description="Textos reales que se muestran al cliente."/><div className="mt-5 grid gap-4"><label className="admin-field-label">Texto de envíos<textarea rows={3} className="admin-input resize-none" value={form.shippingNote} onChange={e=>patch('shippingNote',e.target.value)}/></label><label className="admin-field-label">Texto de retiro<textarea rows={3} className="admin-input resize-none" value={form.pickupNote} onChange={e=>patch('pickupNote',e.target.value)}/></label></div></AdminCard></div><AdminCard className="bg-[#111713] text-white"><div className="flex items-center gap-2 text-sm font-black"><ShieldCheck size={17}/> Configuración operativa</div><div className="mt-4 grid gap-2 text-xs leading-relaxed text-white/50"><Row>WhatsApp usado para pedidos nuevos.</Row><Row>Tiempo de reserva de stock.</Row><Row>Estado y avisos de la tienda.</Row></div><a href="/" target="_blank" className="mt-5 flex items-center justify-between border-t border-white/10 pt-4 text-[10px] font-black text-white/45 hover:text-white"><span>Ver tienda publicada</span><ExternalLink size={14}/></a></AdminCard></div>}
  {section==='amargos'&&<BrandSettings title="Bien Amargos" hero={form.heroAmargos} whatsapp={form.amargosWhatsapp} instagram={form.amargosInstagram} email={form.amargosEmail} onHero={v=>patch('heroAmargos',v)} onChange={(k,v)=>patch((`amargos${k}`) as keyof FormState,v)}/>} 
  {section==='yerbados'&&<BrandSettings title="Bien Yerbados" hero={form.heroYerbados} whatsapp={form.enyerbadosWhatsapp} instagram={form.enyerbadosInstagram} email={form.enyerbadosEmail} onHero={v=>patch('heroYerbados',v)} onChange={(k,v)=>patch((`enyerbados${k}`) as keyof FormState,v)}/>} 
  {section==='users'&&can('admins.manage')&&<AdminCard><AdminCardHeader title="Usuarios y permisos" description="Roles fijos y alcance por marca. Las restricciones también se validan en backend." action={<button type="button" onClick={()=>setAdminDraft(emptyAdmin)} className="admin-primary-button"><Plus size={14}/> Nuevo usuario</button>}/><div className="mt-5 grid gap-2">{admins.data?.map(a=><button type="button" key={a.id} onClick={()=>setAdminDraft({id:a.id,name:a.name,email:a.email,password:'',role:a.role,brandScope:a.brandScope||'',active:a.active})} className="grid grid-cols-[1fr_auto] items-center gap-3 rounded-[16px] border border-black/7 bg-[#faf9f5] p-4 text-left"><div><div className="text-[11px] font-black">{a.name}</div><div className="mt-1 text-[8px] text-black/32">{a.email} · {a.role} · {a.brandScope||'todas las marcas'}</div></div><span className={`rounded-full px-2.5 py-1 text-[8px] font-black ${a.active?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-600'}`}>{a.active?'ACTIVO':'INACTIVO'}</span></button>)}</div></AdminCard>}
  </div></div></form>
  {adminDraft&&<div className="fixed inset-0 z-[170] grid place-items-center bg-black/35 p-4 backdrop-blur-[2px]"><form onSubmit={e=>{e.preventDefault();if(!adminDraft.id&&!adminDraft.password)return toast.error('La contraseña inicial es obligatoria.');saveAdmin.mutate(adminDraft)}} className="w-full max-w-lg rounded-[26px] border border-white/30 bg-[#f6f4ee] p-6 shadow-[0_28px_100px_rgba(0,0,0,.28)]"><div className="flex items-center justify-between"><div><div className="admin-eyebrow">Acceso</div><h2 className="mt-1 text-2xl font-black">{adminDraft.id?'Editar usuario':'Nuevo usuario'}</h2></div><button type="button" onClick={()=>setAdminDraft(null)} className="admin-icon-button"><X size={15}/></button></div><div className="mt-5 grid gap-4"><label className="admin-field-label">Nombre<input className="admin-input" required value={adminDraft.name} onChange={e=>setAdminDraft({...adminDraft,name:e.target.value})}/></label><label className="admin-field-label">Email<input disabled={Boolean(adminDraft.id)} className="admin-input" type="email" required value={adminDraft.email} onChange={e=>setAdminDraft({...adminDraft,email:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="admin-field-label">Rol<select className="admin-input" value={adminDraft.role} onChange={e=>setAdminDraft({...adminDraft,role:e.target.value as any})}><option value="superadmin">Superadmin</option><option value="manager">Manager</option><option value="operator">Operator</option></select></label><label className="admin-field-label">Alcance<select className="admin-input" value={adminDraft.brandScope} onChange={e=>setAdminDraft({...adminDraft,brandScope:e.target.value as any})}><option value="">Todas las marcas</option><option value="amargos">Bien Amargos</option><option value="enyerbados">Bien Yerbados</option></select></label></div><label className="admin-field-label">{adminDraft.id?'Nueva contraseña (opcional)':'Contraseña inicial'}<div className="relative"><KeyRound size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-black/25"/><input className="admin-input !pl-9" type="password" minLength={8} required={!adminDraft.id} value={adminDraft.password} onChange={e=>setAdminDraft({...adminDraft,password:e.target.value})}/></div></label><label className="flex items-center gap-2 text-[10px] font-black"><input type="checkbox" checked={adminDraft.active} disabled={adminDraft.id===user.id} onChange={e=>setAdminDraft({...adminDraft,active:e.target.checked})}/> Usuario activo</label></div><button disabled={saveAdmin.isPending} className="admin-primary-button mt-6 w-full"><UserCog size={15}/>{saveAdmin.isPending?'Guardando…':'Guardar usuario'}</button></form></div>}
  </AdminPage>;
}
function BrandSettings({title,hero,whatsapp,instagram,email,onHero,onChange}:{title:string;hero:string;whatsapp:string;instagram:string;email:string;onHero:(v:string)=>void;onChange:(k:'Whatsapp'|'Instagram'|'Email',v:string)=>void}){return <AdminCard><AdminCardHeader title={title} description="Identidad y contacto de esta marca."/><div className="mt-5 grid gap-4"><label className="admin-field-label">Hero<input className="admin-input" value={hero} onChange={e=>onHero(e.target.value)}/></label><label className="admin-field-label">WhatsApp<input className="admin-input" value={whatsapp} onChange={e=>onChange('Whatsapp',e.target.value)}/></label><label className="admin-field-label">Instagram<input className="admin-input" value={instagram} onChange={e=>onChange('Instagram',e.target.value)}/></label><label className="admin-field-label">Email<input className="admin-input" type="email" value={email} onChange={e=>onChange('Email',e.target.value)}/></label></div></AdminCard>}
function Row({children}:{children:string}){return <div className="flex gap-2"><Check size={14} className="mt-0.5 shrink-0 text-[#efc51d]"/>{children}</div>}
