import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ChevronDown, ChevronUp, Filter, ShieldCheck } from 'lucide-react';
import { apiGet } from '@/lib/api';
import { AdminCard, AdminEmpty, AdminPage, AdminPageHeader } from '@/components/admin/AdminUI';

type Audit={id:number;action:string;entityType:string;entityId?:string|null;detailJson?:any;ipAddress?:string|null;createdAt:string;adminName?:string|null;adminEmail?:string|null};
const labels:Record<string,string>={
 'auth.login':'inició sesión','auth.logout':'cerró sesión','product.create':'creó un producto','product.update':'editó un producto','product.reorder':'reordenó la tienda','stock.adjust':'ajustó stock','order.status':'cambió el estado de un pedido','order.cancel':'canceló un pedido','order.note':'editó una nota interna','settings.update':'actualizó configuración','faq.create':'creó una FAQ','faq.update':'editó una FAQ','faq.delete':'eliminó una FAQ','banner.create':'creó un banner','banner.update':'editó un banner','banner.delete':'eliminó un banner','media.delete':'eliminó una imagen','admin.create':'creó un administrador','admin.update':'editó un administrador','world.create':'agregó un punto','world.update':'editó un punto','world.delete':'eliminó un punto','world.import':'importó Materos por el mundo'
};
export function AdminAudit(){
 const[action,setAction]=useState(''); const[entity,setEntity]=useState(''); const[open,setOpen]=useState<number|null>(null);
 const query=new URLSearchParams();if(action)query.set('action',action);if(entity)query.set('entity',entity);
 const q=useQuery({queryKey:['admin-audit',action,entity],queryFn:()=>apiGet<Audit[]>(`/api/admin/audit${query.toString()?`?${query}`:''}`)});
 const actions=useMemo(()=>Array.from(new Set((q.data||[]).map(x=>x.action))).sort(),[q.data]);
 return <AdminPage><AdminPageHeader eyebrow="Seguridad y trazabilidad" title="Auditoría" description="Un historial legible de los cambios importantes. El JSON técnico queda disponible solo cuando lo necesitás."/>
 <AdminCard><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-2 text-[10px] font-black text-black/42"><Filter size={14}/> Filtros</div><select value={action} onChange={e=>setAction(e.target.value)} className="admin-select-compact"><option value="">Todas las acciones</option>{actions.map(a=><option key={a} value={a}>{labels[a]||a}</option>)}</select><select value={entity} onChange={e=>setEntity(e.target.value)} className="admin-select-compact"><option value="">Todas las entidades</option>{['product','order','settings','faq','banner','media','admin','world','auth'].map(x=><option key={x} value={x}>{x}</option>)}</select></div>
 {q.data?.length?<div className="relative grid gap-2 before:absolute before:bottom-4 before:left-[17px] before:top-4 before:w-px before:bg-black/7">{q.data.map(a=>{const detail=parseDetail(a.detailJson);const summary=describeDetail(a.action,detail);return <article key={a.id} className="relative pl-11"><div className="absolute left-[10px] top-4 grid h-4 w-4 place-items-center rounded-full bg-[#164b36] ring-4 ring-[#f4f5f0]"><span className="h-1.5 w-1.5 rounded-full bg-white"/></div><div className="rounded-[18px] border border-black/7 bg-[#faf9f5] p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-[11px] leading-relaxed"><strong>{a.adminName||'Sistema'}</strong> <span className="text-black/48">{labels[a.action]||a.action}</span>{a.entityId&&<span className="font-mono-ui text-[8px] text-black/28"> · {a.entityType} #{a.entityId}</span>}</div>{summary&&<div className="mt-2 text-[10px] font-semibold leading-relaxed text-black/48">{summary}</div>}<div className="mt-2 text-[8px] text-black/30">{new Date(a.createdAt).toLocaleString('es-AR')} · {a.adminEmail||a.ipAddress||'sistema'}</div></div>{detail&&<button onClick={()=>setOpen(open===a.id?null:a.id)} className="admin-icon-button shrink-0">{open===a.id?<ChevronUp size={13}/>:<ChevronDown size={13}/>} Detalles</button>}</div>{open===a.id&&detail&&<pre className="mt-4 max-h-[260px] overflow-auto rounded-[14px] bg-[#111713] p-4 font-mono-ui text-[8px] leading-relaxed text-white/66">{JSON.stringify(detail,null,2)}</pre>}</div></article>})}</div>:<AdminEmpty title="Sin actividad registrada" description="Las próximas acciones importantes van a aparecer acá."/>}</AdminCard>
 <div className="mt-4 flex items-center gap-2 text-[9px] text-black/35"><ShieldCheck size={13}/> Las acciones críticas se registran desde el backend, no dependen del navegador.</div></AdminPage>;
}
function parseDetail(v:any){if(!v)return null;if(typeof v==='object')return v;try{return JSON.parse(v)}catch{return{detail:String(v)}}}
function describeDetail(action:string,d:any){if(!d)return'';if(action==='stock.adjust')return `Stock ${d.before??'—'} → ${d.after??'—'} (${Number(d.delta||0)>0?'+':''}${d.delta??0})${d.note?` · ${d.note}`:''}`;if(action==='order.status'||action==='order.cancel')return `${d.from||'—'} → ${d.to||'—'}`;if(action.startsWith('product.')&&d.name)return String(d.name);if(action.startsWith('admin.')&&d.role)return `Rol ${d.role}${d.brandScope?` · ${d.brandScope}`:' · todas las marcas'}`;if(action.startsWith('banner.')&&d.title)return String(d.title);return''}
