import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Columns3, Download, List, MessageCircle, Search, X, Clock3, MapPin, PackageCheck, Save, AlertTriangle } from 'lucide-react';
import { toast } from 'sonner';
import { apiGet, apiSend } from '@/lib/api';
import { useSearchParams } from 'react-router-dom';
import { dateTime, money } from '@/lib/format';
import type { OrderAdmin } from '@/lib/types';
import { AdminCard, AdminEmpty, AdminPage, AdminPageHeader, StatusPill } from '@/components/admin/AdminUI';
import { useAdmin } from '@/components/admin/AdminContext';

const statusLabels:Record<string,string>={pending:'Pendiente',confirmed:'Confirmado',preparing:'Preparando',ready:'Listo',completed:'Entregado',cancelled:'Cancelado',expired:'Vencido'};
const nextStatus:Record<string,string|undefined>={pending:'confirmed',confirmed:'preparing',preparing:'ready',ready:'completed'};
const nextAction:Record<string,string>={confirmed:'Confirmar',preparing:'Preparar',ready:'Marcar listo',completed:'Entregado'};
const boardStatuses=['pending','confirmed','preparing','ready'] as const;

export function AdminOrders(){
  const qc=useQueryClient();const{brand,can}=useAdmin();const[searchParams,setSearchParams]=useSearchParams();const status=searchParams.get('status')||'all';const initialSearch=searchParams.get('search')||'';const[view,setView]=useState<'list'|'board'>('list');const[search,setSearch]=useState(initialSearch);const[selected,setSelected]=useState<OrderAdmin|null>(null);
  const query=new URLSearchParams();if(brand!=='all')query.set('brand',brand);if(status!=='all'&&view==='list')query.set('status',status);if(search.trim())query.set('search',search.trim());
  const orders=useQuery({queryKey:['admin-orders',brand,status,view,search],queryFn:()=>apiGet<OrderAdmin[]>(`/api/admin/orders${query.toString()?`?${query}`:''}`)});
  const filtered=useMemo(()=>orders.data||[],[orders.data]);
  const update=useMutation({mutationFn:({id,next}:{id:number;next:string})=>apiSend(`/api/admin/orders/${id}/status`,'PATCH',{status:next}),onSuccess:()=>{toast.success('Estado actualizado.');setSelected(null);['admin-orders','admin-dashboard','admin-analytics','admin-products','admin-notifications'].forEach(k=>qc.invalidateQueries({queryKey:[k]}));},onError:(e:any)=>toast.error(e.message)});
  function setStatus(value:string){const next=new URLSearchParams(searchParams);if(value==='all')next.delete('status');else next.set('status',value);setSearchParams(next,{replace:true});}
  function exportCsv(){const rows=[['Código','Cliente','Teléfono','Estado','Fecha','Total'],...filtered.map(o=>[o.code,o.customerName,o.customerPhone,statusLabels[o.status]||o.status,o.createdAt,String(o.total)])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`pedidos-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
  return <AdminPage>
    <AdminPageHeader eyebrow="Operación" title="Pedidos" description="Un flujo controlado desde la reserva hasta la entrega." action={<button onClick={exportCsv} className="admin-secondary-button"><Download size={14}/> Exportar CSV</button>}/>
    <AdminCard className="p-3 sm:p-4"><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-black/[.04] px-3 py-2 text-[9px] font-black text-black/42">{brand==='all'?'Todo el negocio':brand==='amargos'?'Bien Amargos':'Bien Yerbados'}</span>{view==='list'&&<select value={status} onChange={e=>setStatus(e.target.value)} className="admin-select-compact"><option value="all">Todos los estados</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>}</div><div className="flex flex-col gap-2 sm:flex-row"><label className="admin-search-field min-w-[280px]"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Código, cliente o teléfono"/></label><div className="admin-view-toggle"><button aria-label="Lista" className={view==='list'?'is-active':''} onClick={()=>setView('list')}><List size={15}/></button><button aria-label="Kanban" className={view==='board'?'is-active':''} onClick={()=>setView('board')}><Columns3 size={15}/></button></div></div></div></AdminCard>
    {view==='board'?<div className="mt-5 grid gap-4 xl:grid-cols-4">{boardStatuses.map(s=><section key={s}><div className="mb-3 flex items-center justify-between px-1"><div className="text-xs font-black">{statusLabels[s]}</div><span className="rounded-full bg-black/5 px-2 py-1 text-[9px] font-black text-black/40">{filtered.filter(o=>o.status===s).length}</span></div><div className="grid gap-3">{filtered.filter(o=>o.status===s).map(o=><OrderBoardCard key={o.id} order={o} open={()=>setSelected(o)} update={(next)=>update.mutate({id:o.id,next})} canUpdate={can('orders.update_status')}/>) }{!filtered.some(o=>o.status===s)&&<div className="rounded-[22px] border border-dashed border-black/10 p-6 text-center text-[10px] font-bold text-black/28">Sin pedidos</div>}</div></section>)}</div>:
    <><div className="mt-5 hidden overflow-hidden rounded-[22px] border border-black/7 bg-white md:block"><table className="admin-table w-full"><thead><tr><th>Código</th><th>Cliente</th><th>Estado</th><th>Entrega</th><th>Marca</th><th>Total</th><th>Fecha</th></tr></thead><tbody>{filtered.map(order=><tr key={order.id} onClick={()=>setSelected(order)} className="cursor-pointer"><td className="font-mono-ui text-[9px] font-black">{order.code}</td><td><div className="font-black">{order.customerName}</div><div className="mt-1 text-[9px] text-black/35">{order.customerPhone}</div></td><td><StatusPill status={order.status}/></td><td className="text-[10px] font-bold">{order.deliveryType==='pickup'?'Retiro':'Envío'}</td><td><div className="flex gap-1">{Array.from(new Set(order.items.map(i=>i.brandId))).map(b=><span key={b} className={`admin-brand-chip ${b==='amargos'?'admin-brand-chip--green':'admin-brand-chip--yellow'}`}>{b==='amargos'?'A':'Y'}</span>)}</div></td><td className="font-black">{money(order.total)}</td><td className="text-[10px] font-bold text-black/40">{dateTime(order.createdAt)}</td></tr>)}</tbody></table></div><div className="mt-5 grid gap-2 md:hidden">{filtered.map(order=><button key={order.id} onClick={()=>setSelected(order)} className="rounded-[18px] border border-black/7 bg-white p-4 text-left"><div className="flex items-start justify-between gap-3"><div><div className="font-mono-ui text-[8px] text-black/35">{order.code}</div><div className="mt-1 text-sm font-black">{order.customerName}</div></div><StatusPill status={order.status}/></div><div className="mt-3 flex items-center justify-between text-[10px] text-black/45"><span>{order.deliveryType==='pickup'?'Retiro':'Envío'} · {dateTime(order.createdAt)}</span><b className="text-sm text-black">{money(order.total)}</b></div></button>)}</div></>}
    {!filtered.length&&!orders.isLoading&&<AdminEmpty title="No hay pedidos" description="No encontramos resultados con estos filtros."/>}
    {selected&&<OrderDrawer order={selected} close={()=>setSelected(null)} update={(next)=>update.mutate({id:selected.id,next})} pending={update.isPending} canUpdate={can('orders.update_status')} canCancel={can('orders.cancel')} onSaved={()=>qc.invalidateQueries({queryKey:['admin-orders']})}/>} 
  </AdminPage>;
}

function OrderBoardCard({order,update,open,canUpdate}:{order:OrderAdmin;update:(next:string)=>void;open:()=>void;canUpdate:boolean}){const next=nextStatus[order.status];return <div className="rounded-[20px] border border-black/7 bg-white p-4 shadow-sm"><button onClick={open} className="w-full text-left"><div className="flex items-start justify-between"><div><div className="font-mono-ui text-[8px] text-black/30">{order.code}</div><div className="mt-1 text-sm font-black">{order.customerName}</div></div><div className="text-sm font-black">{money(order.total)}</div></div><div className="mt-3 line-clamp-2 text-[10px] text-black/38">{order.items.slice(0,2).map(i=>`${i.qty}× ${i.productName}${i.variantValue?` · ${i.variantValue}`:''}`).join(' · ')}{order.items.length>2?` +${order.items.length-2}`:''}</div></button><div className="mt-4 flex gap-2"><a href={`https://wa.me/${order.customerPhone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer" className="grid h-9 w-9 place-items-center rounded-xl bg-[#25D366]/15 text-[#0c7137]"><MessageCircle size={14}/></a>{canUpdate&&order.canOperate!==false&&next&&<button onClick={()=>update(next)} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#111713] px-3 text-[9px] font-black text-white">{nextAction[next]||statusLabels[next]} →</button>}</div></div>}

function OrderDrawer({order,close,update,pending,canUpdate,canCancel,onSaved}:{order:OrderAdmin;close:()=>void;update:(next:string)=>void;pending:boolean;canUpdate:boolean;canCancel:boolean;onSaved:()=>void}){
 const[note,setNote]=useState(order.internalNote||'');const noteSave=useMutation({mutationFn:()=>apiSend(`/api/admin/orders/${order.id}/note`,'PUT',{note}),onSuccess:()=>{toast.success('Nota guardada.');onSaved();},onError:(e:any)=>toast.error(e.message)});const next=nextStatus[order.status];
 return <div className="fixed inset-0 z-[230] bg-black/35" onMouseDown={close}><aside className="absolute right-0 top-0 h-full w-full max-w-2xl overflow-y-auto bg-[#f6f3eb] shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="sticky top-0 z-10 flex items-start justify-between border-b border-black/7 bg-[#f6f3eb]/95 p-5 backdrop-blur-xl"><div><div className="font-mono-ui text-[8px] uppercase tracking-[.16em] text-black/35">{order.code}</div><div className="mt-1 flex items-center gap-2"><h2 className="text-2xl font-black">{order.customerName}</h2><StatusPill status={order.status}/></div><div className="mt-1 text-[10px] text-black/40">{dateTime(order.createdAt)}</div></div><button onClick={close} className="grid h-10 w-10 place-items-center rounded-xl bg-black/5"><X size={16}/></button></div><div className="grid gap-5 p-5">
   {order.canOperate===false&&<div className="flex gap-3 rounded-[16px] bg-amber-50 p-4 text-[10px] font-bold text-amber-800"><AlertTriangle size={16} className="shrink-0"/>Este pedido mezcla marcas fuera de tu alcance. Podés verlo, pero no cambiar su estado.</div>}
   <section className="grid gap-3 rounded-[20px] border border-black/7 bg-white p-4 sm:grid-cols-2"><div><div className="admin-eyebrow">Cliente</div><div className="mt-2 text-sm font-black">{order.customerName}</div><div className="mt-1 text-[10px] text-black/40">{order.customerPhone}</div><a href={`https://wa.me/${order.customerPhone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer" className="admin-secondary-button mt-3 w-fit"><MessageCircle size={14}/> WhatsApp</a></div><div><div className="admin-eyebrow">Entrega</div><div className="mt-2 flex items-center gap-2 text-sm font-black">{order.deliveryType==='pickup'?<PackageCheck size={15}/>:<MapPin size={15}/>} {order.deliveryType==='pickup'?'Retiro coordinado':'Envío'}</div>{order.address&&<div className="mt-2 text-[10px] leading-relaxed text-black/45">{order.address}</div>}</div></section>
   <section><div className="admin-eyebrow">Productos</div><div className="mt-3 grid gap-2">{order.items.map((item,idx)=><div key={idx} className="flex items-center gap-3 rounded-[16px] border border-black/7 bg-white p-3">{item.imageUrl?<img src={item.imageUrl} alt="" className="h-12 w-12 rounded-[12px] bg-[#f2eee4] object-contain p-1"/>:<div className="h-12 w-12 rounded-[12px] bg-black/5"/>}<div className="min-w-0 flex-1"><div className="text-xs font-black">{item.qty}× {item.productName}{item.variantValue?` · ${item.variantValue}`:''}</div><div className="mt-1 font-mono-ui text-[8px] text-black/30">{item.variantSku||item.sku} · {item.brandId==='amargos'?'Bien Amargos':'Bien Yerbados'}</div></div><div className="text-xs font-black">{money(item.lineTotal)}</div></div>)}</div><div className="mt-3 flex items-center justify-between rounded-[16px] bg-[#111713] px-4 py-3 text-white"><span className="text-[10px] font-bold text-white/55">Total</span><strong className="text-lg">{money(order.total)}</strong></div></section>
   <section><div className="admin-eyebrow">Timeline</div><div className="mt-3 grid gap-2"><div className="flex gap-3 rounded-[14px] bg-white p-3"><Clock3 size={14} className="mt-0.5 text-black/30"/><div><div className="text-[10px] font-black">Pedido creado</div><div className="mt-1 text-[8px] text-black/35">{dateTime(order.createdAt)}</div></div></div>{(order.events||[]).map((ev,i)=><div key={i} className="flex gap-3 rounded-[14px] bg-white p-3"><Clock3 size={14} className="mt-0.5 text-[#164b36]"/><div><div className="text-[10px] font-black">{statusLabels[ev.fromStatus||'']||ev.fromStatus||'Estado'} → {statusLabels[ev.toStatus]||ev.toStatus}</div><div className="mt-1 text-[8px] text-black/35">{dateTime(ev.createdAt)}</div></div></div>)}</div></section>
   <section className="rounded-[20px] border border-black/7 bg-white p-4"><div className="admin-eyebrow">Nota interna</div><textarea className="admin-input mt-3 min-h-[100px]" value={note} onChange={e=>setNote(e.target.value)} placeholder="No se envía al cliente."/><button onClick={()=>noteSave.mutate()} disabled={noteSave.isPending} className="admin-secondary-button mt-3"><Save size={14}/> Guardar nota</button></section>
   {canUpdate&&order.canOperate!==false&&<section className="rounded-[20px] border border-black/7 bg-white p-4"><div className="admin-eyebrow">Acciones</div><div className="mt-3 flex flex-wrap gap-2">{next&&<button disabled={pending} onClick={()=>update(next)} className="admin-primary-button">{nextAction[next]||statusLabels[next]}</button>}{canCancel&&['pending','confirmed','preparing'].includes(order.status)&&<button disabled={pending} onClick={()=>confirm('Cancelar este pedido restaurará el stock. ¿Continuar?')&&update('cancelled')} className="admin-danger-button">Cancelar pedido</button>}</div></section>}
 </div></aside></div>;
}
