import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bot, Eye, EyeOff, Pencil, Plus, Save, Send, Sparkles, Trash2, X } from 'lucide-react';
import { toast } from 'sonner';
import { apiGet, apiSend } from '@/lib/api';
import type { FaqItem } from '@/lib/types';
import { AdminCard, AdminEmpty, AdminPage, AdminPageHeader } from '@/components/admin/AdminUI';

type Draft={question:string;answer:string;keywords:string;category:string;sortOrder:number;active:boolean};
type TestResult={matched:boolean;score:number;faq?:{id:number;question:string;category:string}|null;response:string};
const empty:Draft={question:'',answer:'',keywords:'',category:'Compra',sortOrder:10,active:true};

export function AdminFaqs(){
  const qc=useQueryClient(); const[editing,setEditing]=useState<number|null>(null); const[draft,setDraft]=useState<Draft>(empty); const[testQuestion,setTestQuestion]=useState(''); const[testResult,setTestResult]=useState<TestResult|null>(null);
  const q=useQuery({queryKey:['admin-faqs'],queryFn:()=>apiGet<FaqItem[]>('/api/admin/faqs')});
  const save=useMutation({mutationFn:()=>editing?apiSend(`/api/admin/faqs/${editing}`,'PUT',draft):apiSend('/api/admin/faqs','POST',draft),onSuccess:()=>{toast.success('FAQ guardada.');setEditing(null);setDraft(empty);qc.invalidateQueries({queryKey:['admin-faqs']});qc.invalidateQueries({queryKey:['faqs']});},onError:(e:any)=>toast.error(e.message)});
  const del=useMutation({mutationFn:(id:number)=>apiSend(`/api/admin/faqs/${id}`,'DELETE'),onSuccess:()=>{toast.success('FAQ eliminada.');qc.invalidateQueries({queryKey:['admin-faqs']});qc.invalidateQueries({queryKey:['faqs']});},onError:(e:any)=>toast.error(e.message)});
  const tester=useMutation({mutationFn:()=>apiSend<TestResult>('/api/admin/faqs/test','POST',{question:testQuestion}),onSuccess:setTestResult,onError:(e:any)=>toast.error(e.message)});
  function edit(f:FaqItem){setEditing(f.id);setDraft({question:f.question,answer:f.answer,keywords:f.keywords||'',category:f.category,sortOrder:f.sortOrder,active:Boolean(f.active)});window.scrollTo({top:0,behavior:'smooth'});}
  function submit(e:FormEvent){e.preventDefault();save.mutate();}
  return <AdminPage>
    <AdminPageHeader eyebrow="Cana · Ayudante de ronda" title="Preguntas frecuentes" description="Administrá el conocimiento real de Cana y probalo antes de publicarlo." action={<button onClick={()=>{setEditing(null);setDraft(empty)}} className="admin-primary-button"><Plus size={15}/> Nueva FAQ</button>}/>
    <div className="grid gap-5 2xl:grid-cols-[.86fr_1.05fr_.8fr]">
      <AdminCard><form onSubmit={submit} className="grid gap-4"><div className="flex items-center justify-between"><div><div className="text-sm font-black">{editing?'Editar respuesta':'Nueva respuesta'}</div><div className="mt-1 text-[10px] text-black/38">Información concreta, administrable y sin alucinaciones.</div></div>{editing&&<button type="button" onClick={()=>{setEditing(null);setDraft(empty)}} className="admin-icon-button"><X size={15}/></button>}</div><label className="admin-field-label">Pregunta<input className="admin-input" required value={draft.question} onChange={e=>setDraft(x=>({...x,question:e.target.value}))}/></label><label className="admin-field-label">Respuesta<textarea className="admin-input min-h-[130px] resize-y" required value={draft.answer} onChange={e=>setDraft(x=>({...x,answer:e.target.value}))}/></label><label className="admin-field-label">Palabras clave<input className="admin-input" value={draft.keywords} onChange={e=>setDraft(x=>({...x,keywords:e.target.value}))} placeholder="envio,enviar,correo,despacho"/><span>Separalas con coma. Cana también compara contra la pregunta.</span></label><div className="grid gap-3 sm:grid-cols-2"><label className="admin-field-label">Categoría<select className="admin-input" value={draft.category} onChange={e=>setDraft(x=>({...x,category:e.target.value}))}>{['Compra','Envíos','Retiros','Pagos','Productos','Stock','Bien Amargos','Bien Yerbados','Materos por el mundo','General'].map(v=><option key={v}>{v}</option>)}</select></label><label className="admin-field-label">Orden<input className="admin-input" type="number" min="0" value={draft.sortOrder} onChange={e=>setDraft(x=>({...x,sortOrder:Number(e.target.value)}))}/></label></div><button type="button" onClick={()=>setDraft(x=>({...x,active:!x.active}))} className="admin-secondary-button w-fit">{draft.active?<><Eye size={14}/> Visible</>:<><EyeOff size={14}/> Oculta</>}</button><button className="admin-primary-button justify-center"><Save size={15}/>{save.isPending?'Guardando…':'Guardar'}</button></form></AdminCard>
      <AdminCard><div className="mb-4"><div className="text-sm font-black">Base de conocimiento</div><div className="mt-1 text-[10px] text-black/35">{q.data?.length||0} respuestas configuradas</div></div>{q.data?.length?<div className="grid max-h-[680px] gap-3 overflow-y-auto pr-1">{q.data.map(f=><article key={f.id} className="rounded-[18px] border border-black/7 bg-[#faf8f2] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#153f2f]/8 px-2 py-1 text-[8px] font-black text-[#153f2f]">{f.category}</span><span className="text-[8px] font-bold text-black/28">Orden {f.sortOrder}</span>{!f.active&&<span className="text-[8px] font-black text-red-500">Oculta</span>}</div><div className="mt-2 text-sm font-black">{f.question}</div><div className="mt-1 text-[10px] leading-relaxed text-black/44">{f.answer}</div><div className="mt-2 break-words font-mono-ui text-[8px] text-black/28">{f.keywords||'Sin keywords'}</div></div><div className="flex shrink-0 gap-1"><button onClick={()=>edit(f)} className="admin-icon-button !p-2"><Pencil size={14}/></button><button onClick={()=>confirm('¿Eliminar esta FAQ?')&&del.mutate(f.id)} className="admin-icon-button !p-2 text-red-600"><Trash2 size={14}/></button></div></div></article>)}</div>:<AdminEmpty title="Sin preguntas" description="Cargá las respuestas que Cana puede usar."/>}</AdminCard>
      <AdminCard className="2xl:sticky 2xl:top-[94px] 2xl:self-start"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-[16px] bg-[#efc51d] text-[#183526]"><Bot size={20}/></div><div><div className="text-sm font-black">Cana Lab</div><div className="mt-1 text-[9px] text-black/35">Probá exactamente qué contestaría.</div></div></div><div className="mt-5 rounded-[20px] bg-[#143b2b] p-4 text-white"><div className="font-mono-ui text-[7px] uppercase tracking-[.18em] text-white/38">Pregunta del cliente</div><textarea value={testQuestion} onChange={e=>setTestQuestion(e.target.value)} placeholder="Ej. ¿Hacen envíos a todo el país?" className="mt-3 min-h-[90px] w-full resize-none rounded-[14px] border border-white/10 bg-white/7 p-3 text-[11px] font-semibold text-white outline-none placeholder:text-white/22 focus:border-white/25"/><button disabled={!testQuestion.trim()||tester.isPending} onClick={()=>tester.mutate()} className="mt-3 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-[13px] bg-[#efc51d] text-[9px] font-black text-[#17311f] disabled:opacity-40"><Send size={13}/>{tester.isPending?'Probando…':'Probar a Cana'}</button></div>{testResult&&<div className={`mt-4 rounded-[18px] border p-4 ${testResult.matched?'border-emerald-800/10 bg-emerald-50/65':'border-amber-800/10 bg-amber-50/70'}`}><div className="flex items-center gap-2 font-mono-ui text-[7px] uppercase tracking-[.14em] text-black/38"><Sparkles size={12}/>{testResult.matched?`Match · score ${testResult.score}`:'Sin coincidencia'}</div>{testResult.faq&&<div className="mt-2 text-[9px] font-black text-black/55">{testResult.faq.question} · {testResult.faq.category}</div>}<div className="mt-3 text-[11px] font-semibold leading-relaxed text-black/62">{testResult.response}</div></div>}<div className="mt-4 text-[9px] leading-relaxed text-black/35">Este laboratorio usa el mismo matching del backend. Si no hay coincidencia, muestra el fallback real de WhatsApp.</div></AdminCard>
    </div>
  </AdminPage>;
}
