import { useCallback, useEffect, useState } from 'react';
import useEmblaCarousel from 'embla-carousel-react';
import { ArrowLeft, ArrowRight, ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'motion/react';
import type { BrandId } from '@/lib/types';
import { BrandGlyph } from './BrandGlyph';
import { AnimatedContent } from '@/components/motion/AnimatedContent';

type Category={id:number;brandId:BrandId;name:string;slug:string;imageUrl?:string|null;iconKey?:string|null};
const assets:Record<string,string>={mates:'/catalog/categories/mates.webp',bombillas:'/catalog/categories/bombillas.webp',termos:'/catalog/categories/termos.webp',canastas:'/catalog/categories/canastas.webp',combos:'/catalog/categories/combos.webp',accesorios:'/catalog/categories/accesorios.webp',yerbas:'/catalog/categories/yerbas.webp',yerberos:'/catalog/categories/yerberos.webp',dispensers:'/catalog/categories/dispensers.webp'};

export function CategoryShowcase({brand,categories}:{brand:BrandId;categories:Category[]}){
  const en=brand==='enyerbados';
  const [emblaRef,emblaApi]=useEmblaCarousel({align:'start',containScroll:'trimSnaps',dragFree:true,breakpoints:{'(min-width: 1024px)':{active:false}}});
  const [canPrev,setCanPrev]=useState(false);const[canNext,setCanNext]=useState(false);
  const update=useCallback(()=>{if(!emblaApi)return;setCanPrev(emblaApi.canScrollPrev());setCanNext(emblaApi.canScrollNext());},[emblaApi]);
  useEffect(()=>{if(!emblaApi)return;update();emblaApi.on('select',update).on('reInit',update);return()=>{emblaApi.off('select',update);emblaApi.off('reInit',update);};},[emblaApi,update]);
  if(!categories.length)return null;
  return <section id="categorias" className="relative px-4 pb-12 pt-12 sm:px-6 sm:pt-16 lg:px-10 lg:pb-16 lg:pt-20"><div className="mx-auto max-w-[1580px]"><AnimatedContent className="mb-7 flex items-end justify-between gap-5 sm:mb-9"><div><div className="font-mono-ui text-[8px] font-bold uppercase tracking-[.24em] text-black/36">Categorías</div><h2 className="mt-2 text-4xl font-black tracking-[-.06em] text-[#12261b] sm:text-5xl lg:text-[64px]">Todo para tu ronda.</h2></div><div className="hidden items-center gap-2 sm:flex"><button disabled={!canPrev} onClick={()=>emblaApi?.scrollPrev()} className="grid h-10 w-10 place-items-center rounded-full border border-black/8 bg-white/72 transition enabled:hover:bg-white disabled:opacity-20 lg:hidden" aria-label="Categorías anteriores"><ArrowLeft size={15}/></button><button disabled={!canNext} onClick={()=>emblaApi?.scrollNext()} className="grid h-10 w-10 place-items-center rounded-full border border-black/8 bg-white/72 transition enabled:hover:bg-white disabled:opacity-20 lg:hidden" aria-label="Más categorías"><ArrowRight size={15}/></button><Link to={`/catalogo?brand=${brand}`} className="hidden items-center gap-2 rounded-full border border-black/8 bg-white/72 px-4 py-2.5 text-xs font-black sm:flex">Ver todo <ArrowUpRight size={15}/></Link></div></AnimatedContent>
    <div ref={emblaRef} className="overflow-hidden lg:overflow-visible"><div className="-ml-3 flex touch-pan-y lg:ml-0 lg:grid lg:grid-cols-5 lg:gap-3">{categories.map((cat,idx)=>{const image=cat.imageUrl||assets[cat.slug]||(en?'/brand/yerbas-stock.webp':'/brand/repisa.webp');const studio=['mates','bombillas','termos','canastas','combos','accesorios'].includes(cat.slug);return <motion.div key={cat.id} initial={{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.36,ease:[.22,1,.36,1]}} className="min-w-0 flex-[0_0_44%] pl-3 min-[390px]:flex-[0_0_42%] sm:flex-[0_0_31%] md:flex-[0_0_24%] lg:pl-0"><Link to={`/catalogo?brand=${brand}&category=${encodeURIComponent(cat.slug)}`} className="category-card-v5 group relative block aspect-[.84] overflow-hidden rounded-[22px] border border-white/35 lg:aspect-[.82]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_30%,rgba(255,255,255,.98),rgba(235,228,215,.94)_62%,rgba(203,191,170,.88))]"/><img src={image} alt={cat.name} loading="lazy" decoding="async" className={`absolute inset-0 h-full w-full transition duration-500 group-hover:scale-[1.025] ${studio?'object-contain p-3 mix-blend-multiply sm:p-5':'object-cover'}`}/><div className="absolute inset-0 bg-gradient-to-t from-[#07120c]/78 via-transparent to-white/[.02]"/><div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-4 text-white"><div><div className="mb-1.5 flex items-center gap-1.5 font-mono-ui text-[6px] uppercase tracking-[.18em] text-white/48">{String(idx+1).padStart(2,'0')}{(cat.slug==='mates'||cat.slug==='yerbas')&&<BrandGlyph kind={cat.slug==='yerbas'?'yerba':'mate'} className="h-3.5 w-3.5"/>}</div><div className="text-[20px] font-black tracking-[-.05em] sm:text-[24px]">{cat.name}</div></div><span className="grid h-8 w-8 place-items-center rounded-full border border-white/28 bg-black/16 backdrop-blur-sm transition group-hover:bg-white group-hover:text-black"><ArrowUpRight size={13}/></span></div></Link></motion.div>})}</div></div>
    <div className="mt-5 flex items-center justify-between sm:hidden"><Link to={`/catalogo?brand=${brand}`} className="inline-flex items-center gap-2 rounded-full border border-black/9 bg-white/72 px-4 py-2.5 text-[10px] font-black">Ver categorías <ArrowUpRight size={13}/></Link><div className="font-mono-ui text-[7px] uppercase tracking-[.16em] text-black/28">Deslizá para explorar</div></div>
  </div></section>;
}
