import { Instagram, MessageCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useEffect, useRef, useState } from 'react';
import type { BrandId } from '@/lib/types';
import { BrandGlyph } from './BrandGlyph';
import { apiGet } from '@/lib/api';

type StoreSettings={settings:Record<string,string>;brands:{id:string;whatsapp?:string|null;instagram?:string|null;email?:string|null}[]};
export function Footer({brand}:{brand:BrandId}){const en=brand==='enyerbados';const root=useRef<HTMLElement|null>(null);const[visible,setVisible]=useState(false);useEffect(()=>{const node=root.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){setVisible(true);observer.disconnect();}},{rootMargin:'500px'});observer.observe(node);return()=>observer.disconnect();},[]);const q=useQuery({queryKey:['store-settings'],queryFn:({signal})=>apiGet<StoreSettings>('/api/store-settings',signal),staleTime:5*60_000,enabled:visible});const data=q.data?.brands.find(b=>b.id===brand);const whatsapp=(data?.whatsapp||'').replace(/\D/g,'')|| '5492257410476';const instagram=data?.instagram|| (en?'https://instagram.com/Enyerbate.ok':'https://instagram.com/bien.amargos');const ig=instagram.startsWith('http')?instagram:`https://instagram.com/${instagram.replace(/^@/,'')}`;
return <footer ref={root} id="contacto" className="relative bg-gradient-to-b from-transparent via-[#102319]/[.08] to-[#08110c]/20 px-3 pb-[calc(6rem+env(safe-area-inset-bottom))] pt-12 sm:px-5 sm:pb-12 lg:px-8 lg:pt-16"><div className="mx-auto max-w-[1640px] overflow-hidden rounded-[30px] border border-white/10 bg-[#0b110e]/97 text-white shadow-[0_24px_80px_rgba(0,0,0,.22)] sm:rounded-[38px]"><div className="grid gap-9 p-7 sm:p-10 lg:grid-cols-[1.3fr_.6fr_.6fr_.5fr] lg:p-12"><div><div className="flex items-center gap-3"><span className={`grid h-12 w-12 place-items-center rounded-[15px] ${en?'bg-[#d7c6ad] text-[#17311f]':'bg-white/10 text-white'}`}><BrandGlyph kind={en?'yerba':'mate'} className="h-7 w-7"/></span><div><div className="text-3xl font-black tracking-[-.055em] sm:text-4xl">{en?'Bien Yerbados':'Bien Amargos'}</div><div className="mt-2 font-mono-ui text-[7px] uppercase tracking-[.22em] text-white/30">Mar de Ajó · Argentina</div></div></div><p className="mt-6 max-w-sm text-xs font-semibold leading-relaxed text-white/42">Una misma ronda, dos marcas. Mates, accesorios y yerbas seleccionadas con identidad propia.</p></div><div><div className="footer-label">Tienda</div><div className="mt-4 grid gap-3 text-xs font-bold text-white/56"><Link to={`/catalogo?brand=${brand}`}>Productos</Link><Link to="/materos-por-el-mundo">Materos por el mundo</Link></div></div><div><div className="footer-label">Marcas</div><div className="mt-4 grid gap-3 text-xs font-bold text-white/56"><Link to="/">Bien Amargos</Link><Link to="/yerbados">Bien Yerbados</Link><Link to="/admin/login">Administración</Link></div></div><div><div className="footer-label">Hablemos</div><div className="mt-4 flex gap-2"><a className="footer-social" href={ig} target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={17}/></a><a className="footer-social" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle size={17}/></a></div>{data?.email&&<a href={`mailto:${data.email}`} className="mt-4 block text-[10px] font-bold text-white/42 hover:text-white">{data.email}</a>}</div></div><div className="flex flex-col gap-2 border-t border-white/8 px-7 py-5 font-mono-ui text-[7px] uppercase tracking-[.15em] text-white/26 sm:flex-row sm:justify-between sm:px-10 lg:px-12"><span>© 2026 {en?'Bien Yerbados':'Bien Amargos'}</span><span>Rondas en todos lados.</span></div></div></footer>}
