import { Home, Menu, Search, ShoppingBag, Store, X } from 'lucide-react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { FormEvent, useDeferredValue, useEffect, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import type { BrandId, Product } from '@/lib/types';
import { useCart } from '@/store/cart';
import { BrandGlyph } from './BrandGlyph';
import { apiGet } from '@/lib/api';
import { money } from '@/lib/format';
import { ProductImage } from './ProductImage';

export function Header({ brand, solid = false, hideMobileDock = false }: { brand: BrandId; solid?: boolean; hideMobileDock?: boolean }) {
  const [mobileOpen,setMobileOpen]=useState(false); const[scrolled,setScrolled]=useState(false); const[searchOpen,setSearchOpen]=useState(false); const[term,setTerm]=useState(''); const[dockCompact,setDockCompact]=useState(false);
  const navigate=useNavigate(); const location=useLocation(); const reduceMotion=useReducedMotion(); const lastY=useRef(0);
  const items=useCart(s=>s.items); const setCartOpen=useCart(s=>s.setOpen); const count=items.reduce((sum,item)=>sum+item.qty,0); const en=brand==='enyerbados';
  const deferredTerm=useDeferredValue(term.trim());
  const products=useQuery({
    queryKey:['store-search-products',brand,deferredTerm],
    queryFn:()=>apiGet<Product[]>(`/api/products?brand=${brand}&q=${encodeURIComponent(deferredTerm)}&limit=8`),
    enabled:searchOpen&&deferredTerm.length>=2,
    staleTime:5*60_000,
  });
  const results=products.data||[];
  useEffect(()=>{const onScroll=()=>{const y=window.scrollY;setScrolled(y>38);if(!hideMobileDock&&y>140){setDockCompact(y>lastY.current+5);}else setDockCompact(false);lastY.current=y;};onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll);},[hideMobileDock]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes((e.target as HTMLElement)?.tagName)){e.preventDefault();setSearchOpen(true);} if(e.key==='Escape'){setSearchOpen(false);setMobileOpen(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  useEffect(()=>setMobileOpen(false),[location.pathname,location.search]);
  const elevated=solid||scrolled||mobileOpen;
  const homePath=en?'/yerbados':'/'; const catalogPath=`/catalogo?brand=${brand}`;
  const homeActive=location.pathname===homePath; const catalogActive=location.pathname==='/catalogo'; const worldActive=location.pathname==='/materos-por-el-mundo';
  function submit(e:FormEvent){e.preventDefault();const q=term.trim();setSearchOpen(false);navigate(`/catalogo?brand=${brand}${q?`&q=${encodeURIComponent(q)}`:''}`);}
  const navClass=(active:boolean)=>`nav-link ${active?'nav-link--active':''}`;

  return <>
    <header className="pointer-events-none fixed inset-x-0 top-0 z-50 px-3 pt-[max(.65rem,env(safe-area-inset-top))] sm:px-5 sm:pt-4 lg:px-7 lg:pt-5">
      <div className={`pointer-events-auto mx-auto max-w-[1640px] overflow-hidden rounded-[22px] border transition-all duration-300 sm:rounded-[26px] ${elevated?'border-white/58 bg-[#f7f3e9]/97 shadow-[0_18px_56px_rgba(7,20,12,.16)] backdrop-blur-xl':'border-white/42 bg-[#f7f3e9]/93 shadow-[0_14px_42px_rgba(7,20,12,.11)] backdrop-blur-lg'}`}>
        <div className="flex h-[68px] items-center justify-between px-3.5 sm:h-[78px] sm:px-6 lg:h-[82px] lg:px-7">
          <Link to={homePath} className="flex min-w-0 items-center gap-3 text-[#13251b]"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-[14px] shadow-sm ${en?'bg-[#d7c6ad] text-[#17311f]':'bg-[#164b36] text-white'}`}><BrandGlyph kind={en?'yerba':'mate'} className="h-6 w-6"/></span><div className="min-w-0"><div className="truncate text-[14px] font-black tracking-[-.035em] sm:text-[16px]">{en?'Bien Yerbados':'Bien Amargos'}</div><div className="mt-1 hidden font-mono-ui text-[7px] uppercase tracking-[.22em] text-black/33 sm:block">Mar de Ajó · Argentina</div></div></Link>

          <nav className="hidden items-center gap-8 text-[11px] font-black text-[#182219] xl:flex"><Link className={navClass(homeActive)} to={homePath}>Inicio</Link><Link className={navClass(catalogActive)} to={catalogPath}>Tienda</Link><Link className={navClass(worldActive)} to="/materos-por-el-mundo">Materos por el mundo</Link><Link className="nav-link" to={`${homePath}#contacto`}>Contacto</Link></nav>

          <div className="flex items-center gap-2 sm:gap-2.5"><div className="hidden items-center rounded-[13px] border border-black/[.07] bg-white/62 p-1 lg:flex"><Link to="/" className={`inline-flex h-9 items-center gap-1.5 rounded-[9px] px-3 text-[9px] font-black transition ${!en?'bg-[#164b36] text-white':'text-[#263127] hover:bg-white'}`}><BrandGlyph kind="mate" className="h-4 w-4"/>Amargos</Link><Link to="/yerbados" className={`inline-flex h-9 items-center gap-1.5 rounded-[9px] px-3 text-[9px] font-black transition ${en?'bg-[#d7c6ad] text-[#17311f]':'text-[#263127] hover:bg-white'}`}><BrandGlyph kind="yerba" className="h-4 w-4"/>Yerbados</Link></div><button onClick={()=>setSearchOpen(true)} className="hidden h-11 w-11 place-items-center rounded-[13px] border border-black/[.07] bg-white/72 text-[#182219] transition hover:-translate-y-px md:grid" aria-label="Buscar"><Search size={18}/></button><button onClick={()=>setCartOpen(true)} className="relative grid h-11 w-11 place-items-center rounded-[13px] border border-black/[.07] bg-white/72 text-[#182219] transition active:scale-[.97]" aria-label="Carrito"><ShoppingBag size={18}/><AnimatePresence mode="popLayout">{count>0&&<motion.span key={count} initial={reduceMotion?false:{scale:.6,opacity:0}} animate={{scale:1,opacity:1}} exit={{scale:.7,opacity:0}} transition={{type:'spring',stiffness:420,damping:24}} className="absolute -right-1.5 -top-1.5 grid h-5 min-w-5 place-items-center rounded-full bg-[#d7c6ad] px-1 text-[8px] font-black text-[#17311f] shadow">{count}</motion.span>}</AnimatePresence></button><button className="grid h-11 w-11 place-items-center rounded-[13px] border border-black/[.07] bg-white/62 xl:hidden" onClick={()=>setMobileOpen(v=>!v)} aria-label="Menú" aria-expanded={mobileOpen}>{mobileOpen?<X size={20}/>:<Menu size={20}/>}</button></div>
        </div>
        <AnimatePresence initial={false}>{mobileOpen&&<motion.div initial={reduceMotion?false:{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:reduceMotion?0:.24,ease:[.22,1,.36,1]}} className="overflow-hidden border-t border-black/[.07] bg-[#f7f3e9]/98 xl:hidden"><motion.div initial="hidden" animate="show" variants={{hidden:{},show:{transition:{staggerChildren:reduceMotion?0:.045}}}} className="grid gap-1 p-3">{[[homePath,'Inicio'],[catalogPath,'Tienda'],['/materos-por-el-mundo','Materos por el mundo'],[`${homePath}#contacto`,'Contacto']].map(([to,label])=><motion.div key={to} variants={{hidden:{opacity:0,y:8},show:{opacity:1,y:0}}}><Link className="block rounded-[13px] px-3 py-3 text-sm font-black text-[#172119] transition hover:bg-white/70" to={to}>{label}</Link></motion.div>)}<motion.button variants={{hidden:{opacity:0,y:8},show:{opacity:1,y:0}}} onClick={()=>{setMobileOpen(false);setSearchOpen(true);}} className="flex items-center gap-2 rounded-[13px] px-3 py-3 text-left text-sm font-black hover:bg-white/70"><Search size={16}/> Buscar productos</motion.button><motion.div variants={{hidden:{opacity:0,y:8},show:{opacity:1,y:0}}} className="mt-2 grid grid-cols-2 gap-2"><Link to="/" className="flex min-h-11 items-center gap-2 rounded-[15px] bg-[#164b36] px-3 py-3 text-xs font-black text-white"><BrandGlyph kind="mate" className="h-5 w-5"/>Bien Amargos</Link><Link to="/yerbados" className="flex min-h-11 items-center gap-2 rounded-[15px] bg-[#d7c6ad] px-3 py-3 text-xs font-black text-[#17311f]"><BrandGlyph kind="yerba" className="h-5 w-5"/>Bien Yerbados</Link></motion.div></motion.div></motion.div>}</AnimatePresence>
      </div>
    </header>

    {!hideMobileDock&&<motion.nav animate={reduceMotion?undefined:{y:dockCompact?4:0,scale:dockCompact ? .97 : 1,opacity:dockCompact ? .92 : 1}} transition={{duration:.16}} className="mobile-dock fixed inset-x-3 z-40 flex items-center justify-around border border-white/48 bg-[#f7f3e9]/96 shadow-[0_14px_42px_rgba(7,20,12,.18)] backdrop-blur-xl sm:hidden" aria-label="Navegación rápida"><Link to={homePath} className={`mobile-dock-item ${homeActive?'is-active':''}`}><Home size={17}/><span>Inicio</span></Link><Link to={catalogPath} className={`mobile-dock-item ${catalogActive?'is-active':''}`}><Store size={17}/><span>Tienda</span></Link><button onClick={()=>setSearchOpen(true)} className="mobile-dock-item"><Search size={17}/><span>Buscar</span></button><button onClick={()=>setCartOpen(true)} className="mobile-dock-item relative"><ShoppingBag size={17}/><span>Carrito</span>{count>0&&<i>{count}</i>}</button></motion.nav>}

    <AnimatePresence>{searchOpen&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[120] bg-[#07110c]/56 p-3 pt-[max(9vh,env(safe-area-inset-top))] backdrop-blur-sm" onMouseDown={()=>setSearchOpen(false)}><motion.div initial={reduceMotion?false:{opacity:0,y:12,scale:.985}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:8,scale:.99}} transition={{duration:reduceMotion?0:.22}} onMouseDown={e=>e.stopPropagation()} className="mx-auto max-w-2xl overflow-hidden rounded-[26px] border border-white/25 bg-[#f7f3e9] shadow-[0_30px_100px_rgba(0,0,0,.30)]"><form onSubmit={submit} className="flex items-center gap-3 border-b border-black/7 px-4 py-4 sm:px-5"><Search size={19} className="text-black/32"/><input autoFocus value={term} onChange={e=>setTerm(e.target.value)} placeholder="Buscar mate, termo, bombilla, yerba…" className="min-w-0 flex-1 bg-transparent text-sm font-bold outline-none placeholder:text-black/25"/><span className="hidden rounded-lg bg-black/5 px-2 py-1 font-mono-ui text-[8px] text-black/35 sm:block">ESC</span></form><div className="max-h-[58vh] overflow-y-auto p-3">{results.map((p,index)=><motion.div key={p.id} initial={reduceMotion?false:{opacity:0,y:5}} animate={{opacity:1,y:0}} transition={{delay:reduceMotion?0:index*.025}}><Link onClick={()=>setSearchOpen(false)} to={`/producto/${p.slug}`} className="flex items-center gap-3 rounded-[16px] p-2.5 transition hover:bg-black/[.035]"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-[14px] bg-[#f5f2ea]"><ProductImage src={p.imageUrl} alt={p.name} categoryName={p.categoryName} zoom={p.imageZoom??1.08} positionX={p.imagePositionX??50} positionY={p.imagePositionY??50} blendMode={p.imageBlendMode??'normal'} /></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{p.name}</div><div className="mt-1 text-[9px] font-bold text-black/35">{p.categoryName||'Producto'} · {p.brandId==='amargos'?'Bien Amargos':'Bien Yerbados'}</div></div><div className="text-xs font-black">{money(p.price)}</div></Link></motion.div>)}{deferredTerm.length<2?<div className="p-10 text-center text-sm font-bold text-black/30">Escribí al menos 2 letras para buscar.</div>:!products.isLoading&&!results.length?<div className="p-10 text-center text-sm font-bold text-black/30">No encontramos productos con esa búsqueda.</div>:null}</div><button onClick={()=>{setSearchOpen(false);navigate(`/catalogo?brand=${brand}${term.trim()?`&q=${encodeURIComponent(term.trim())}`:''}`);}} className="flex min-h-12 w-full items-center justify-center border-t border-black/7 px-5 py-4 text-[10px] font-black text-black/55">Ver resultados en el catálogo →</button></motion.div></motion.div>}</AnimatePresence>
  </>;
}
